/**
 * Hand-rolled mock fixtures, keyed by daemon `kind`.
 *
 * Each entry is the `data` body of a successful envelope. Kept minimal
 * until Phase 1.2 §2.2 generates real fixtures from the Pydantic schema.
 * Add entries as screens get translated.
 */

import { MOCK_OVERVIEW } from "@/mocks/seed";
import { MOCK_TRANSACTIONS } from "@/mocks/transactions";
import { MOCK_PROFILES } from "@/mocks/profiles";
import { MOCK_WORKSPACE_OVERVIEW } from "@/mocks/workspaceOverview";
import { MOCK_CAPITAL_GAINS } from "@/mocks/reports";

const SOURCE_FUNDS_FIXTURE_TARGET_TXID =
  "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766";
const SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID =
  "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211";
const SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS = [
  {
    txid: SOURCE_FUNDS_FIXTURE_TARGET_TXID,
    asset: "BTC",
    network: "bitcoin",
    label: "mempool.space",
    url: `https://mempool.space/tx/${SOURCE_FUNDS_FIXTURE_TARGET_TXID}`,
  },
  {
    txid: SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
    asset: "BTC",
    network: "bitcoin",
    label: "mempool.space",
    url: `https://mempool.space/tx/${SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID}`,
  },
];

// One demo collateral mark, keyed to an outbound mock transaction (`tx16`,
// the Multisig Vault miner-fee send) so the "Collateral" badge lands on a real
// row in mock mode. Both `marks` and `open_locks` carry it; `open_locks` is the
// subset still locked (no matching release).
const COLLATERAL_MARK_FIXTURE = {
  transaction_id: "tx16",
  loan_id: "mock-loan-1",
  role: "collateral_lock",
  note: "Posted as collateral with Firefish.",
  created_at: "2026-03-25T21:05:00Z",
  direction: "outbound",
  asset: "BTC",
  amount: 0.0000341,
  occurred_at: "2026-03-25T21:03:00Z",
  description: "Miner fee · UTXO send",
};

function privacyFinding(
  code: string,
  severity: string,
  scope: string,
  count: number,
  impact: number,
  occurrences = 1,
  evidence_level = "heuristic",
  attribution = "user_wallet",
) {
  return {
    code,
    severity,
    scope,
    count,
    impact,
    occurrences,
    evidence_level,
    attribution,
    remediation:
      "Review this local tell manually; Kassiber does not mutate accounting state from privacy heuristics.",
  };
}

export const fixtures: Record<string, unknown> = {
  "ui.loans.list": {
    marks: [COLLATERAL_MARK_FIXTURE],
    open_locks: [COLLATERAL_MARK_FIXTURE],
    roles: [
      "collateral_lock",
      "collateral_release",
      "loan_principal_received",
      "loan_principal_repaid",
    ],
    role_labels: {
      collateral_lock: "BTC collateral posted for fiat loan (out)",
      collateral_release: "BTC collateral returned (in)",
      loan_principal_received: "BTC loan principal received (in)",
      loan_principal_repaid: "BTC loan principal repaid (out)",
    },
  },
  "ui.loans.mark": {
    transaction_id: "tx16",
    loan_id: "mock-loan-1",
    role: "collateral_lock",
  },
  "ui.loans.link": { loan_id: "mock-loan-1", transaction_ids: ["tx16", "tx17"] },
  "ui.loans.unmark": { transaction_id: "tx16" },
  status: {
    version: "0.0.0-ui-scaffold",
    project_id: "mock",
    project_name: "Mock Books",
    project_root: "~/.kassiber/projects/mock",
    data_root: "~/.kassiber/projects/mock/data",
    workspace: null,
    profile: null,
  },
  "ui.projects.list": {
    selected_project_id: "mock",
    projects: [
      {
        id: "mock",
        name: "Mock Books",
        path: "~/.kassiber/projects/mock",
        data_root: "~/.kassiber/projects/mock/data",
        database: "~/.kassiber/projects/mock/data/kassiber.sqlite3",
        encrypted: true,
        last_opened_at: "2026-07-01T09:00:00Z",
        selected: true,
      },
    ],
  },
  "ui.logs.snapshot": {
    records: [],
    last_id: 0,
    gap: false,
    started_at: "mock",
    buffer_bytes: 0,
    max_bytes: 4194304,
  },
  "ui.egress.snapshot": {
    records: [
      {
        id: 1,
        ts: "2026-07-01T09:00:00Z",
        subsystem: "sync",
        host: "mempool.bitcoin-austria.at",
        port: 443,
        scheme: "https",
        operation: "http.request",
        method: "GET",
        bytes_out: 312,
        via_proxy: false,
        allowlist_status: "expected",
        allowlist_label: "backend:mempool",
        allowlist_source: "built-in default",
        user_allowlisted: false,
      },
      {
        id: 2,
        ts: "2026-07-01T09:01:00Z",
        subsystem: "ai",
        host: "unexpected.example",
        port: 443,
        scheme: "https",
        operation: "http.request",
        method: "POST",
        bytes_out: 2048,
        via_proxy: false,
        allowlist_status: "unexpected",
        allowlist_label: null,
        allowlist_source: null,
        user_allowlisted: false,
      },
    ],
    last_id: 2,
    gap: false,
    started_at: "mock",
    buffer_bytes: 512,
    max_bytes: 2097152,
    allowlist_complete: true,
    allowlist: [],
    db_header: {
      exists: true,
      classification: "ciphertext-like",
      sqlite_plaintext_header: false,
      encrypted_like: true,
      prefix_hex: "8cf201b1bb7e412a6dbbbd99c3a31c0e",
    },
    summary: {
      total_records: 2,
      unexpected: 1,
      update: 0,
      by_subsystem: {
        ai: { records: 1, bytes_out: 2048 },
        sync: { records: 1, bytes_out: 312 },
      },
    },
  },
  "ui.overview.snapshot": MOCK_OVERVIEW,
  "ui.workspace.overview.snapshot": MOCK_WORKSPACE_OVERVIEW,
  "ui.review.badges": {
    quarantine: 2,
    journals_needs_processing: true,
    swaps: 3,
  },
  "ui.connections.node.snapshot": {
    error: "Pass `connection` to ui.connections.node.snapshot (handled in mock.ts).",
  },
  "ui.reports.lightning_profitability": {
    error: "Pass `connection` to ui.reports.lightning_profitability (handled in mock.ts).",
  },
  "ui.transactions.list": MOCK_TRANSACTIONS,
  "ui.transactions.extremes": {
    largest: MOCK_TRANSACTIONS.txs.slice(0, 3),
    smallest: MOCK_TRANSACTIONS.txs.slice(-3),
    filters: { limit: 3, sort: "amount", scope: "all_time_before_limit" },
  },
  "ui.transactions.search": {
    txs: MOCK_TRANSACTIONS.txs.slice(0, 4),
    filters: {
      query: "invoice",
      limit: 25,
      sort: "occurred-at",
      order: "desc",
    },
  },
  "ui.transactions.resolve": {
    transaction: null,
    query: "",
  },
  "ui.wallets.sync": {
    results: MOCK_OVERVIEW.connections.map((connection) => ({
      wallet: connection.label,
      status: "synced",
      inserted: 0,
      updated: 0,
    })),
  },
  "ui.wallets.utxos": {
    wallet: {
      id: "c1",
      label: "Cold Storage",
    },
    utxos: [
      {
        id: "coin-1",
        outpoint:
          "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766:0",
        txid: "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766",
        vout: 0,
        asset: "BTC",
        amount: 0.125,
        amount_sat: 12_500_000,
        amount_msat: 12_500_000_000,
        confirmation_status: "confirmed",
        confirmations: 18,
        block_height: 884_200,
        block_time: "2026-03-18T10:20:00Z",
        address: "bc1qmockcoinaddress0000000000000000000000000000",
        address_label: "receive #12",
        branch_label: "receive",
        branch_index: 0,
        address_index: 12,
        source: {
          backend: "mempool",
          backend_kind: "esplora",
          chain: "bitcoin",
          network: "mainnet",
          first_seen_at: "2026-03-18T10:22:00Z",
          last_seen_at: "2026-03-18T10:22:00Z",
          spent_at: null,
        },
      },
      {
        id: "coin-2",
        outpoint:
          "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211:1",
        txid: "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211",
        vout: 1,
        asset: "BTC",
        amount: 0.03125,
        amount_sat: 3_125_000,
        amount_msat: 3_125_000_000,
        confirmation_status: "mempool",
        confirmations: 0,
        block_height: null,
        block_time: null,
        address: "bc1qmockchangeaddress000000000000000000000000000",
        address_label: "change #4",
        branch_label: "change",
        branch_index: 1,
        address_index: 4,
        source: {
          backend: "mempool",
          backend_kind: "esplora",
          chain: "bitcoin",
          network: "mainnet",
          first_seen_at: "2026-03-18T10:24:00Z",
          last_seen_at: "2026-03-18T10:24:00Z",
          spent_at: null,
        },
      },
    ],
    totals: [
      {
        asset: "BTC",
        amount: 0.15625,
        amount_sat: 15_625_000,
        amount_msat: 15_625_000_000,
      },
    ],
    support: {
      supported: true,
      status: "supported",
      reason: "",
      message: "",
    },
    freshness: {
      status: "current",
      last_seen_at: "2026-03-18T10:24:00Z",
      last_synced_at: "2026-03-18T10:24:00Z",
      stale: false,
      active_count: 2,
    },
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 2,
    },
  },
  "ui.privacy_hygiene.snapshot": {
    profile: { id: "mock-profile", label: "local books" },
    scope: { wallet: null, transaction: null },
    summary: {
      state: "partial",
      wallet_count: 3,
      transaction_count: 24,
      risk_weight: 42,
      risk_count: 6,
      unknown_count: 3,
      risk_level: "high",
      finding_counts: {
        positive: 2,
        info: 3,
        low: 5,
        medium: 4,
        high: 1,
        critical: 1,
      },
      top_findings: [
        privacyFinding("address_reuse", "critical", "wallet", 2, -24, 1, "ground_truth"),
        privacyFinding("op_return_metadata", "high", "transaction", 1, -10, 1, "ground_truth"),
        privacyFinding("coinjoin_pattern", "positive", "transaction", 5, 24, 1, "imported", "local_data"),
      ],
    },
    coverage: {
      wallet_count: 3,
      wallets_with_inventory: 2,
      inventory_outputs: 18,
      active_utxos: 9,
      transaction_total: 24,
      transaction_full: 11,
      transaction_partial: 5,
      transaction_not_analysable: 8,
      transaction_scored: 16,
    },
    wallets: [
      {
        id: "c1",
        label: "Cold Storage",
        kind: "descriptor",
        state: "partial",
        transaction_count: 10,
        scored_transaction_count: 7,
        inventory_output_count: 12,
        active_utxo_count: 6,
        risk_weight: 34,
        risk_count: 5,
        unknown_count: 1,
        risk_level: "high",
        address: {
          known_address_count: 10,
          reused_address_count: 2,
          active_utxo_count: 6,
          dust_utxo_count: 1,
          script_type_counts: { p2wpkh: 9, p2tr: 3 },
        },
        finding_counts: {
          positive: 1,
          info: 1,
          low: 1,
          medium: 2,
          high: 0,
          critical: 1,
        },
        top_findings: [
          privacyFinding("address_reuse", "critical", "wallet", 2, -24, 1, "ground_truth"),
          privacyFinding("large_utxo_set", "medium", "wallet", 24, -8, 1, "ground_truth"),
        ],
      },
      {
        id: "c2",
        label: "BTCPay Store",
        kind: "btcpay",
        state: "not_enough_data",
        transaction_count: 8,
        scored_transaction_count: 0,
        inventory_output_count: 0,
        active_utxo_count: 0,
        risk_weight: 0,
        risk_count: 0,
        unknown_count: 1,
        risk_level: "none",
        address: {
          known_address_count: 0,
          reused_address_count: 0,
          active_utxo_count: 0,
          dust_utxo_count: 0,
          script_type_counts: {},
        },
        finding_counts: {
          positive: 0,
          info: 1,
          low: 0,
          medium: 0,
          high: 0,
          critical: 0,
        },
        top_findings: [
          privacyFinding("transaction_coverage_gap", "info", "wallet", 8, 0, 1, "unavailable"),
        ],
      },
      {
        id: "c3",
        label: "Postmix",
        kind: "wasabi",
        state: "address_only",
        transaction_count: 6,
        scored_transaction_count: 2,
        inventory_output_count: 6,
        active_utxo_count: 3,
        risk_weight: 0,
        risk_count: 0,
        unknown_count: 0,
        risk_level: "none",
        address: {
          known_address_count: 6,
          reused_address_count: 0,
          active_utxo_count: 3,
          dust_utxo_count: 0,
          script_type_counts: { p2wpkh: 6 },
        },
        finding_counts: {
          positive: 2,
          info: 0,
          low: 0,
          medium: 0,
          high: 0,
          critical: 0,
        },
        top_findings: [
          privacyFinding("coin_anonymity_evidence", "positive", "wallet", 3, 7, 1, "imported", "local_data"),
        ],
      },
    ],
    transactions: [
      {
        id: "tx-privacy-1",
        external_id:
          "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766",
        wallet_id: "c1",
        wallet_label: "Cold Storage",
        occurred_at: "2026-03-18T10:20:00Z",
        direction: "outbound",
        asset: "BTC",
        state: "full",
        risk_weight: 18,
        risk_count: 4,
        unknown_count: 0,
        risk_level: "medium",
        support: {
          level: "full",
          reason: null,
          input_count: 3,
          output_count: 3,
          known_input_values: 3,
          known_output_values: 3,
        },
        finding_counts: {
          positive: 0,
          info: 0,
          low: 2,
          medium: 3,
          high: 1,
          critical: 0,
        },
        top_findings: [
          privacyFinding("op_return_metadata", "high", "transaction", 1, -10, 1, "ground_truth"),
        ],
      },
      {
        id: "tx-privacy-2",
        external_id:
          "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211",
        wallet_id: "c1",
        wallet_label: "Cold Storage",
        occurred_at: "2026-03-20T12:00:00Z",
        direction: "outbound",
        asset: "BTC",
        state: "partial",
        risk_weight: 8,
        risk_count: 2,
        unknown_count: 0,
        risk_level: "low",
        support: {
          level: "partial",
          reason: "missing_prevout_or_output_values",
          input_count: 2,
          output_count: 2,
          known_input_values: 1,
          known_output_values: 2,
        },
        finding_counts: {
          positive: 0,
          info: 0,
          low: 1,
          medium: 2,
          high: 0,
          critical: 0,
        },
        top_findings: [
          privacyFinding("round_output_amount", "medium", "transaction", 1, -8),
        ],
      },
    ],
    findings: [],
    meta: {
      engine: "privacy_hygiene_phase1",
      local_only: true,
      egress: "none",
      scope: "single_transaction_and_address_level",
      phase2_deferred: [
        "cross_wallet_cluster_reconstruction",
        "boltzmann_entropy",
      ],
    },
  },
  "ui.freshness.run": {
    profile: { id: "mock-profile", label: "Demo book" },
    results: MOCK_OVERVIEW.connections.map((connection) => ({
      wallet: connection.label,
      status: "synced",
      inserted: 0,
      updated: 0,
    })),
    enqueued: [
      {
        job_type: "onchain_wallet_history",
        source_label: "Treasury watch-only",
        source_type: "onchain_wallet",
        status: "queued",
      },
      {
        job_type: "market_rate_coverage",
        source_label: "Market-rate coverage",
        source_type: "market_rates",
        status: "queued",
      },
      {
        job_type: "journal_refresh",
        source_label: "Journals",
        source_type: "journals",
        status: "queued",
      },
    ],
    completed: [
      {
        job_type: "onchain_wallet_history",
        source_label: "Treasury watch-only",
        source_type: "onchain_wallet",
        status: "done",
      },
      {
        job_type: "market_rate_coverage",
        source_label: "Market-rate coverage",
        source_type: "market_rates",
        status: "done",
      },
      {
        job_type: "journal_refresh",
        source_label: "Journals",
        source_type: "journals",
        status: "done",
      },
    ],
    sources: [
      {
        source_key: "onchain_wallet:mock-wallet",
        source_type: "onchain_wallet",
        source_label: "Treasury watch-only",
        status: "fresh",
        blocking_reports: false,
      },
      {
        source_key: "market_rates:mock-profile",
        source_type: "market_rates",
        source_label: "Market-rate coverage",
        status: "fresh",
        blocking_reports: false,
      },
      {
        source_key: "journals:mock-profile",
        source_type: "journals",
        source_label: "Journals",
        status: "fresh",
        blocking_reports: false,
      },
    ],
    jobs: [],
    summary: {
      sources: 3,
      active_jobs: 0,
      blocking_reports: 0,
      rate_limited: 0,
      failed: 0,
    },
  },
  "ui.transfers.suggest": {
    candidates: [
      {
        out_id: "tx:phoenix-out",
        in_id: "tx:liquid-in",
        out_asset: "BTC",
        in_asset: "LBTC",
        out_amount_msat: 100_000_000,
        in_amount_msat: 99_500_000,
        out_amount: 0.001,
        in_amount: 0.000995,
        out_wallet: "Phoenix LN",
        in_wallet: "Liquid Vault",
        out_wallet_kind: "phoenix",
        in_wallet_kind: "descriptor",
        out_occurred_at: "2026-03-14T17:30:00Z",
        in_occurred_at: "2026-03-14T17:32:00Z",
        confidence: "strong",
        method: "heuristic",
        payment_hash: null,
        swap_fee_msat: 500_000,
        swap_fee: 0.000005,
        swap_fee_kind: "combined",
        default_kind: "submarine-swap",
        default_policy: "carrying-value",
        conflict_set_id: "solo:phoenix-liquid",
        conflict_size: 1,
        rule_match: {
          rule_id: "rule:phoenix-liquid",
          rule_name: "Phoenix to Liquid",
          kind: "submarine-swap",
          policy: "carrying-value",
        },
      },
      {
        out_id: "tx:liquid-out",
        in_id: "tx:onchain-in",
        out_asset: "LBTC",
        in_asset: "BTC",
        out_amount_msat: 250_000_000,
        in_amount_msat: 249_300_000,
        out_amount: 0.0025,
        in_amount: 0.002493,
        out_wallet: "Liquid Vault",
        in_wallet: "Bitcoin Vault",
        out_wallet_kind: "descriptor",
        in_wallet_kind: "descriptor",
        out_occurred_at: "2026-03-15T08:10:00Z",
        in_occurred_at: "2026-03-15T09:45:00Z",
        confidence: "exact",
        method: "payment_hash",
        payment_hash: "mock-payment-hash",
        swap_fee_msat: 700_000,
        swap_fee: 0.000007,
        swap_fee_kind: "combined",
        default_kind: "peg-out",
        default_policy: "carrying-value",
        conflict_set_id: "solo:liquid-onchain",
        conflict_size: 1,
      },
    ],
    counts: {
      total: 2,
      exact: 1,
      strong: 1,
      conflicts: 0,
      rule_matches: 1,
    },
  },
  "ui.transfers.bulk_pair": {
    applied: [
      {
        id: "pair:exact",
        swap_fee_msat: 700_000,
      },
    ],
    summary: {
      count: 1,
      skipped_conflicts: 0,
      total_swap_fee_msat: 700_000,
    },
  },
  "ui.transfers.rules.apply": {
    applied: [
      {
        id: "pair:rule",
        swap_fee_msat: 500_000,
      },
    ],
    summary: {
      count: 1,
      remaining: 1,
      total_swap_fee_msat: 500_000,
    },
  },
  "ui.transfers.pair": {
    id: "pair:manual",
    swap_fee_msat: 500_000,
  },
  "ui.transfers.dismiss": {
    dismissed: "tx:phoenix-out->tx:liquid-in",
  },
  "ui.transfers.unpair": {
    deleted: "pair:manual",
  },
  "ui.transfers.update": {
    id: "pair:submarine",
    kind: "peg-out",
    policy: "carrying-value",
    notes: null,
    swap_fee_msat: 500_000,
    swap_fee_kind: "combined",
    confidence_at_pair: "strong",
    pair_source: "rule_auto",
    out_amount: null,
    deleted_at: null,
    created_at: "2026-03-14T17:35:00Z",
  },
  "ui.transfers.list": {
    pairs: [
      {
        id: "pair:submarine",
        out_transaction_id: "tx:phoenix-out",
        in_transaction_id: "tx:liquid-in",
        kind: "submarine-swap",
        policy: "carrying-value",
        notes: null,
        swap_fee_msat: 500_000,
        swap_fee_kind: "combined",
        confidence_at_pair: "strong",
        pair_source: "rule_auto",
        out_amount: null,
        deleted_at: null,
        created_at: "2026-03-14T17:35:00Z",
        out: {
          transaction_id: "tx:phoenix-out",
          external_id: "phoenix-out-1",
          wallet: "Phoenix LN",
          wallet_kind: "phoenix",
          asset: "BTC",
          occurred_at: "2026-03-14T17:30:00Z",
          amount: 0.001,
          amount_msat: 100_000_000,
          full_amount: 0.001,
          full_amount_msat: 100_000_000,
        },
        in: {
          transaction_id: "tx:liquid-in",
          external_id: "liquid-in-1",
          wallet: "Liquid Vault",
          wallet_kind: "descriptor",
          asset: "LBTC",
          occurred_at: "2026-03-14T17:32:00Z",
          amount: 0.000995,
          amount_msat: 99_500_000,
        },
      },
      {
        id: "pair:selftransfer",
        out_transaction_id: "tx:hot-out",
        in_transaction_id: "tx:cold-in",
        kind: "manual",
        policy: "carrying-value",
        notes: "Moved to cold storage.",
        swap_fee_msat: 1_200_000,
        swap_fee_kind: "network",
        confidence_at_pair: "exact",
        pair_source: "manual",
        out_amount: null,
        deleted_at: null,
        created_at: "2026-03-12T11:05:00Z",
        out: {
          transaction_id: "tx:hot-out",
          external_id: "hot-out-1",
          wallet: "Bitcoin Vault",
          wallet_kind: "descriptor",
          asset: "BTC",
          occurred_at: "2026-03-12T11:00:00Z",
          amount: 0.5,
          amount_msat: 50_000_000_000,
          full_amount: 0.5,
          full_amount_msat: 50_000_000_000,
        },
        in: {
          transaction_id: "tx:cold-in",
          external_id: "cold-in-1",
          wallet: "Cold Storage",
          wallet_kind: "descriptor",
          asset: "BTC",
          occurred_at: "2026-03-12T11:04:00Z",
          amount: 0.49998,
          amount_msat: 49_998_000_000,
        },
      },
    ],
  },
  "ui.transfers.rules.list": {
    rules: [
      {
        id: "rule:phoenix-liquid",
        name: "Phoenix to Liquid",
        predicate: {
          out_wallet_kind: "phoenix",
          in_asset: "LBTC",
          min_confidence: "strong",
        },
        kind: "submarine-swap",
        policy: "carrying-value",
        enabled: true,
        created_at: "2026-03-14T17:35:00Z",
        updated_at: "2026-03-14T17:35:00Z",
      },
    ],
  },
  "ui.transfers.rules.create": {
    id: "rule:new",
    name: "New swap rule",
    predicate: {},
    kind: "submarine-swap",
    policy: "carrying-value",
    enabled: true,
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:35:00Z",
  },
  "ui.transfers.rules.delete": {
    deleted: "rule:phoenix-liquid",
  },
  "ui.transfers.rules.set_enabled": {
    id: "rule:phoenix-liquid",
    name: "Phoenix to Liquid",
    predicate: {
      out_wallet_kind: "phoenix",
      in_asset: "LBTC",
      min_confidence: "strong",
    },
    kind: "submarine-swap",
    policy: "carrying-value",
    enabled: false,
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:40:00Z",
  },
  "ui.saved_views.list": {
    views: [],
  },
  "ui.saved_views.create": {
    id: "view:new",
    surface: "swap_candidates",
    name: "Review queue",
    filter: {},
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:35:00Z",
  },
  "ui.saved_views.delete": {
    deleted: "view:new",
  },
  "ui.backends.options": {
    backends: [
      {
        name: "mempool",
        kind: "esplora",
        chain: "bitcoin",
        network: "mainnet",
        has_url: true,
        is_default: true,
      },
      {
        name: "liquid",
        kind: "electrum",
        chain: "liquid",
        network: "liquidv1",
        has_url: true,
        is_default: false,
      },
      {
        name: "liquid-blockstream",
        kind: "electrum",
        chain: "liquid",
        network: "liquidv1",
        has_url: true,
        is_default: false,
      },
      {
        name: "btcpay-demo",
        kind: "btcpay",
        chain: "bitcoin",
        network: "mainnet",
        has_url: true,
        has_token: true,
        is_default: false,
      },
    ],
    summary: {
      count: 4,
      default_backend: "mempool",
    },
    suggestions: [
      {
        name: "mempool",
        label: "Built-in mempool.space Bitcoin backend",
        chain: "bitcoin",
        network: "mainnet",
      },
      {
        name: "liquid",
        label: "Built-in BullBitcoin Liquid Electrum backend",
        chain: "liquid",
        network: "liquidv1",
      },
      {
        name: "liquid-blockstream",
        label: "Built-in Blockstream Liquid Electrum backend",
        chain: "liquid",
        network: "liquidv1",
      },
    ],
  },
  "ui.profiles.snapshot": MOCK_PROFILES,
  "ui.reports.capital_gains": MOCK_CAPITAL_GAINS,
  "ui.reports.summary": {
    workspace: "My Books",
    profile: "local books",
    wallet: null,
    fiat_currency: "EUR",
    metrics: {
      wallets_in_scope: 2,
      assets_in_scope: 1,
      active_transactions: 12,
      excluded_transactions: 0,
      inbound_transactions: 7,
      outbound_transactions: 5,
      journal_entries: 18,
      quarantines: 0,
    },
    asset_flow: [
      {
        asset: "BTC",
        inbound_amount: 0.42,
        inbound_amount_sat: 42_000_000,
        inbound_amount_msat: 42_000_000_000,
        outbound_amount: 0.15,
        outbound_amount_sat: 15_000_000,
        outbound_amount_msat: 15_000_000_000,
        fee_amount: 0.0001,
        fee_amount_sat: 10_000,
        fee_amount_msat: 10_000_000,
      },
    ],
    wallet_flow: [],
  },
  "ui.reports.balance_sheet": {
    rows: [
      {
        account: "treasury",
        account_label: "Treasury",
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    totals_by_asset: [
      {
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    summary: { row_count: 1, asset_count: 1 },
  },
  "ui.reports.portfolio_summary": {
    rows: [
      {
        wallet: "Multisig Vault",
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        average_cost: 71_388.89,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    totals_by_asset: [
      {
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    summary: { row_count: 1, asset_count: 1 },
  },
  "ui.reports.tax_summary": {
    rows: [
      {
        row_type: "year_total",
        year: 2025,
        asset: "BTC",
        quantity: 0.253,
        quantity_msat: 25_300_000_000,
        proceeds: 17_991.95,
        cost_basis: 10_078.35,
        gain_loss: 7_913.6,
      },
    ],
    available_years: [2025, 2026],
    filters: { year: 2025 },
    summary: { row_count: 1, available_year_count: 2 },
  },
  "ui.reports.balance_history": {
    rows: [
      { period_start: "2026-01-01T00:00:00Z", asset: "BTC", quantity: 0.12 },
      { period_start: "2026-02-01T00:00:00Z", asset: "BTC", quantity: 0.18 },
      { period_start: "2026-03-01T00:00:00Z", asset: "BTC", quantity: 0.27 },
    ],
    filters: { interval: "month", limit: 120 },
    summary: { row_count: 3, total_row_count: 3, truncated: false },
  },
  "ui.reports.privacy_hygiene": {
    payload_schema_version: 1,
    redaction: "ai_export_safe",
    local_only: true,
    read_only: true,
    scope: {
      workspace: "active",
      profile: "active",
      workspace_selected: true,
      profile_selected: true,
    },
    summary: {
      finding_count: 3,
      highest_severity: "warning",
      remote_backend_count: 1,
      off_device_ai_provider_count: 0,
      wallet_count: 2,
      watch_only_material_wallet_count: 1,
      active_transaction_count: 12,
      privacy_boundary_transaction_count: 1,
      privacy_quarantine_count: 0,
    },
    facts: {
      database: { status: "encrypted_like", evidence_level: "exact" },
      network: {
        backend_count: 2,
        posture_counts: {
          on_device: 1,
          self_hosted: 0,
          shielded: 0,
          remote: 1,
          unknown: 0,
        },
        credentialed_backend_count: 1,
        proxy_configured_backend_count: 0,
        evidence_level: "derived",
      },
      ai: {
        provider_count: 1,
        local_provider_count: 1,
        remote_provider_count: 0,
        tee_provider_count: 0,
        cli_provider_count: 0,
        credentialed_provider_count: 0,
        unacknowledged_off_device_provider_count: 0,
        evidence_level: "exact",
      },
      wallets: {
        wallet_count: 2,
        watch_only_material_wallet_count: 1,
        backend_linked_wallet_count: 1,
        descriptor_wallet_count: 1,
        xpub_wallet_count: 0,
        address_wallet_count: 0,
        silent_payment_wallet_count: 0,
        source_file_wallet_count: 1,
        evidence_level: "exact",
      },
      transactions: {
        active_transaction_count: 12,
        excluded_transaction_count: 0,
        transaction_raw_json_count: 2,
        privacy_boundary_transaction_count: 1,
        evidence_level: "exact",
      },
      inventory: {
        utxo_count: 4,
        active_utxo_count: 3,
        utxos_with_address_count: 3,
        utxos_with_script_count: 3,
        utxos_with_derivation_metadata_count: 2,
        evidence_level: "exact",
      },
      journals: {
        status: "current",
        needs_processing: false,
        active_transaction_count: 12,
        journal_entry_count: 18,
        quarantine_count: 0,
        privacy_quarantine_count: 0,
        evidence_level: "exact",
      },
    },
    findings: [
      {
        id: "remote_backend_endpoints",
        category: "network",
        severity: "warning",
        title: "Third-party backend endpoints are configured",
        detail:
          "1 configured backend endpoint(s) are inferred as third-party and can observe wallet/indexer queries.",
        evidence_level: "derived",
        evidence: { remote_backend_count: 1 },
      },
      {
        id: "watch_only_wallet_material_present",
        category: "wallets",
        severity: "info",
        title: "Watch-only wallet material is stored locally",
        detail: "1 wallet(s) have watch-only material in the local database.",
        evidence_level: "exact",
        evidence: { watch_only_material_wallet_count: 1 },
      },
      {
        id: "privacy_boundary_transactions_present",
        category: "transactions",
        severity: "info",
        title: "Privacy-boundary transaction markers are present",
        detail:
          "1 transaction(s) carry a privacy-boundary marker; provenance across those hops remains opaque unless reviewed with stronger evidence.",
        evidence_level: "exact",
        evidence: { privacy_boundary_transaction_count: 1 },
      },
    ],
    limitations: [
      {
        code: "local_only_no_probe",
        message:
          "No network request was made; endpoint posture is inferred from local configuration only.",
        evidence_level: "derived",
      },
      {
        code: "redacted_payload",
        message:
          "Addresses, scripts, descriptors, xpubs, backend URLs/tokens, wallet config, raw_json, branch/index values, and derivation paths are omitted from this payload.",
        evidence_level: "exact",
      },
    ],
  },
  "ui.reports.privacy_mirror": {
    payload_schema_version: 1,
    redaction: "ai_export_safe",
    local_only: true,
    read_only: true,
    advisory_only: true,
    scope: {
      workspace: "active",
      profile: "active",
      workspace_selected: true,
      profile_selected: true,
    },
    summary: {
      evidence_level: "unknown",
      privacy_score: {
        value: 53,
        base: 100,
        evidence_level: "derived",
        coverage_ratio: 0.5,
        factors: [
          { key: "wallet_linkage", linked: 1, total: 2, weight: 0.55, points: -28 },
          { key: "transaction_leaks", leaking: 2, total: 3, weight: 0.45, points: -19 },
        ],
      },
      linkage_score: 2,
      linkable_cluster_count: 2,
      adversary_view_count: 3,
      wallet_count: 2,
      transaction_tell_count: 3,
      utxo_count: 4,
      unknown_count: 2,
      finding_count: 3,
      worst_risk: {
        kind: "common_input",
        severity: "warning",
        title: "Common-input ownership heuristic links clusters",
        answer:
          "Worst local privacy risk: Common-input ownership heuristic links clusters. Common-input evidence created 2 new passive-observer cluster merge(s).",
        evidence_level: "exact",
        source: "linkage_graph",
        finding_id: "common_input_linkage",
      },
    },
    exposure_summary: {
      evidence_level: "unknown",
      linkage: {
        node_count: 4,
        linkage_score: 2,
        observer_entity_count: 2,
        transaction_tell_count: 3,
      },
      hygiene: {
        finding_count: 3,
        remote_backend_count: 1,
      },
    },
    adversary_cards: [
      {
        tier: "passive_chain_watcher",
        label: "Passive chain watcher",
        evidence_level: "derived",
        summary: {
          exposed_cluster_count: 2,
          wallet_count: 2,
          observer_entity_count: 2,
          unknown_coverage: {
            status: "partial_model_coverage",
            node_count: 1,
            wallet_count: 0,
            evidence_level: "unknown",
          },
        },
        model_assumptions: [
          {
            code: "bitcoin_graph_facts_only",
            statement:
              "Model starts from public Bitcoin transaction graph facts available in local inventory.",
            evidence_level: "derived",
          },
        ],
        clusters: [],
        unsupported_anchors: [],
      },
      {
        tier: "reviewed_kyc_source_funds_anchor_watcher",
        label: "Reviewed KYC/source-funds anchor watcher",
        evidence_level: "unknown",
        summary: {
          exposed_cluster_count: 1,
          wallet_count: 1,
          observer_entity_count: 1,
          unknown_coverage: {
            status: "partial_model_coverage",
            node_count: 2,
            wallet_count: 1,
            evidence_level: "unknown",
          },
        },
        model_assumptions: [
          {
            code: "reviewed_anchor_starting_knowledge",
            statement:
              "Model starts only from locally reviewed source-funds anchors.",
            evidence_level: "derived",
          },
        ],
        clusters: [],
        unsupported_anchors: [],
      },
      {
        tier: "known_counterparty_hypothetical",
        label: "Known-counterparty hypothetical",
        evidence_level: "derived",
        summary: {
          exposed_cluster_count: 1,
          wallet_count: 1,
          observer_entity_count: 0,
          unknown_coverage: {
            status: "partial_model_coverage",
            node_count: 2,
            wallet_count: 1,
            evidence_level: "unknown",
          },
        },
        model_assumptions: [
          {
            code: "counterparty_starting_knowledge",
            statement:
              "Model starts from locally annotated counterparty transactions.",
            evidence_level: "derived",
          },
        ],
        clusters: [],
        unsupported_anchors: [],
      },
    ],
    wallet_view: [
      {
        wallet_id: "wallet:multisig-vault",
        coin_count: 3,
        amount_msat: 18_400_000_000,
        linkage_edge_count: 2,
        cluster_count: 1,
        unknown_role_coin_count: 1,
        evidence_level: "unknown",
      },
      {
        wallet_id: "wallet:node",
        coin_count: 1,
        amount_msat: 1_200_000_000,
        linkage_edge_count: 0,
        cluster_count: 0,
        unknown_role_coin_count: 0,
        evidence_level: "exact",
      },
    ],
    transaction_view: [
      {
        txid: "tx-common-input-demo",
        tell_count: 2,
        tell_kinds: ["sender_common_input", "fee_fingerprint"],
        wallet_penalty_count: 2,
        evidence_level: "exact",
      },
      {
        txid: "tx-counterparty-demo",
        tell_count: 1,
        tell_kinds: ["op_return_output"],
        wallet_penalty_count: 0,
        evidence_level: "derived",
      },
    ],
    utxo_view: [
      {
        coin_id: "coin:1",
        wallet_id: "wallet:multisig-vault",
        amount_msat: 12_500_000_000,
        branch_role: "receive",
        source_proximity: "known_source_proximity",
        evidence_level: "exact",
      },
      {
        coin_id: "coin:2",
        wallet_id: "wallet:multisig-vault",
        amount_msat: 5_900_000_000,
        branch_role: "unknown",
        source_proximity: "unknown_provenance",
        evidence_level: "unknown",
      },
    ],
    timeline: [
      {
        id: "edge:1",
        kind: "common_input",
        category: "linkage",
        txid: "tx-common-input-demo",
        evidence_level: "exact",
        detail: "common_input",
        new_linkage: true,
      },
      {
        id: "tell:1",
        kind: "fee_fingerprint",
        category: "transaction_tell",
        txid: "tx-common-input-demo",
        evidence_level: "exact",
        detail: "decoded fee presence",
        new_linkage: false,
      },
    ],
    psbt_what_if_panel: {
      evidence_level: "derived",
      status: "available_via_reports_psbt_privacy",
      accepted_inputs: ["base64_psbt_text", "local_psbt_file"],
      raw_psbt_exposed_to_ai: false,
    },
    coverage: {
      evidence_level: "unknown",
      source_proximity_known_coin_count: 1,
      source_proximity_unknown_coin_count: 1,
      unknown_coverage_count: 1,
      degraded: true,
    },
    unknowns: [
      {
        source: "linkage_graph",
        code: "source_proximity_coverage_gaps",
        title:
          "Some owned coins do not have reviewed local source-funds proximity.",
        evidence_level: "unknown",
      },
    ],
    evidence_drilldowns: [
      {
        section: "findings",
        id: "common_input_linkage",
        kind: "common_input",
        evidence_level: "exact",
        evidence: { new_cluster_merges: 2 },
      },
      {
        section: "source_proximity",
        id: "coin:2",
        kind: "unknown_provenance",
        evidence_level: "unknown",
        evidence: { reason: "no_reviewed_source_path" },
      },
    ],
    limitations: [
      {
        code: "local_only_no_probe",
        message:
          "No network request was made; linkage uses local Bitcoin UTXO facts only.",
        evidence_level: "exact",
      },
    ],
  },
  "ui.reports.psbt_privacy": {
    payload_schema_version: 1,
    redaction: "ai_export_safe",
    local_only: true,
    read_only: true,
    advisory_only: true,
    signing_supported: false,
    broadcast_supported: false,
    psbt_exposure: "reduced_findings_only",
    summary: {
      evidence_level: "exact",
      decode_status: "decoded",
      input_count: 2,
      output_count: 2,
      known_owned_input_count: 2,
      unknown_input_count: 0,
      owned_input_cluster_count: 2,
      cluster_merge_delta: 1,
      receive_reuse_output_count: 0,
      receive_reuse_cluster_delta: 0,
      blast_radius_score: 1,
      transaction_tell_count: 2,
      adversary_delta_count: 3,
      finding_count: 1,
      limitation_count: 2,
    },
    findings: [
      {
        id: "psbt_cluster_merge",
        kind: "cluster_merge",
        severity: "warning",
        title: "PSBT merges local ownership clusters",
        detail:
          "The decoded transaction would create 1 new common-input cluster merge among locally known inputs.",
        evidence_level: "exact",
      },
    ],
    adversary_deltas: [
      {
        tier: "passive_chain_watcher",
        cluster_merge_delta: 1,
        newly_exposed_component_count: 2,
        evidence_level: "derived",
      },
    ],
    what_if: [
      {
        scenario: "fresh_receive_output",
        cluster_merge_delta: 0,
        support_status: "supported_by_local_ground_truth",
        evidence_level: "derived",
      },
      {
        scenario: "hypothetical_input_consolidation",
        cluster_merge_delta: 1,
        support_status: "supported_by_local_ground_truth",
        evidence_level: "exact",
      },
    ],
    unknowns: {
      evidence_level: "exact",
      input_count: 0,
      output_without_local_match_count: 2,
      coverage_complete: true,
    },
  },
  "ui.reports.export_pdf": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-report-mock.pdf",
    filename: "kassiber-report-mock.pdf",
    format: "pdf",
    scope: "report",
    pages: 4,
    bytes: 24576,
    title: "Kassiber Report - Mock",
  },
  "ui.reports.export_summary_pdf": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-summary-report-mock.pdf",
    filename: "kassiber-summary-report-mock.pdf",
    format: "pdf",
    scope: "summary_report",
    pages: 3,
    bytes: 28672,
    title: "Kassiber Summary Report - Mock",
    snapshot: true,
    wallets: [
      { id: "wallet:multisig-vault", label: "Multisig Vault" },
      { id: "wallet:node", label: "Home Node" },
    ],
    timeframe: {
      start: "2026-01-01T00:00:00Z",
      end: "2026-12-31T23:59:59Z",
      label: "2026-01-01 to 2026-12-31",
    },
  },
  "ui.reports.export_csv": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-report-mock.csv",
    filename: "kassiber-report-mock.csv",
    format: "csv",
    scope: "report",
    rows: 24,
    bytes: 12288,
    sections: ["Overview", "Wallets", "Asset Flow", "Transactions"],
  },
  "ui.reports.export_xlsx": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-report-mock.xlsx",
    filename: "kassiber-report-mock.xlsx",
    format: "xlsx",
    scope: "report",
    rows: 24,
    sheets: ["Overview", "Wallets", "Asset Flow", "Transactions"],
    bytes: 20480,
  },
  "ui.reports.export_capital_gains_csv": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-capital-gains-mock.csv",
    filename: "kassiber-capital-gains-mock.csv",
    format: "csv",
    scope: "capital_gains",
    rows: MOCK_CAPITAL_GAINS.lots.length,
    bytes: 8192,
  },
  "ui.reports.export_austrian_e1kv_pdf": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-austrian-e1kv-2025-mock.pdf",
    filename: "kassiber-austrian-e1kv-2025-mock.pdf",
    format: "pdf",
    scope: "austrian_e1kv",
    tax_year: 2025,
    pages: 4,
    bytes: 32768,
  },
  "ui.reports.export_austrian_e1kv_xlsx": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-austrian-e1kv-2025-mock.xlsx",
    filename: "kassiber-austrian-e1kv-2025-mock.xlsx",
    format: "xlsx",
    scope: "austrian_e1kv",
    tax_year: 2025,
    rows: MOCK_CAPITAL_GAINS.lots.length,
    summary_rows: 3,
    bytes: 24576,
  },
  "ui.reports.export_austrian_e1kv_csv": {
    dir: "~/.kassiber/projects/mock/exports/reports/kassiber-austrian-e1kv-2025-csv-mock",
    filename: "kassiber-austrian-e1kv-2025-csv-mock",
    format: "csv",
    scope: "austrian_e1kv",
    tax_year: 2025,
    rows: MOCK_CAPITAL_GAINS.lots.length,
    summary_rows: 3,
    files: [
      {
        sheet: "Übersicht",
        file: "~/.kassiber/projects/mock/exports/reports/kassiber-austrian-e1kv-2025-csv-mock/00_uebersicht.csv",
        rows: 3,
        bytes: 2048,
      },
    ],
  },
  "ui.source_funds.preview": {
    workspace: "My Books",
    profile: "local books",
    purpose: {
      type: "planned_exchange_sale",
      label: "Planned exchange sale",
      anchor_role: "funds_history_anchor",
      planned_destination: "Mock Exchange",
      planned_note: "Pre-disclosure before expected EUR proceeds arrive.",
      fiat_purchase_note: "If the bitcoin was bought on an exchange, fiat-source evidence for that original purchase is separate supporting evidence.",
    },
    target: {
      transaction_id: "tx19",
      label: "Vault migration",
      external_id: "mock-target-deposit",
      wallet: "Multisig Vault",
      occurred_at: "2024-11-05T10:12:00Z",
      direction: "inbound",
      asset: "BTC",
      required_amount: 0.15,
      required_amount_msat: 15_000_000_000,
      fiat_value: 10713.03,
    },
    reveal_mode: "standard",
    graph: {
      nodes: [
        { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC" },
        { id: "tx1", node_type: "transaction", transaction_id: "tx1", external_id: SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID, label: "withdraw-1", wallet: "Exchange", asset: "BTC", direction: "outbound", fee: 0.0001, fee_msat: 10_000_000, data_provenance: "platform_export" },
        { id: "tx2", node_type: "transaction", transaction_id: "tx2", external_id: SOURCE_FUNDS_FIXTURE_TARGET_TXID, label: "target deposit", wallet: "Multisig Vault", asset: "BTC", direction: "inbound", fee: 0, fee_msat: 0, data_provenance: "chain_sync" },
      ],
      edges: [
        { id: "link:1", from: "source:1", to: "tx1", link_type: "manual_source", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
        { id: "link:2", from: "tx1", to: "tx2", link_type: "self_transfer", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
      ],
    },
    allocations: {
      target_amount: 0.15,
      target_amount_msat: 15_000_000_000,
      asset: "BTC",
      reviewed_edge_count: 2,
    },
    source_mix: [{ source_type: "fiat_purchase", amount: 0.15, amount_msat: 15_000_000_000, percent_of_target: 100, count: 1 }],
    report_context: {
      tax_country: "at",
      fiat_currency: "EUR",
      jurisdiction_label: "Austria",
      template_key: "at_eur_basic",
      report_title: "Mittelherkunftsnachweis / Source of Funds Report",
      report_subtitle: "Reviewed local evidence disclosure for an Austrian/EUR source-of-funds workflow.",
    },
    overview: {
      target_label: "Vault migration",
      target_asset: "BTC",
      target_amount: 0.15,
      target_fiat_value: 10713.03,
      target_fiat_currency: "EUR",
      target_date: "2024-11-05T10:12:00Z",
      target_wallet: "Multisig Vault",
      time_range: { start: "2024-10-31T09:00:00Z", end: "2024-11-05T10:12:00Z" },
      transaction_count: 2,
      link_count: 2,
      root_source_count: 1,
      source_category_count: 1,
      data_source_count: 3,
      blocker_count: 0,
      warning_count: 1,
    },
    narrative: {
      generated_by: "local_rule_summary",
      paragraphs: [
        "This report traces 0.15000000 BTC for Vault migration through 2 reviewed links across 2 transactions.",
        "The reviewed source mix is fiat purchase: 0.15000000 BTC, 100.0% of target. The path spans 2024-10-31T09:00:00Z to 2024-11-05T10:12:00Z and uses 2 local data sources.",
        "Export is currently clear under the current review gates.",
      ],
    },
    data_sources: [
      {
        label: "Exchange",
        kind: "wallet",
        provenance: "platform_export",
        transaction_count: 1,
        source_count: 0,
        assets: ["BTC"],
        first_seen: "2024-10-31T09:05:00Z",
        last_seen: "2024-10-31T09:05:00Z",
      },
      {
        label: "Multisig Vault",
        kind: "wallet",
        provenance: "chain_sync",
        transaction_count: 1,
        source_count: 0,
        assets: ["BTC"],
        first_seen: "2024-11-05T10:12:00Z",
        last_seen: "2024-11-05T10:12:00Z",
      },
      {
        label: "Reviewed exchange purchase",
        kind: "fiat_purchase",
        provenance: "attested_source",
        transaction_count: 0,
        source_count: 1,
        assets: ["BTC"],
        first_seen: "2024-10-31T09:00:00Z",
        last_seen: "2024-10-31T09:00:00Z",
      },
    ],
    flow_levels: [
      {
        level: 1,
        role: "target",
        transaction_count: 1,
        source_count: 0,
        assets: ["BTC"],
        fiat_currency: "EUR",
        fiat_value_total: 10713.03,
        nodes: [
          { id: "tx2", node_type: "transaction", label: "target deposit", wallet: "Multisig Vault", asset: "BTC", required_amount: 0.15, occurred_at: "2024-11-05T10:12:00Z", external_id: "mock-target-deposit", direction: "inbound", fee: 0, fee_msat: 0, fiat_currency: "EUR", fiat_value: 10713.03, data_provenance: "chain_sync" },
        ],
      },
      {
        level: 2,
        role: "upstream",
        transaction_count: 1,
        source_count: 0,
        assets: ["BTC"],
        fiat_currency: "EUR",
        fiat_value_total: 10715.5,
        nodes: [
          { id: "tx1", node_type: "transaction", label: "withdraw-1", wallet: "Exchange", asset: "BTC", required_amount: 0.15, occurred_at: "2024-10-31T09:05:00Z", external_id: SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID, direction: "outbound", fee: 0.0001, fee_msat: 10_000_000, fiat_currency: "EUR", fiat_value: 10715.5, data_provenance: "platform_export" },
        ],
      },
      {
        level: 3,
        role: "upstream",
        transaction_count: 0,
        source_count: 1,
        assets: ["BTC"],
        fiat_currency: "EUR",
        fiat_value_total: 10650.0,
        nodes: [
          { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC", required_amount: 0.15, acquired_at: "2024-10-31T09:00:00Z", direction: "", fiat_currency: "EUR", fiat_value: 10650.0, data_provenance: "" },
        ],
      },
    ],
    data_provenance_summary: [
      { provenance: "chain_sync", label: "Blockchain (watch-only sync)", count: 1, percent: 50 },
      { provenance: "platform_export", label: "Platform export / API", count: 1, percent: 50 },
    ],
    simplified_flow: {
      note: "Simplified flow follows reviewed local links. Wallet transfers and consolidations are shown as reviewed hops; CoinJoin/PayJoin traversal is deferred and shown only as a privacy boundary.",
      deferred_privacy_hops: [],
      levels: [
        {
          level: 1,
          role: "source",
          distance_to_target: 2,
          nodes: [
            {
              id: "source:1",
              node_type: "source",
              kind: "fiat_purchase",
              label: "Reviewed exchange purchase",
              asset: "BTC",
              amount: 0.15,
              occurred_at: "2024-10-31T09:00:00Z",
            },
          ],
        },
        {
          level: 2,
          role: "upstream",
          distance_to_target: 1,
          nodes: [
            {
              id: "tx1",
              node_type: "transaction",
              transaction_id: "tx1",
              kind: "outbound",
              label: "withdraw-1",
              wallet: "Exchange",
              asset: "BTC",
              amount: 0.15,
              occurred_at: "2024-10-31T09:05:00Z",
            },
          ],
        },
        {
          level: 3,
          role: "target",
          distance_to_target: 0,
          nodes: [
            {
              id: "tx2",
              node_type: "transaction",
              transaction_id: "tx19",
              kind: "inbound",
              label: "target deposit",
              wallet: "Multisig Vault",
              asset: "BTC",
              amount: 0.15,
              occurred_at: "2024-11-05T10:12:00Z",
            },
          ],
        },
      ],
      edges: [
        {
          id: "link:1",
          from: "source:1",
          to: "tx1",
          link_type: "manual_source",
          asset: "BTC",
          amount: 0.15,
          percent_of_target: 100,
          deferred_privacy_hop: false,
        },
        {
          id: "link:2",
          from: "tx1",
          to: "tx2",
          link_type: "self_transfer",
          asset: "BTC",
          amount: 0.15,
          percent_of_target: 100,
          deferred_privacy_hop: false,
        },
      ],
    },
    gaps: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    findings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    explain_gates: { exportable: true, blockers: [], warnings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }] },
    disclosure_preview: {
      txids: [
        SOURCE_FUNDS_FIXTURE_TARGET_TXID,
        SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
      ],
      explorer_links: SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS,
      attachments: [{ id: "att:1", label: "Exchange statement", attachment_type: "file" }],
      wallets_named: ["Exchange", "Multisig Vault"],
      ownership_note:
        "Sharing this report demonstrates to the recipient that the wallets named above are under common ownership or control, and links their disclosed transactions to your identity.",
      privacy_note: "Txids disclose on-chain neighbors to the recipient. Chain observations are context, not proof of ownership.",
      excluded: ["descriptors", "xpubs", "wallet files", "seeds", "backend tokens", "unrelated wallet history"],
    },
    diagrams: {
      flow_svg:
        '<svg viewBox="0 0 500 70" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="20" width="120" height="34" rx="4" fill="#ecfdf5" stroke="#16a34a"/><text x="8" y="33" font-family="Helvetica,Arial,sans-serif" font-size="8" font-weight="700" fill="#222222">Fiat purchase</text><text x="8" y="46" font-family="Courier,monospace" font-size="7" fill="#222222">0.30000000 BTC</text><line x1="124" y1="37" x2="184" y2="37" stroke="#666666" stroke-width="2.5"/><polyline points="184,37 179,34 179,40" fill="#666666"/><text x="153" y="32" font-family="Helvetica,Arial,sans-serif" font-size="6" font-weight="700" fill="#666666" text-anchor="middle">100.0%</text><rect x="190" y="20" width="120" height="34" rx="4" fill="#ffffff" stroke="#d9d9d9"/><text x="196" y="33" font-family="Helvetica,Arial,sans-serif" font-size="8" font-weight="700" fill="#222222">Cold storage</text><text x="196" y="46" font-family="Courier,monospace" font-size="7" fill="#222222">0.30000000 BTC</text><line x1="312" y1="37" x2="372" y2="37" stroke="#666666" stroke-width="2.5"/><polyline points="372,37 367,34 367,40" fill="#666666"/><rect x="378" y="20" width="120" height="34" rx="4" fill="#ffffff" stroke="#e3000f" stroke-width="1.2"/><text x="384" y="33" font-family="Helvetica,Arial,sans-serif" font-size="8" font-weight="700" fill="#222222">Broker deposit</text><text x="384" y="46" font-family="Courier,monospace" font-size="7" fill="#222222">0.30000000 BTC</text></svg>',
      source_mix_ring_svg:
        '<svg viewBox="0 0 240 100" xmlns="http://www.w3.org/2000/svg"><circle cx="49" cy="50" r="45" fill="#2563eb"/><circle cx="49" cy="50" r="26" fill="#ffffff"/><text x="49" y="50" font-family="Helvetica,Arial,sans-serif" font-size="9" font-weight="700" fill="#222222" text-anchor="middle">0.30000000</text><text x="49" y="60" font-family="Helvetica,Arial,sans-serif" font-size="6" fill="#666666" text-anchor="middle">BTC explained</text><rect x="104" y="46" width="7" height="7" fill="#2563eb"/><text x="115" y="52" font-family="Helvetica,Arial,sans-serif" font-size="6.4" fill="#222222">fiat purchase  100.0%</text></svg>',
      data_source_ring_svg:
        '<svg viewBox="0 0 240 100" xmlns="http://www.w3.org/2000/svg"><circle cx="49" cy="50" r="45" fill="#0ea5e9"/><circle cx="49" cy="50" r="26" fill="#ffffff"/><text x="49" y="50" font-family="Helvetica,Arial,sans-serif" font-size="9" font-weight="700" fill="#222222" text-anchor="middle">2</text><text x="49" y="60" font-family="Helvetica,Arial,sans-serif" font-size="6" fill="#666666" text-anchor="middle">transactions</text><rect x="104" y="40" width="7" height="7" fill="#0891b2"/><text x="115" y="46" font-family="Helvetica,Arial,sans-serif" font-size="6.4" fill="#222222">Blockchain (watch-only sync)  50.0%</text><rect x="104" y="52" width="7" height="7" fill="#2563eb"/><text x="115" y="58" font-family="Helvetica,Arial,sans-serif" font-size="6.4" fill="#222222">Platform export / API  50.0%</text></svg>',
    },
  },
  "ui.source_funds.cases.save": {
    workspace: "My Books",
    profile: "local books",
    purpose: {
      type: "planned_exchange_sale",
      label: "Planned exchange sale",
      anchor_role: "funds_history_anchor",
      planned_destination: "Mock Exchange",
      planned_note: "Pre-disclosure before expected EUR proceeds arrive.",
      fiat_purchase_note: "If the bitcoin was bought on an exchange, fiat-source evidence for that original purchase is separate supporting evidence.",
    },
    target: {
      transaction_id: "tx19",
      label: "Vault migration",
      external_id: "mock-target-deposit",
      wallet: "Multisig Vault",
      occurred_at: "2024-11-05T10:12:00Z",
      direction: "inbound",
      asset: "BTC",
      required_amount: 0.15,
      required_amount_msat: 15_000_000_000,
      fiat_value: 10713.03,
    },
    reveal_mode: "standard",
    case: {
      id: "case:source-funds-demo",
      snapshot_id: "snapshot:source-funds-demo",
      status: "exportable",
      snapshot_hash: "mock-source-funds-snapshot",
      created_at: "2024-11-05T10:30:00Z",
    },
    graph: {
      nodes: [
        { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC" },
        { id: "tx1", node_type: "transaction", transaction_id: "tx1", external_id: SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID, label: "withdraw-1", wallet: "Exchange", asset: "BTC", direction: "outbound", fee: 0.0001, fee_msat: 10_000_000, data_provenance: "platform_export" },
        { id: "tx2", node_type: "transaction", transaction_id: "tx2", external_id: SOURCE_FUNDS_FIXTURE_TARGET_TXID, label: "target deposit", wallet: "Multisig Vault", asset: "BTC", direction: "inbound", fee: 0, fee_msat: 0, data_provenance: "chain_sync" },
      ],
      edges: [
        { id: "link:1", from: "source:1", to: "tx1", link_type: "manual_source", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
        { id: "link:2", from: "tx1", to: "tx2", link_type: "self_transfer", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
      ],
    },
    allocations: {
      target_amount: 0.15,
      target_amount_msat: 15_000_000_000,
      asset: "BTC",
      reviewed_edge_count: 2,
    },
    source_mix: [{ source_type: "fiat_purchase", amount: 0.15, amount_msat: 15_000_000_000, count: 1 }],
    gaps: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    findings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    explain_gates: { exportable: true, blockers: [], warnings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }] },
    disclosure_preview: {
      txids: [
        SOURCE_FUNDS_FIXTURE_TARGET_TXID,
        SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
      ],
      explorer_links: SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS,
      attachments: [{ id: "att:1", label: "Exchange statement", attachment_type: "file" }],
      wallets_named: ["Exchange", "Multisig Vault"],
      ownership_note:
        "Sharing this report demonstrates to the recipient that the wallets named above are under common ownership or control, and links their disclosed transactions to your identity.",
      privacy_note: "Txids disclose on-chain neighbors to the recipient. Chain observations are context, not proof of ownership.",
      excluded: ["descriptors", "xpubs", "wallet files", "seeds", "backend tokens", "unrelated wallet history"],
    },
  },
  "ui.source_funds.cases.list": {
    cases: [
      {
        id: "case:source-funds-demo",
        label: "Demo disclosure",
        target_transaction_id: "tx19",
        target_external_id: "mock-target-deposit",
        target_amount: 0.15,
        target_amount_msat: 15_000_000_000,
        asset: "BTC",
        reveal_mode: "standard",
        status: "exportable",
        snapshot_hash: "mock-source-funds-snapshot",
        recipient_id: null,
        recipient_label: "",
        recipient_kind: "",
        recipient_reveal_mode: "",
        created_at: "2024-11-05T10:30:00Z",
        updated_at: "2024-11-05T10:30:00Z",
      },
    ],
  },
  "ui.source_funds.sources.list": {
    sources: [
      {
        id: "source:1",
        source_type: "fiat_purchase",
        label: "Reviewed exchange purchase",
        asset: "BTC",
        amount: 0.15,
        amount_msat: 15_000_000_000,
        description: "Exchange statement and purchase receipt reviewed.",
        attachments: [
          { id: "att:1", label: "Exchange statement", attachment_type: "file" },
        ],
      },
    ],
  },
  "ui.source_funds.sources.create": {
    id: "source:new",
    source_type: "fiat_purchase",
    label: "New reviewed source",
    asset: "BTC",
    amount: 0.15,
    amount_msat: 15_000_000_000,
    description: "",
    attachments: [],
  },
  "ui.source_funds.sources.attach": {
    id: "source:1",
    source_type: "fiat_purchase",
    label: "Reviewed exchange purchase",
    asset: "BTC",
    amount: 0.15,
    amount_msat: 15_000_000_000,
    attachments: [
      { id: "att:1", label: "Exchange statement", attachment_type: "file" },
    ],
  },
  "ui.source_funds.links.list": {
    links: [
      {
        id: "link:1",
        from_source_id: "source:1",
        from_transaction_id: null,
        to_transaction_id: "tx19",
        link_type: "manual_source",
        state: "reviewed",
        confidence: "strong",
        method: "manual",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: null,
        allocation_policy: "explicit",
        explanation: "Reviewed exchange source.",
        attachments: [
          { id: "att:1", label: "Exchange statement", attachment_type: "file" },
        ],
      },
      {
        id: "link:2",
        from_source_id: null,
        from_transaction_id: "tx12",
        to_transaction_id: "tx19",
        link_type: "self_transfer",
        state: "suggested",
        confidence: "weak",
        method: "tight_time_amount_match",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: 0.15001,
        allocation_policy: "heuristic",
        explanation: "Same-day amount match across owned wallets.",
        attachments: [],
      },
    ],
  },
  "ui.source_funds.links.create": {
    id: "link:new",
    from_source_id: "source:new",
    from_transaction_id: null,
    to_transaction_id: "tx19",
    link_type: "manual_source",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: null,
    allocation_policy: "explicit",
    explanation: "",
    attachments: [],
  },
  "ui.source_funds.links.review": {
    id: "link:2",
    from_source_id: null,
    from_transaction_id: "tx12",
    to_transaction_id: "tx19",
    link_type: "self_transfer",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: 0.15001,
    allocation_policy: "explicit",
    explanation: "Reviewed self-transfer.",
    attachments: [],
  },
  "ui.source_funds.links.bulk_review": {
    reviewed: 1,
    skipped: 1,
    target_transaction_id: "tx19",
    links: [
      {
        id: "link:3",
        from_source_id: null,
        from_transaction_id: "tx8",
        to_transaction_id: "tx12",
        link_type: "self_transfer",
        state: "reviewed",
        confidence: "exact",
        method: "same_external_id",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: 0.1501,
        allocation_policy: "explicit",
        explanation: "Same external transaction id.",
        attachments: [],
      },
    ],
    policy:
      "Bulk review only accepts exact/strong deterministic suggestions. Weak hints remain manual.",
  },
  "ui.source_funds.links.attach": {
    id: "link:2",
    from_source_id: null,
    from_transaction_id: "tx12",
    to_transaction_id: "tx19",
    link_type: "self_transfer",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: 0.15001,
    allocation_policy: "explicit",
    explanation: "Reviewed self-transfer.",
    attachments: [
      { id: "att:1", label: "Exchange statement", attachment_type: "file" },
    ],
  },
  "ui.source_funds.suggest": {
    inserted: 1,
    target_transaction_id: "tx19",
    links: [],
    privacy_warning: "No chain backend was queried.",
  },
  "ui.source_funds.assemble": {
    target_transaction_id: "tx19",
    passes: 2,
    inserted: 3,
    auto_reviewed: 2,
    awaiting_manual_review: 1,
    methods: { payment_hash: 1, utxo_spend: 1 },
    policy:
      "Assembly derives exact edges from synced transaction inputs/outputs and Lightning payment hashes, plus deterministic platform-id and reviewed-pair matches. Weak hints, chain observations, privacy boundaries, and root-source evidence remain manual review items.",
  },
  "ui.source_funds.evidence.list": {
    attachments: [
      {
        id: "att:1",
        attachment_type: "file",
        label: "Exchange statement",
        external_id: "mock-target-deposit",
        wallet: "Multisig Vault",
        occurred_at: "2024-11-05T10:12:00Z",
      },
    ],
  },
  "ui.source_funds.export_pdf": {
    file: "~/.kassiber/projects/mock/exports/reports/kassiber-source-funds-mock.pdf",
    filename: "kassiber-source-funds-mock.pdf",
    format: "pdf",
    scope: "source_funds",
    pages: 3,
    bytes: 18432,
    exportable: true,
  },
  "ui.source_funds.coverage": {
    scope: "historical_inbound",
    scope_note:
      "Counts every inbound transaction. Not a current-holdings view: self-transfers between owned wallets are counted at each hop, and already-spent inflows still appear in the totals.",
    by_wallet: [
      {
        wallet_id: "wallet:multisig-vault",
        wallet_label: "Multisig Vault",
        asset: "BTC",
        buckets: {
          fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
          attested: { amount_msat: 0, amount: 0, tx_count: 0 },
          in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
          untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
          not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
        },
        total_inbound_msat: 15_000_000_000,
        total_inbound: 0.15,
      },
    ],
    by_asset: [
      {
        asset: "BTC",
        buckets: {
          fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
          attested: { amount_msat: 0, amount: 0, tx_count: 0 },
          in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
          untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
          not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
        },
        total_inbound_msat: 15_000_000_000,
        total_inbound: 0.15,
      },
    ],
    totals: {
      buckets: {
        fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
        attested: { amount_msat: 0, amount: 0, tx_count: 0 },
        in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
        untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
        not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
      },
      tx_count: 1,
      amount_msat: 15_000_000_000,
      amount: 0.15,
    },
    limits: { max_depth: 8, max_transactions: 5000 },
    truncation: {
      truncated: false,
      inbound_total_count: 1,
      inbound_total_msat: 15_000_000_000,
      inbound_total: 0.15,
      not_classified_count: 0,
      not_classified_msat: 0,
      not_classified: 0,
    },
  },
  "ui.source_funds.recipients.list": {
    recipients: [
      {
        id: "recipient:bank-austria",
        label: "Bank Austria",
        kind: "bank",
        default_reveal_mode: "minimal",
        notes: "Account manager prefers minimal disclosure.",
        active: true,
        created_at: "2024-09-01T08:00:00Z",
        updated_at: "2024-09-01T08:00:00Z",
      },
      {
        id: "recipient:mock-exchange",
        label: "Mock Exchange",
        kind: "exchange",
        default_reveal_mode: "standard",
        active: true,
        created_at: "2024-09-01T08:00:00Z",
        updated_at: "2024-09-01T08:00:00Z",
      },
      {
        id: "recipient:retired-broker",
        label: "Retired Broker",
        kind: "exchange",
        default_reveal_mode: "standard",
        active: false,
        created_at: "2024-08-01T08:00:00Z",
        updated_at: "2024-09-15T08:00:00Z",
      },
    ],
  },
  "ui.journals.snapshot": {
    status: {
      workspace: "My Books",
      profile: "local books",
      transactionCount: MOCK_OVERVIEW.txs.length,
      journalEntryCount: 42,
      needsJournals: false,
      quarantines: 0,
      lastProcessedAt: "2026-04-26T12:00:00Z",
    },
    entryTypes: [
      { type: "acquisition", count: 28, gainLossEur: 0 },
      { type: "disposal", count: 8, gainLossEur: 1240.5 },
      { type: "transfer_in", count: 3, gainLossEur: 0 },
      { type: "transfer_out", count: 3, gainLossEur: 0 },
    ],
    recent: [],
  },
  "ui.journals.events.list": {
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 4,
      reportableCount: 3,
      needsJournals: false,
      lastProcessedAt: "2026-04-26T12:00:00Z",
      freshnessStatus: "current",
      freshnessReason: "journals match the active transaction count and input version",
      entryTypes: [
        { type: "acquisition", count: 1, gainLossEur: 0 },
        { type: "disposal", count: 1, gainLossEur: 1240.5 },
        { type: "income", count: 1, gainLossEur: 0 },
        { type: "fee", count: 1, gainLossEur: -13.01 },
      ],
      limit: 100,
    },
    events: [
      {
        id: "je-001",
        transactionId: "tx-001",
        transactionExternalId: "seed-inbound-1",
        transactionDirection: "inbound",
        occurredAt: "2026-04-18T12:10:00Z",
        createdAt: "2026-04-18T12:10:01Z",
        entryType: "income",
        wallet: "Cold Storage",
        account: "TREASURY",
        accountLabel: "Cold Storage",
        asset: "BTC",
        quantity: 0.0245,
        quantityMsat: 2_450_000_000,
        fiatValueEur: 1749.79,
        unitCostEur: 71420,
        costBasisEur: null,
        proceedsEur: 1749.79,
        gainLossEur: 0,
        pricingSourceKind: "manual",
        pricingQuality: "exact",
        description: "Revenue receipt",
        atCategory: null,
        atKennzahl: null,
      },
      {
        id: "je-002",
        transactionId: "tx-002",
        transactionExternalId: "vault-sale-1",
        transactionDirection: "outbound",
        occurredAt: "2026-04-17T09:30:00Z",
        createdAt: "2026-04-17T09:30:01Z",
        entryType: "disposal",
        wallet: "Multisig Vault",
        account: "TREASURY",
        accountLabel: "Multisig Vault",
        asset: "BTC",
        quantity: -0.5,
        quantityMsat: -50_000_000_000,
        fiatValueEur: 35600,
        unitCostEur: 71200,
        costBasisEur: 23000,
        proceedsEur: 35600,
        gainLossEur: 12600,
        pricingSourceKind: "rates_cache",
        pricingQuality: "exact",
        description: "Treasury rebalance",
        atCategory: "capital_gain_current",
        atKennzahl: 984,
      },
      {
        id: "je-003",
        transactionId: "tx-003",
        transactionExternalId: "node-fee-1",
        transactionDirection: "outbound",
        occurredAt: "2026-04-16T16:05:00Z",
        createdAt: "2026-04-16T16:05:01Z",
        entryType: "fee",
        wallet: "Home Node",
        account: "OPS",
        accountLabel: "Operations",
        asset: "BTC",
        quantity: -0.0001821,
        quantityMsat: -18_210_000,
        fiatValueEur: 13.01,
        unitCostEur: 71440,
        costBasisEur: 13.01,
        proceedsEur: 0,
        gainLossEur: -13.01,
        pricingSourceKind: "rates_cache",
        pricingQuality: "exact",
        description: "Channel-open fee",
        atCategory: null,
        atKennzahl: null,
      },
    ],
  },
  "ui.journals.quarantine": {
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 2,
      by_reason: [
        { reason: "missing_price", count: 1 },
        { reason: "insufficient_lots", count: 1 },
      ],
      limit: 100,
    },
    items: [
      {
        transaction_id: "tx-missing-price",
        external_id: "missing-price-1",
        occurred_at: "2026-04-15T08:00:00Z",
        confirmed_at: null,
        wallet: "Cold Storage",
        direction: "inbound",
        asset: "BTC",
        amount: 0.0041,
        amount_msat: 410_000_000,
        fee: 0,
        fee_msat: 0,
        reason: "missing_price",
        detail: { field: "fiat_rate" },
        created_at: "2026-04-26T12:00:00Z",
      },
      {
        transaction_id: "tx-missing-basis",
        external_id: "basis-review-1",
        occurred_at: "2026-04-12T14:20:00Z",
        confirmed_at: null,
        wallet: "Multisig Vault",
        direction: "outbound",
        asset: "BTC",
        amount: 0.25,
        amount_msat: 25_000_000_000,
        fee: 0.00001,
        fee_msat: 1_000_000,
        reason: "insufficient_lots",
        detail: { available: "0 BTC", needed: "0.25 BTC" },
        created_at: "2026-04-26T12:00:00Z",
      },
    ],
  },
  "ui.journals.process": {
    profile: "local books",
    entries_created: 42,
    quarantined: 0,
    transfers_detected: 3,
    cross_asset_pairs: 0,
    auto_priced: 0,
    processed_transactions: MOCK_OVERVIEW.txs.length,
    processed_at: "2026-04-26T12:00:00Z",
  },
  "ui.rates.coverage": {
    workspace: "My Books",
    profile: "local books",
    summary: {
      active_transactions: 12,
      priced_transactions: 11,
      missing_price_transactions: 1,
      cache_coverable_missing: 1,
      cache_uncovered_missing: 0,
    },
    items: [
      {
        id: "mock-missing-price",
        externalId: "mock-txid",
        date: "2026-04-22T10:20:00Z",
        wallet: "Multisig Vault",
        direction: "inbound",
        asset: "BTC",
        amountSat: 50_000,
        amountMsat: 50_000_000,
        fiatCurrency: "EUR",
        cachePair: "BTC-EUR",
        cacheHasRate: true,
        cacheRateAt: "2026-04-22T00:00:00Z",
      },
    ],
    filters: { limit: 25 },
  },
  "ui.report.blockers": {
    ready: false,
    blockers: [
      {
        id: "missing_prices",
        severity: "review",
        title: "Missing transaction prices",
        detail: "1 transaction(s) are missing fiat price fields.",
        daemon_kind: "ui.rates.coverage",
      },
    ],
    health: {
      counts: {
        wallets: 2,
        transactions: 12,
        active_transactions: 12,
        journal_entries: 42,
        quarantines: 0,
        rate_pairs: 1,
      },
      journals: {
        status: "current",
        needs_processing: false,
        quarantine_count: 0,
        last_processed_at: "2026-04-26T12:00:00Z",
      },
      reports: { ready: true, hints: ["Reports are ready."] },
    },
    rates_coverage: {
      summary: {
        active_transactions: 12,
        missing_price_transactions: 1,
        cache_coverable_missing: 1,
      },
      items: [],
    },
  },
  "ui.audit.changes_since_last_answer": {
    changed: false,
    baseline: { since: "2026-04-26T12:00:00Z" },
    workspace: "My Books",
    profile: "local books",
    counts_since: {
      transactions: 0,
      journal_entries: 0,
      journal_quarantines: 0,
      wallets: 0,
      rates: 0,
    },
    latest: { journals_processed_at: "2026-04-26T12:00:00Z" },
    current: {
      generated_at: "2026-04-26T12:01:00Z",
      active_transactions: 12,
      journals_processed_at: "2026-04-26T12:00:00Z",
      quarantines: 0,
    },
  },
  "ui.maintenance.settings": {
    workspace: "My Books",
    profile: { id: "mock-profile", label: "local books" },
    settings: {
      background_enabled: false,
      report_read_sync: false,
      source_classes: {
        onchain_wallet: false,
        btcpay_wallet: false,
        btcpay_provenance: false,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: false,
      require_coarse_review: false,
      coarse_priced_count: 3,
      setting_key: "ai.auto_sync_before_report_reads.profile.mock-profile",
    },
  },
  "ui.maintenance.configure": {
    workspace: "My Books",
    profile: { id: "mock-profile", label: "local books" },
    settings: {
      background_enabled: true,
      report_read_sync: true,
      source_classes: {
        onchain_wallet: true,
        btcpay_wallet: true,
        btcpay_provenance: true,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: true,
      setting_key: "ai.auto_sync_before_report_reads.profile.mock-profile",
    },
  },
  "ui.maintenance.run": {
    ready: true,
    sync_mode: "if_enabled",
    maintenance: {
      journals: {
        kind: "ui.journals.process",
        schema_version: 1,
        data: {
          processed_transactions: MOCK_OVERVIEW.txs.length,
          quarantined: 0,
          processed_at: "2026-04-26T12:00:00Z",
        },
      },
    },
    blockers: [],
    health: {
      counts: { active_transactions: 12, quarantines: 0 },
      journals: { status: "current", needs_processing: false },
      reports: { ready: true },
    },
    settings: {
      background_enabled: false,
      report_read_sync: false,
      source_classes: {
        onchain_wallet: false,
        btcpay_wallet: false,
        btcpay_provenance: false,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: false,
    },
  },
  "ai.providers.list": {
    providers: [
      {
        name: "ollama",
        display_name: "Ollama",
        base_url: "http://localhost:11434/v1",
        kind: "local",
        default_model: "qwen3.6:35b",
        notes: "Local Ollama (mock).",
        acknowledged_at: "2026-04-27T08:00:00Z",
        created_at: "2026-04-27T08:00:00Z",
        updated_at: "2026-04-27T08:00:00Z",
        has_api_key: false,
        secret_ref: { store_id: "sqlcipher_inline", state: "missing" },
        is_default: true,
      },
      {
        name: "omlx",
        display_name: "oMLX",
        base_url: "http://127.0.0.1:8000/v1",
        kind: "local",
        default_model: null,
        notes: "Local oMLX (mock).",
        acknowledged_at: "2026-04-27T08:00:00Z",
        created_at: "2026-04-27T08:00:00Z",
        updated_at: "2026-04-27T08:00:00Z",
        has_api_key: false,
        secret_ref: { store_id: "sqlcipher_inline", state: "missing" },
        is_default: false,
      },
    ],
    default: "ollama",
    secret_store_policy: {
      platform: "macos",
      availability: {
        state: "available",
        identity_strength: "unknown_or_unsigned",
      },
      default: {
        store_id: "sqlcipher_inline",
        native_store_id: "macos_keychain",
        native_available: true,
        warning:
          "Unsigned or ad-hoc macOS builds keep AI keys in SQLCipher by default; Keychain is an explicit experimental move because prompts may appear again after rebuilds or identity changes.",
      },
    },
  },
  "ai.list_models": {
    provider: "ollama",
    models: [
      { id: "qwen3.6:35b", owned_by: "library" },
      { id: "llama3.3:70b", owned_by: "library" },
    ],
  },
  "ai.test_connection": {
    base_url: "http://localhost:11434/v1",
    model_count: 2,
    models: [
      { id: "qwen3.6:35b", owned_by: "library" },
      { id: "llama3.3:70b", owned_by: "library" },
    ],
  },
};

/**
 * Pre-canned AI chat stream for mock mode. Mimics what Ollama's
 * OpenAI-compat shim sends for current reasoning builds (Qwen3, Gemma
 * reasoning) and what OpenAI o1/o3 endpoints send: structured
 * `reasoning` deltas first, then visible `content` deltas — never both
 * in one stream. The inline `<think>...</think>` tag style used by
 * DeepSeek-R1 / QwQ is covered by `lib/thinkParser.test.ts` rather than
 * mixed into this fixture, so the mock matches one realistic provider
 * shape instead of conflating two.
 */
export const MOCK_AI_CHAT_STREAM: {
  content?: string;
  reasoning?: string;
  delayMs?: number;
}[] = [
  { reasoning: "Preparing a formatting demo. ", delayMs: 20 },
  { reasoning: "Including headings, table, list, quote, and code.", delayMs: 60 },
  { content: "## Review snapshot\n\n", delayMs: 30 },
  {
    content:
      "This is a formatting demo for the assistant transcript. It should show relaxed paragraphs, headings, a CLI-style table, and command output without squeezing everything into a tiny bubble.\n\n",
    delayMs: 40,
  },
  { content: "### CLI-style table\n\n", delayMs: 30 },
  { content: "| Item | Status | Action |\n", delayMs: 30 },
  { content: "| --- | --- | --- |\n", delayMs: 20 },
  { content: "| Journals | Current | Run report exports |\n", delayMs: 30 },
  { content: "| Quarantine | Clear | Keep watching imports |\n", delayMs: 30 },
  { content: "| Rates | Needs review | Sync BTC-EUR cache |\n\n", delayMs: 30 },
  { content: "### Notes\n\n", delayMs: 30 },
  { content: "- Use program output for calculations.\n", delayMs: 30 },
  { content: "- Keep wallet data local.\n", delayMs: 30 },
  { content: "- Reprocess journals after imports.\n\n", delayMs: 30 },
  {
    content:
      "> Tables should be readable and scroll horizontally when needed.\n\n",
    delayMs: 40,
  },
  {
    content: "```bash\nkassiber reports tax-summary --machine\n```\n",
    delayMs: 50,
  },
];
