/**
 * Hand-rolled mock fixtures, keyed by daemon `kind`.
 *
 * Each entry is the `data` body of a successful envelope. Kept minimal
 * until Phase 1.2 §2.2 generates real fixtures from the Pydantic schema.
 * Add entries as screens get translated.
 */

import { MOCK_OVERVIEW } from "@/mocks/seed";
import { MOCK_TRANSACTIONS } from "@/mocks/transactions";
import { MOCK_PROFILES } from "@/mocks/profiles";
import { MOCK_WORKSPACE_OVERVIEW } from "@/mocks/workspaceOverview";
import { MOCK_CAPITAL_GAINS } from "@/mocks/reports";

const SOURCE_FUNDS_FIXTURE_TARGET_TXID =
  "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766";
const SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID =
  "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211";
const SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS = [
  {
    txid: SOURCE_FUNDS_FIXTURE_TARGET_TXID,
    asset: "BTC",
    network: "bitcoin",
    label: "mempool.space",
    url: `https://mempool.space/tx/${SOURCE_FUNDS_FIXTURE_TARGET_TXID}`,
  },
  {
    txid: SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
    asset: "BTC",
    network: "bitcoin",
    label: "mempool.space",
    url: `https://mempool.space/tx/${SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID}`,
  },
];

export const fixtures: Record<string, unknown> = {
  status: {
    version: "0.0.0-ui-scaffold",
    data_root: "~/.kassiber",
    workspace: null,
    profile: null,
  },
  "ui.logs.snapshot": {
    records: [],
    last_id: 0,
    gap: false,
    started_at: "mock",
    buffer_bytes: 0,
    max_bytes: 4194304,
  },
  "ui.overview.snapshot": MOCK_OVERVIEW,
  "ui.workspace.overview.snapshot": MOCK_WORKSPACE_OVERVIEW,
  "ui.connections.node.snapshot": {
    error: "Pass `connection` to ui.connections.node.snapshot (handled in mock.ts).",
  },
  "ui.reports.lightning_profitability": {
    error: "Pass `connection` to ui.reports.lightning_profitability (handled in mock.ts).",
  },
  "ui.transactions.list": MOCK_TRANSACTIONS,
  "ui.transactions.extremes": {
    largest: MOCK_TRANSACTIONS.txs.slice(0, 3),
    smallest: MOCK_TRANSACTIONS.txs.slice(-3),
    filters: { limit: 3, sort: "amount", scope: "all_time_before_limit" },
  },
  "ui.transactions.search": {
    txs: MOCK_TRANSACTIONS.txs.slice(0, 4),
    filters: {
      query: "invoice",
      limit: 25,
      sort: "occurred-at",
      order: "desc",
    },
  },
  "ui.transactions.resolve": {
    transaction: null,
    query: "",
  },
  "ui.wallets.sync": {
    results: MOCK_OVERVIEW.connections.map((connection) => ({
      wallet: connection.label,
      status: "synced",
      inserted: 0,
      updated: 0,
    })),
  },
  "ui.wallets.utxos": {
    wallet: {
      id: "c1",
      label: "Cold Storage",
    },
    utxos: [
      {
        id: "coin-1",
        outpoint:
          "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766:0",
        txid: "4e9f0b7d8c6a5b4c3d2e1f0099887766554433221100ffeeddccbbaa99887766",
        vout: 0,
        asset: "BTC",
        amount: 0.125,
        amount_sat: 12_500_000,
        amount_msat: 12_500_000_000,
        confirmation_status: "confirmed",
        confirmations: 18,
        block_height: 884_200,
        block_time: "2026-03-18T10:20:00Z",
        address: "bc1qmockcoinaddress0000000000000000000000000000",
        address_label: "receive #12",
        branch_label: "receive",
        branch_index: 0,
        address_index: 12,
        source: {
          backend: "mempool",
          backend_kind: "esplora",
          chain: "bitcoin",
          network: "mainnet",
          first_seen_at: "2026-03-18T10:22:00Z",
          last_seen_at: "2026-03-18T10:22:00Z",
          spent_at: null,
        },
      },
      {
        id: "coin-2",
        outpoint:
          "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211:1",
        txid: "6f1e2d3c4b5a69788776655443322110ffeeddccbbaa00998877665544332211",
        vout: 1,
        asset: "BTC",
        amount: 0.03125,
        amount_sat: 3_125_000,
        amount_msat: 3_125_000_000,
        confirmation_status: "mempool",
        confirmations: 0,
        block_height: null,
        block_time: null,
        address: "bc1qmockchangeaddress000000000000000000000000000",
        address_label: "change #4",
        branch_label: "change",
        branch_index: 1,
        address_index: 4,
        source: {
          backend: "mempool",
          backend_kind: "esplora",
          chain: "bitcoin",
          network: "mainnet",
          first_seen_at: "2026-03-18T10:24:00Z",
          last_seen_at: "2026-03-18T10:24:00Z",
          spent_at: null,
        },
      },
    ],
    totals: [
      {
        asset: "BTC",
        amount: 0.15625,
        amount_sat: 15_625_000,
        amount_msat: 15_625_000_000,
      },
    ],
    support: {
      supported: true,
      status: "supported",
      reason: "",
      message: "",
    },
    freshness: {
      status: "current",
      last_seen_at: "2026-03-18T10:24:00Z",
      last_synced_at: "2026-03-18T10:24:00Z",
      stale: false,
      active_count: 2,
    },
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 2,
    },
  },
  "ui.freshness.run": {
    profile: { id: "mock-profile", label: "Demo book" },
    results: MOCK_OVERVIEW.connections.map((connection) => ({
      wallet: connection.label,
      status: "synced",
      inserted: 0,
      updated: 0,
    })),
    enqueued: [
      {
        job_type: "onchain_wallet_history",
        source_label: "Treasury watch-only",
        source_type: "onchain_wallet",
        status: "queued",
      },
      {
        job_type: "market_rate_coverage",
        source_label: "Market-rate coverage",
        source_type: "market_rates",
        status: "queued",
      },
      {
        job_type: "journal_refresh",
        source_label: "Journals",
        source_type: "journals",
        status: "queued",
      },
    ],
    completed: [
      {
        job_type: "onchain_wallet_history",
        source_label: "Treasury watch-only",
        source_type: "onchain_wallet",
        status: "done",
      },
      {
        job_type: "market_rate_coverage",
        source_label: "Market-rate coverage",
        source_type: "market_rates",
        status: "done",
      },
      {
        job_type: "journal_refresh",
        source_label: "Journals",
        source_type: "journals",
        status: "done",
      },
    ],
    sources: [
      {
        source_key: "onchain_wallet:mock-wallet",
        source_type: "onchain_wallet",
        source_label: "Treasury watch-only",
        status: "fresh",
        blocking_reports: false,
      },
      {
        source_key: "market_rates:mock-profile",
        source_type: "market_rates",
        source_label: "Market-rate coverage",
        status: "fresh",
        blocking_reports: false,
      },
      {
        source_key: "journals:mock-profile",
        source_type: "journals",
        source_label: "Journals",
        status: "fresh",
        blocking_reports: false,
      },
    ],
    jobs: [],
    summary: {
      sources: 3,
      active_jobs: 0,
      blocking_reports: 0,
      rate_limited: 0,
      failed: 0,
    },
  },
  "ui.transfers.suggest": {
    candidates: [
      {
        out_id: "tx:phoenix-out",
        in_id: "tx:liquid-in",
        out_asset: "BTC",
        in_asset: "LBTC",
        out_amount_msat: 100_000_000,
        in_amount_msat: 99_500_000,
        out_amount: 0.001,
        in_amount: 0.000995,
        out_wallet: "Phoenix LN",
        in_wallet: "Liquid Vault",
        out_wallet_kind: "phoenix",
        in_wallet_kind: "descriptor",
        out_occurred_at: "2026-03-14T17:30:00Z",
        in_occurred_at: "2026-03-14T17:32:00Z",
        confidence: "strong",
        method: "heuristic",
        payment_hash: null,
        swap_fee_msat: 500_000,
        swap_fee: 0.000005,
        swap_fee_kind: "combined",
        default_kind: "submarine-swap",
        default_policy: "carrying-value",
        conflict_set_id: "solo:phoenix-liquid",
        conflict_size: 1,
        rule_match: {
          rule_id: "rule:phoenix-liquid",
          rule_name: "Phoenix to Liquid",
          kind: "submarine-swap",
          policy: "carrying-value",
        },
      },
      {
        out_id: "tx:liquid-out",
        in_id: "tx:onchain-in",
        out_asset: "LBTC",
        in_asset: "BTC",
        out_amount_msat: 250_000_000,
        in_amount_msat: 249_300_000,
        out_amount: 0.0025,
        in_amount: 0.002493,
        out_wallet: "Liquid Vault",
        in_wallet: "Bitcoin Vault",
        out_wallet_kind: "descriptor",
        in_wallet_kind: "descriptor",
        out_occurred_at: "2026-03-15T08:10:00Z",
        in_occurred_at: "2026-03-15T09:45:00Z",
        confidence: "exact",
        method: "payment_hash",
        payment_hash: "mock-payment-hash",
        swap_fee_msat: 700_000,
        swap_fee: 0.000007,
        swap_fee_kind: "combined",
        default_kind: "peg-out",
        default_policy: "carrying-value",
        conflict_set_id: "solo:liquid-onchain",
        conflict_size: 1,
      },
    ],
    counts: {
      total: 2,
      exact: 1,
      strong: 1,
      conflicts: 0,
      rule_matches: 1,
    },
  },
  "ui.transfers.bulk_pair": {
    applied: [
      {
        id: "pair:exact",
        swap_fee_msat: 700_000,
      },
    ],
    summary: {
      count: 1,
      skipped_conflicts: 0,
      total_swap_fee_msat: 700_000,
    },
  },
  "ui.transfers.rules.apply": {
    applied: [
      {
        id: "pair:rule",
        swap_fee_msat: 500_000,
      },
    ],
    summary: {
      count: 1,
      remaining: 1,
      total_swap_fee_msat: 500_000,
    },
  },
  "ui.transfers.pair": {
    id: "pair:manual",
    swap_fee_msat: 500_000,
  },
  "ui.transfers.dismiss": {
    dismissed: "tx:phoenix-out->tx:liquid-in",
  },
  "ui.transfers.unpair": {
    deleted: "pair:manual",
  },
  "ui.transfers.rules.list": {
    rules: [
      {
        id: "rule:phoenix-liquid",
        name: "Phoenix to Liquid",
        predicate: {
          out_wallet_kind: "phoenix",
          in_asset: "LBTC",
          min_confidence: "strong",
        },
        kind: "submarine-swap",
        policy: "carrying-value",
        enabled: true,
        created_at: "2026-03-14T17:35:00Z",
        updated_at: "2026-03-14T17:35:00Z",
      },
    ],
  },
  "ui.transfers.rules.create": {
    id: "rule:new",
    name: "New swap rule",
    predicate: {},
    kind: "submarine-swap",
    policy: "carrying-value",
    enabled: true,
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:35:00Z",
  },
  "ui.transfers.rules.delete": {
    deleted: "rule:phoenix-liquid",
  },
  "ui.transfers.rules.set_enabled": {
    id: "rule:phoenix-liquid",
    name: "Phoenix to Liquid",
    predicate: {
      out_wallet_kind: "phoenix",
      in_asset: "LBTC",
      min_confidence: "strong",
    },
    kind: "submarine-swap",
    policy: "carrying-value",
    enabled: false,
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:40:00Z",
  },
  "ui.saved_views.list": {
    views: [],
  },
  "ui.saved_views.create": {
    id: "view:new",
    surface: "swap_candidates",
    name: "Review queue",
    filter: {},
    created_at: "2026-03-14T17:35:00Z",
    updated_at: "2026-03-14T17:35:00Z",
  },
  "ui.saved_views.delete": {
    deleted: "view:new",
  },
  "ui.backends.options": {
    backends: [
      {
        name: "mempool",
        kind: "esplora",
        chain: "bitcoin",
        network: "mainnet",
        has_url: true,
        is_default: true,
      },
      {
        name: "liquid",
        kind: "electrum",
        chain: "liquid",
        network: "liquidv1",
        has_url: true,
        is_default: false,
      },
      {
        name: "liquid-blockstream",
        kind: "electrum",
        chain: "liquid",
        network: "liquidv1",
        has_url: true,
        is_default: false,
      },
      {
        name: "btcpay-demo",
        kind: "btcpay",
        chain: "bitcoin",
        network: "mainnet",
        has_url: true,
        has_token: true,
        is_default: false,
      },
    ],
    summary: {
      count: 4,
      default_backend: "mempool",
    },
    suggestions: [
      {
        name: "mempool",
        label: "Built-in mempool.space Bitcoin backend",
        chain: "bitcoin",
        network: "mainnet",
      },
      {
        name: "liquid",
        label: "Built-in BullBitcoin Liquid Electrum backend",
        chain: "liquid",
        network: "liquidv1",
      },
      {
        name: "liquid-blockstream",
        label: "Built-in Blockstream Liquid Electrum backend",
        chain: "liquid",
        network: "liquidv1",
      },
    ],
  },
  "ui.profiles.snapshot": MOCK_PROFILES,
  "ui.reports.capital_gains": MOCK_CAPITAL_GAINS,
  "ui.reports.summary": {
    workspace: "My Books",
    profile: "local books",
    wallet: null,
    fiat_currency: "EUR",
    metrics: {
      wallets_in_scope: 2,
      assets_in_scope: 1,
      active_transactions: 12,
      excluded_transactions: 0,
      inbound_transactions: 7,
      outbound_transactions: 5,
      journal_entries: 18,
      quarantines: 0,
    },
    asset_flow: [
      {
        asset: "BTC",
        inbound_amount: 0.42,
        inbound_amount_sat: 42_000_000,
        inbound_amount_msat: 42_000_000_000,
        outbound_amount: 0.15,
        outbound_amount_sat: 15_000_000,
        outbound_amount_msat: 15_000_000_000,
        fee_amount: 0.0001,
        fee_amount_sat: 10_000,
        fee_amount_msat: 10_000_000,
      },
    ],
    wallet_flow: [],
  },
  "ui.reports.balance_sheet": {
    rows: [
      {
        account: "treasury",
        account_label: "Treasury",
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    totals_by_asset: [
      {
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    summary: { row_count: 1, asset_count: 1 },
  },
  "ui.reports.portfolio_summary": {
    rows: [
      {
        wallet: "Multisig Vault",
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        average_cost: 71_388.89,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    totals_by_asset: [
      {
        asset: "BTC",
        quantity: 0.27,
        quantity_sat: 27_000_000,
        quantity_msat: 27_000_000_000,
        cost_basis: 19_275.0,
        market_value: 19_283.45,
        unrealized_pnl: 8.45,
      },
    ],
    summary: { row_count: 1, asset_count: 1 },
  },
  "ui.reports.tax_summary": {
    rows: [
      {
        row_type: "year_total",
        year: 2025,
        asset: "BTC",
        quantity: 0.253,
        quantity_msat: 25_300_000_000,
        proceeds: 17_991.95,
        cost_basis: 10_078.35,
        gain_loss: 7_913.6,
      },
    ],
    available_years: [2025, 2026],
    filters: { year: 2025 },
    summary: { row_count: 1, available_year_count: 2 },
  },
  "ui.reports.balance_history": {
    rows: [
      { period_start: "2026-01-01T00:00:00Z", asset: "BTC", quantity: 0.12 },
      { period_start: "2026-02-01T00:00:00Z", asset: "BTC", quantity: 0.18 },
      { period_start: "2026-03-01T00:00:00Z", asset: "BTC", quantity: 0.27 },
    ],
    filters: { interval: "month", limit: 120 },
    summary: { row_count: 3, total_row_count: 3, truncated: false },
  },
  "ui.reports.export_pdf": {
    file: "~/.kassiber/exports/reports/kassiber-report-mock.pdf",
    filename: "kassiber-report-mock.pdf",
    format: "pdf",
    scope: "report",
    pages: 4,
    bytes: 24576,
    title: "Kassiber Report - Mock",
  },
  "ui.reports.export_summary_pdf": {
    file: "~/.kassiber/exports/reports/kassiber-summary-report-mock.pdf",
    filename: "kassiber-summary-report-mock.pdf",
    format: "pdf",
    scope: "summary_report",
    pages: 3,
    bytes: 28672,
    title: "Kassiber Summary Report - Mock",
    snapshot: true,
    wallets: [
      { id: "wallet:multisig-vault", label: "Multisig Vault" },
      { id: "wallet:node", label: "Home Node" },
    ],
    timeframe: {
      start: "2026-01-01T00:00:00Z",
      end: "2026-12-31T23:59:59Z",
      label: "2026-01-01 to 2026-12-31",
    },
  },
  "ui.reports.export_csv": {
    file: "~/.kassiber/exports/reports/kassiber-report-mock.csv",
    filename: "kassiber-report-mock.csv",
    format: "csv",
    scope: "report",
    rows: 24,
    bytes: 12288,
    sections: ["Overview", "Wallets", "Asset Flow", "Transactions"],
  },
  "ui.reports.export_xlsx": {
    file: "~/.kassiber/exports/reports/kassiber-report-mock.xlsx",
    filename: "kassiber-report-mock.xlsx",
    format: "xlsx",
    scope: "report",
    rows: 24,
    sheets: ["Overview", "Wallets", "Asset Flow", "Transactions"],
    bytes: 20480,
  },
  "ui.reports.export_capital_gains_csv": {
    file: "~/.kassiber/exports/reports/kassiber-capital-gains-mock.csv",
    filename: "kassiber-capital-gains-mock.csv",
    format: "csv",
    scope: "capital_gains",
    rows: MOCK_CAPITAL_GAINS.lots.length,
    bytes: 8192,
  },
  "ui.reports.export_austrian_e1kv_pdf": {
    file: "~/.kassiber/exports/reports/kassiber-austrian-e1kv-2025-mock.pdf",
    filename: "kassiber-austrian-e1kv-2025-mock.pdf",
    format: "pdf",
    scope: "austrian_e1kv",
    tax_year: 2025,
    pages: 4,
    bytes: 32768,
  },
  "ui.reports.export_austrian_e1kv_xlsx": {
    file: "~/.kassiber/exports/reports/kassiber-austrian-e1kv-2025-mock.xlsx",
    filename: "kassiber-austrian-e1kv-2025-mock.xlsx",
    format: "xlsx",
    scope: "austrian_e1kv",
    tax_year: 2025,
    rows: MOCK_CAPITAL_GAINS.lots.length,
    summary_rows: 3,
    bytes: 24576,
  },
  "ui.reports.export_austrian_e1kv_csv": {
    dir: "~/.kassiber/exports/reports/kassiber-austrian-e1kv-2025-csv-mock",
    filename: "kassiber-austrian-e1kv-2025-csv-mock",
    format: "csv",
    scope: "austrian_e1kv",
    tax_year: 2025,
    rows: MOCK_CAPITAL_GAINS.lots.length,
    summary_rows: 3,
    files: [
      {
        sheet: "Übersicht",
        file: "~/.kassiber/exports/reports/kassiber-austrian-e1kv-2025-csv-mock/00_uebersicht.csv",
        rows: 3,
        bytes: 2048,
      },
    ],
  },
  "ui.source_funds.preview": {
    workspace: "My Books",
    profile: "local books",
    purpose: {
      type: "planned_exchange_sale",
      label: "Planned exchange sale",
      anchor_role: "funds_history_anchor",
      planned_destination: "Mock Exchange",
      planned_note: "Pre-disclosure before expected EUR proceeds arrive.",
      fiat_purchase_note: "If the bitcoin was bought on an exchange, fiat-source evidence for that original purchase is separate supporting evidence.",
    },
    target: {
      transaction_id: "tx19",
      label: "Vault migration",
      external_id: "mock-target-deposit",
      wallet: "Multisig Vault",
      occurred_at: "2024-11-05T10:12:00Z",
      direction: "inbound",
      asset: "BTC",
      required_amount: 0.15,
      required_amount_msat: 15_000_000_000,
      fiat_value: 10713.03,
    },
    reveal_mode: "standard",
    graph: {
      nodes: [
        { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC" },
        { id: "tx:1", node_type: "transaction", label: "withdraw-1", wallet: "Exchange", asset: "BTC" },
        { id: "tx:2", node_type: "transaction", label: "target deposit", wallet: "Multisig Vault", asset: "BTC" },
      ],
      edges: [
        { id: "link:1", link_type: "manual_source", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
      ],
    },
    allocations: {
      target_amount: 0.15,
      target_amount_msat: 15_000_000_000,
      asset: "BTC",
      reviewed_edge_count: 1,
    },
    source_mix: [{ source_type: "fiat_purchase", amount: 0.15, amount_msat: 15_000_000_000, percent_of_target: 100, count: 1 }],
    report_context: {
      tax_country: "at",
      fiat_currency: "EUR",
      jurisdiction_label: "Austria",
      template_key: "at_eur_basic",
      report_title: "Mittelherkunftsnachweis / Source of Funds Report",
      report_subtitle: "Reviewed local evidence disclosure for an Austrian/EUR source-of-funds workflow.",
    },
    overview: {
      target_label: "Vault migration",
      target_asset: "BTC",
      target_amount: 0.15,
      target_fiat_value: 10713.03,
      target_fiat_currency: "EUR",
      target_date: "2024-11-05T10:12:00Z",
      target_wallet: "Multisig Vault",
      time_range: { start: "2024-10-31T09:00:00Z", end: "2024-11-05T10:12:00Z" },
      transaction_count: 2,
      link_count: 1,
      root_source_count: 1,
      source_category_count: 1,
      data_source_count: 2,
      blocker_count: 0,
      warning_count: 1,
    },
    narrative: {
      generated_by: "local_rule_summary",
      paragraphs: [
        "This report traces 0.15000000 BTC for Vault migration through 1 reviewed link across 2 transactions.",
        "The reviewed source mix is fiat purchase: 0.15000000 BTC, 100.0% of target. The path spans 2024-10-31T09:00:00Z to 2024-11-05T10:12:00Z and uses 2 local data sources.",
        "Export is currently clear under the current review gates.",
      ],
    },
    data_sources: [
      {
        label: "Multisig Vault",
        kind: "wallet",
        transaction_count: 1,
        source_count: 0,
        assets: ["BTC"],
        first_seen: "2024-11-05T10:12:00Z",
        last_seen: "2024-11-05T10:12:00Z",
      },
      {
        label: "Reviewed exchange purchase",
        kind: "fiat_purchase",
        transaction_count: 0,
        source_count: 1,
        assets: ["BTC"],
        first_seen: "2024-10-31T09:00:00Z",
        last_seen: "2024-10-31T09:00:00Z",
      },
    ],
    flow_levels: [
      {
        level: 1,
        role: "target",
        transaction_count: 1,
        source_count: 0,
        nodes: [
          { id: "tx:2", node_type: "transaction", label: "target deposit", wallet: "Multisig Vault", asset: "BTC", required_amount: 0.15, occurred_at: "2024-11-05T10:12:00Z", external_id: "mock-target-deposit" },
        ],
      },
      {
        level: 2,
        role: "upstream",
        transaction_count: 0,
        source_count: 1,
        nodes: [
          { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC", required_amount: 0.15, acquired_at: "2024-10-31T09:00:00Z" },
        ],
      },
    ],
    simplified_flow: {
      note: "Simplified flow follows reviewed local links. Wallet transfers and consolidations are shown as reviewed hops; CoinJoin/PayJoin traversal is deferred and shown only as a privacy boundary.",
      deferred_privacy_hops: [],
      levels: [
        {
          level: 1,
          role: "source",
          distance_to_target: 1,
          nodes: [
            {
              id: "source:1",
              node_type: "source",
              kind: "fiat_purchase",
              label: "Reviewed exchange purchase",
              asset: "BTC",
              amount: 0.15,
              occurred_at: "2024-10-31T09:00:00Z",
            },
          ],
        },
        {
          level: 2,
          role: "target",
          distance_to_target: 0,
          nodes: [
            {
              id: "tx:2",
              node_type: "transaction",
              kind: "inbound",
              label: "target deposit",
              wallet: "Multisig Vault",
              asset: "BTC",
              amount: 0.15,
              occurred_at: "2024-11-05T10:12:00Z",
            },
          ],
        },
      ],
      edges: [
        {
          id: "link:1",
          from: "source:1",
          to: "tx:2",
          link_type: "manual_source",
          asset: "BTC",
          amount: 0.15,
          deferred_privacy_hop: false,
        },
      ],
    },
    gaps: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    findings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    explain_gates: { exportable: true, blockers: [], warnings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }] },
    disclosure_preview: {
      txids: [
        SOURCE_FUNDS_FIXTURE_TARGET_TXID,
        SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
      ],
      explorer_links: SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS,
      attachments: [{ id: "att:1", label: "Exchange statement", attachment_type: "file" }],
      privacy_note: "Txids disclose on-chain neighbors to the recipient. Chain observations are context, not proof of ownership.",
      excluded: ["descriptors", "xpubs", "wallet files", "seeds", "backend tokens", "unrelated wallet history"],
    },
  },
  "ui.source_funds.cases.save": {
    workspace: "My Books",
    profile: "local books",
    purpose: {
      type: "planned_exchange_sale",
      label: "Planned exchange sale",
      anchor_role: "funds_history_anchor",
      planned_destination: "Mock Exchange",
      planned_note: "Pre-disclosure before expected EUR proceeds arrive.",
      fiat_purchase_note: "If the bitcoin was bought on an exchange, fiat-source evidence for that original purchase is separate supporting evidence.",
    },
    target: {
      transaction_id: "tx19",
      label: "Vault migration",
      external_id: "mock-target-deposit",
      wallet: "Multisig Vault",
      occurred_at: "2024-11-05T10:12:00Z",
      direction: "inbound",
      asset: "BTC",
      required_amount: 0.15,
      required_amount_msat: 15_000_000_000,
      fiat_value: 10713.03,
    },
    reveal_mode: "standard",
    case: {
      id: "case:source-funds-demo",
      snapshot_id: "snapshot:source-funds-demo",
      status: "exportable",
      snapshot_hash: "mock-source-funds-snapshot",
      created_at: "2024-11-05T10:30:00Z",
    },
    graph: {
      nodes: [
        { id: "source:1", node_type: "source", source_type: "fiat_purchase", label: "Reviewed exchange purchase", asset: "BTC" },
        { id: "tx:1", node_type: "transaction", label: "withdraw-1", wallet: "Exchange", asset: "BTC" },
        { id: "tx:2", node_type: "transaction", label: "target deposit", wallet: "Multisig Vault", asset: "BTC" },
      ],
      edges: [
        { id: "link:1", link_type: "manual_source", state: "reviewed", method: "manual", allocation_amount: 0.15, asset: "BTC", allocation_policy: "explicit" },
      ],
    },
    allocations: {
      target_amount: 0.15,
      target_amount_msat: 15_000_000_000,
      asset: "BTC",
      reviewed_edge_count: 1,
    },
    source_mix: [{ source_type: "fiat_purchase", amount: 0.15, amount_msat: 15_000_000_000, count: 1 }],
    gaps: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    findings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }],
    explain_gates: { exportable: true, blockers: [], warnings: [{ code: "missing_history", severity: "warning", message: "Reviewed prior-history gap included.", ref: "source:gap" }] },
    disclosure_preview: {
      txids: [
        SOURCE_FUNDS_FIXTURE_TARGET_TXID,
        SOURCE_FUNDS_FIXTURE_WITHDRAW_TXID,
      ],
      explorer_links: SOURCE_FUNDS_FIXTURE_EXPLORER_LINKS,
      attachments: [{ id: "att:1", label: "Exchange statement", attachment_type: "file" }],
      privacy_note: "Txids disclose on-chain neighbors to the recipient. Chain observations are context, not proof of ownership.",
      excluded: ["descriptors", "xpubs", "wallet files", "seeds", "backend tokens", "unrelated wallet history"],
    },
  },
  "ui.source_funds.cases.list": {
    cases: [
      {
        id: "case:source-funds-demo",
        label: "Demo disclosure",
        target_transaction_id: "tx19",
        target_external_id: "mock-target-deposit",
        target_amount: 0.15,
        target_amount_msat: 15_000_000_000,
        asset: "BTC",
        reveal_mode: "standard",
        status: "exportable",
        snapshot_hash: "mock-source-funds-snapshot",
        recipient_id: null,
        recipient_label: "",
        recipient_kind: "",
        recipient_reveal_mode: "",
        created_at: "2024-11-05T10:30:00Z",
        updated_at: "2024-11-05T10:30:00Z",
      },
    ],
  },
  "ui.source_funds.sources.list": {
    sources: [
      {
        id: "source:1",
        source_type: "fiat_purchase",
        label: "Reviewed exchange purchase",
        asset: "BTC",
        amount: 0.15,
        amount_msat: 15_000_000_000,
        description: "Exchange statement and purchase receipt reviewed.",
        attachments: [
          { id: "att:1", label: "Exchange statement", attachment_type: "file" },
        ],
      },
    ],
  },
  "ui.source_funds.sources.create": {
    id: "source:new",
    source_type: "fiat_purchase",
    label: "New reviewed source",
    asset: "BTC",
    amount: 0.15,
    amount_msat: 15_000_000_000,
    description: "",
    attachments: [],
  },
  "ui.source_funds.sources.attach": {
    id: "source:1",
    source_type: "fiat_purchase",
    label: "Reviewed exchange purchase",
    asset: "BTC",
    amount: 0.15,
    amount_msat: 15_000_000_000,
    attachments: [
      { id: "att:1", label: "Exchange statement", attachment_type: "file" },
    ],
  },
  "ui.source_funds.links.list": {
    links: [
      {
        id: "link:1",
        from_source_id: "source:1",
        from_transaction_id: null,
        to_transaction_id: "tx19",
        link_type: "manual_source",
        state: "reviewed",
        confidence: "strong",
        method: "manual",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: null,
        allocation_policy: "explicit",
        explanation: "Reviewed exchange source.",
        attachments: [
          { id: "att:1", label: "Exchange statement", attachment_type: "file" },
        ],
      },
      {
        id: "link:2",
        from_source_id: null,
        from_transaction_id: "tx12",
        to_transaction_id: "tx19",
        link_type: "self_transfer",
        state: "suggested",
        confidence: "weak",
        method: "tight_time_amount_match",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: 0.15001,
        allocation_policy: "heuristic",
        explanation: "Same-day amount match across owned wallets.",
        attachments: [],
      },
    ],
  },
  "ui.source_funds.links.create": {
    id: "link:new",
    from_source_id: "source:new",
    from_transaction_id: null,
    to_transaction_id: "tx19",
    link_type: "manual_source",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: null,
    allocation_policy: "explicit",
    explanation: "",
    attachments: [],
  },
  "ui.source_funds.links.review": {
    id: "link:2",
    from_source_id: null,
    from_transaction_id: "tx12",
    to_transaction_id: "tx19",
    link_type: "self_transfer",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: 0.15001,
    allocation_policy: "explicit",
    explanation: "Reviewed self-transfer.",
    attachments: [],
  },
  "ui.source_funds.links.bulk_review": {
    reviewed: 1,
    skipped: 1,
    target_transaction_id: "tx19",
    links: [
      {
        id: "link:3",
        from_source_id: null,
        from_transaction_id: "tx8",
        to_transaction_id: "tx12",
        link_type: "self_transfer",
        state: "reviewed",
        confidence: "exact",
        method: "same_external_id",
        asset: "BTC",
        allocation_amount: 0.15,
        from_allocation_amount: 0.1501,
        allocation_policy: "explicit",
        explanation: "Same external transaction id.",
        attachments: [],
      },
    ],
    policy:
      "Bulk review only accepts exact/strong deterministic suggestions. Weak hints remain manual.",
  },
  "ui.source_funds.links.attach": {
    id: "link:2",
    from_source_id: null,
    from_transaction_id: "tx12",
    to_transaction_id: "tx19",
    link_type: "self_transfer",
    state: "reviewed",
    confidence: "strong",
    method: "manual",
    asset: "BTC",
    allocation_amount: 0.15,
    from_allocation_amount: 0.15001,
    allocation_policy: "explicit",
    explanation: "Reviewed self-transfer.",
    attachments: [
      { id: "att:1", label: "Exchange statement", attachment_type: "file" },
    ],
  },
  "ui.source_funds.suggest": {
    inserted: 1,
    target_transaction_id: "tx19",
    links: [],
    privacy_warning: "No chain backend was queried.",
  },
  "ui.source_funds.evidence.list": {
    attachments: [
      {
        id: "att:1",
        attachment_type: "file",
        label: "Exchange statement",
        external_id: "mock-target-deposit",
        wallet: "Multisig Vault",
        occurred_at: "2024-11-05T10:12:00Z",
      },
    ],
  },
  "ui.source_funds.export_pdf": {
    file: "~/.kassiber/exports/reports/kassiber-source-funds-mock.pdf",
    filename: "kassiber-source-funds-mock.pdf",
    format: "pdf",
    scope: "source_funds",
    pages: 3,
    bytes: 18432,
    exportable: true,
  },
  "ui.source_funds.coverage": {
    scope: "historical_inbound",
    scope_note:
      "Counts every inbound transaction. Not a current-holdings view: self-transfers between owned wallets are counted at each hop, and already-spent inflows still appear in the totals.",
    by_wallet: [
      {
        wallet_id: "wallet:multisig-vault",
        wallet_label: "Multisig Vault",
        asset: "BTC",
        buckets: {
          fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
          attested: { amount_msat: 0, amount: 0, tx_count: 0 },
          in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
          untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
          not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
        },
        total_inbound_msat: 15_000_000_000,
        total_inbound: 0.15,
      },
    ],
    by_asset: [
      {
        asset: "BTC",
        buckets: {
          fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
          attested: { amount_msat: 0, amount: 0, tx_count: 0 },
          in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
          untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
          not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
        },
        total_inbound_msat: 15_000_000_000,
        total_inbound: 0.15,
      },
    ],
    totals: {
      buckets: {
        fully_traced: { amount_msat: 15_000_000_000, amount: 0.15, tx_count: 1 },
        attested: { amount_msat: 0, amount: 0, tx_count: 0 },
        in_review: { amount_msat: 0, amount: 0, tx_count: 0 },
        untraced: { amount_msat: 0, amount: 0, tx_count: 0 },
        not_classified: { amount_msat: 0, amount: 0, tx_count: 0 },
      },
      tx_count: 1,
      amount_msat: 15_000_000_000,
      amount: 0.15,
    },
    limits: { max_depth: 8, max_transactions: 5000 },
    truncation: {
      truncated: false,
      inbound_total_count: 1,
      inbound_total_msat: 15_000_000_000,
      inbound_total: 0.15,
      not_classified_count: 0,
      not_classified_msat: 0,
      not_classified: 0,
    },
  },
  "ui.source_funds.recipients.list": {
    recipients: [
      {
        id: "recipient:bank-austria",
        label: "Bank Austria",
        kind: "bank",
        default_reveal_mode: "minimal",
        notes: "Account manager prefers minimal disclosure.",
        active: true,
        created_at: "2024-09-01T08:00:00Z",
        updated_at: "2024-09-01T08:00:00Z",
      },
      {
        id: "recipient:mock-exchange",
        label: "Mock Exchange",
        kind: "exchange",
        default_reveal_mode: "standard",
        active: true,
        created_at: "2024-09-01T08:00:00Z",
        updated_at: "2024-09-01T08:00:00Z",
      },
      {
        id: "recipient:retired-broker",
        label: "Retired Broker",
        kind: "exchange",
        default_reveal_mode: "standard",
        active: false,
        created_at: "2024-08-01T08:00:00Z",
        updated_at: "2024-09-15T08:00:00Z",
      },
    ],
  },
  "ui.journals.snapshot": {
    status: {
      workspace: "My Books",
      profile: "local books",
      transactionCount: MOCK_OVERVIEW.txs.length,
      journalEntryCount: 42,
      needsJournals: false,
      quarantines: 0,
      lastProcessedAt: "2026-04-26T12:00:00Z",
    },
    entryTypes: [
      { type: "acquisition", count: 28, gainLossEur: 0 },
      { type: "disposal", count: 8, gainLossEur: 1240.5 },
      { type: "transfer_in", count: 3, gainLossEur: 0 },
      { type: "transfer_out", count: 3, gainLossEur: 0 },
    ],
    recent: [],
  },
  "ui.journals.events.list": {
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 4,
      reportableCount: 3,
      needsJournals: false,
      lastProcessedAt: "2026-04-26T12:00:00Z",
      freshnessStatus: "current",
      freshnessReason: "journals match the active transaction count and input version",
      entryTypes: [
        { type: "acquisition", count: 1, gainLossEur: 0 },
        { type: "disposal", count: 1, gainLossEur: 1240.5 },
        { type: "income", count: 1, gainLossEur: 0 },
        { type: "fee", count: 1, gainLossEur: -13.01 },
      ],
      limit: 100,
    },
    events: [
      {
        id: "je-001",
        transactionId: "tx-001",
        transactionExternalId: "seed-inbound-1",
        transactionDirection: "inbound",
        occurredAt: "2026-04-18T12:10:00Z",
        createdAt: "2026-04-18T12:10:01Z",
        entryType: "income",
        wallet: "Cold Storage",
        account: "TREASURY",
        accountLabel: "Cold Storage",
        asset: "BTC",
        quantity: 0.0245,
        quantityMsat: 2_450_000_000,
        fiatValueEur: 1749.79,
        unitCostEur: 71420,
        costBasisEur: null,
        proceedsEur: 1749.79,
        gainLossEur: 0,
        pricingSourceKind: "manual",
        pricingQuality: "exact",
        description: "Revenue receipt",
        atCategory: null,
        atKennzahl: null,
      },
      {
        id: "je-002",
        transactionId: "tx-002",
        transactionExternalId: "vault-sale-1",
        transactionDirection: "outbound",
        occurredAt: "2026-04-17T09:30:00Z",
        createdAt: "2026-04-17T09:30:01Z",
        entryType: "disposal",
        wallet: "Multisig Vault",
        account: "TREASURY",
        accountLabel: "Multisig Vault",
        asset: "BTC",
        quantity: -0.5,
        quantityMsat: -50_000_000_000,
        fiatValueEur: 35600,
        unitCostEur: 71200,
        costBasisEur: 23000,
        proceedsEur: 35600,
        gainLossEur: 12600,
        pricingSourceKind: "rates_cache",
        pricingQuality: "exact",
        description: "Treasury rebalance",
        atCategory: "capital_gain_current",
        atKennzahl: 984,
      },
      {
        id: "je-003",
        transactionId: "tx-003",
        transactionExternalId: "node-fee-1",
        transactionDirection: "outbound",
        occurredAt: "2026-04-16T16:05:00Z",
        createdAt: "2026-04-16T16:05:01Z",
        entryType: "fee",
        wallet: "Home Node",
        account: "OPS",
        accountLabel: "Operations",
        asset: "BTC",
        quantity: -0.0001821,
        quantityMsat: -18_210_000,
        fiatValueEur: 13.01,
        unitCostEur: 71440,
        costBasisEur: 13.01,
        proceedsEur: 0,
        gainLossEur: -13.01,
        pricingSourceKind: "rates_cache",
        pricingQuality: "exact",
        description: "Channel-open fee",
        atCategory: null,
        atKennzahl: null,
      },
    ],
  },
  "ui.journals.quarantine": {
    summary: {
      workspace: "My Books",
      profile: "local books",
      count: 2,
      by_reason: [
        { reason: "missing_price", count: 1 },
        { reason: "insufficient_lots", count: 1 },
      ],
      limit: 100,
    },
    items: [
      {
        transaction_id: "tx-missing-price",
        external_id: "missing-price-1",
        occurred_at: "2026-04-15T08:00:00Z",
        confirmed_at: null,
        wallet: "Cold Storage",
        direction: "inbound",
        asset: "BTC",
        amount: 0.0041,
        amount_msat: 410_000_000,
        fee: 0,
        fee_msat: 0,
        reason: "missing_price",
        detail: { field: "fiat_rate" },
        created_at: "2026-04-26T12:00:00Z",
      },
      {
        transaction_id: "tx-missing-basis",
        external_id: "basis-review-1",
        occurred_at: "2026-04-12T14:20:00Z",
        confirmed_at: null,
        wallet: "Multisig Vault",
        direction: "outbound",
        asset: "BTC",
        amount: 0.25,
        amount_msat: 25_000_000_000,
        fee: 0.00001,
        fee_msat: 1_000_000,
        reason: "insufficient_lots",
        detail: { available: "0 BTC", needed: "0.25 BTC" },
        created_at: "2026-04-26T12:00:00Z",
      },
    ],
  },
  "ui.journals.process": {
    profile: "local books",
    entries_created: 42,
    quarantined: 0,
    transfers_detected: 3,
    cross_asset_pairs: 0,
    auto_priced: 0,
    processed_transactions: MOCK_OVERVIEW.txs.length,
    processed_at: "2026-04-26T12:00:00Z",
  },
  "ui.rates.coverage": {
    workspace: "My Books",
    profile: "local books",
    summary: {
      active_transactions: 12,
      priced_transactions: 11,
      missing_price_transactions: 1,
      cache_coverable_missing: 1,
      cache_uncovered_missing: 0,
    },
    items: [
      {
        id: "mock-missing-price",
        externalId: "mock-txid",
        date: "2026-04-22T10:20:00Z",
        wallet: "Multisig Vault",
        direction: "inbound",
        asset: "BTC",
        amountSat: 50_000,
        amountMsat: 50_000_000,
        fiatCurrency: "EUR",
        cachePair: "BTC-EUR",
        cacheHasRate: true,
        cacheRateAt: "2026-04-22T00:00:00Z",
      },
    ],
    filters: { limit: 25 },
  },
  "ui.report.blockers": {
    ready: false,
    blockers: [
      {
        id: "missing_prices",
        severity: "review",
        title: "Missing transaction prices",
        detail: "1 transaction(s) are missing fiat price fields.",
        daemon_kind: "ui.rates.coverage",
      },
    ],
    health: {
      counts: {
        wallets: 2,
        transactions: 12,
        active_transactions: 12,
        journal_entries: 42,
        quarantines: 0,
        rate_pairs: 1,
      },
      journals: {
        status: "current",
        needs_processing: false,
        quarantine_count: 0,
        last_processed_at: "2026-04-26T12:00:00Z",
      },
      reports: { ready: true, hints: ["Reports are ready."] },
    },
    rates_coverage: {
      summary: {
        active_transactions: 12,
        missing_price_transactions: 1,
        cache_coverable_missing: 1,
      },
      items: [],
    },
  },
  "ui.audit.changes_since_last_answer": {
    changed: false,
    baseline: { since: "2026-04-26T12:00:00Z" },
    workspace: "My Books",
    profile: "local books",
    counts_since: {
      transactions: 0,
      journal_entries: 0,
      journal_quarantines: 0,
      wallets: 0,
      rates: 0,
    },
    latest: { journals_processed_at: "2026-04-26T12:00:00Z" },
    current: {
      generated_at: "2026-04-26T12:01:00Z",
      active_transactions: 12,
      journals_processed_at: "2026-04-26T12:00:00Z",
      quarantines: 0,
    },
  },
  "ui.maintenance.settings": {
    workspace: "My Books",
    profile: { id: "mock-profile", label: "local books" },
    settings: {
      background_enabled: false,
      report_read_sync: false,
      source_classes: {
        onchain_wallet: false,
        btcpay_wallet: false,
        btcpay_provenance: false,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: false,
      require_coarse_review: false,
      coarse_priced_count: 3,
      setting_key: "ai.auto_sync_before_report_reads.profile.mock-profile",
    },
  },
  "ui.maintenance.configure": {
    workspace: "My Books",
    profile: { id: "mock-profile", label: "local books" },
    settings: {
      background_enabled: true,
      report_read_sync: true,
      source_classes: {
        onchain_wallet: true,
        btcpay_wallet: true,
        btcpay_provenance: true,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: true,
      setting_key: "ai.auto_sync_before_report_reads.profile.mock-profile",
    },
  },
  "ui.maintenance.run": {
    ready: true,
    sync_mode: "if_enabled",
    maintenance: {
      journals: {
        kind: "ui.journals.process",
        schema_version: 1,
        data: {
          processed_transactions: MOCK_OVERVIEW.txs.length,
          quarantined: 0,
          processed_at: "2026-04-26T12:00:00Z",
        },
      },
    },
    blockers: [],
    health: {
      counts: { active_transactions: 12, quarantines: 0 },
      journals: { status: "current", needs_processing: false },
      reports: { ready: true },
    },
    settings: {
      background_enabled: false,
      report_read_sync: false,
      source_classes: {
        onchain_wallet: false,
        btcpay_wallet: false,
        btcpay_provenance: false,
        market_rates: true,
        journals: true,
      },
      market_rate_provider: "coinbase-exchange",
      market_rate_providers: ["coinbase-exchange", "coingecko", "mempool"],
      market_rate_fiats: ["USD", "EUR", "GBP", "CHF", "AUD", "CAD", "JPY"],
      active_rate_pair: "BTC-EUR",
      auto_sync_before_report_reads: false,
    },
  },
  "ai.providers.list": {
    providers: [
      {
        name: "ollama",
        base_url: "http://localhost:11434/v1",
        kind: "local",
        default_model: "qwen3.6:35b",
        notes: "Local Ollama (mock).",
        acknowledged_at: "2026-04-27T08:00:00Z",
        created_at: "2026-04-27T08:00:00Z",
        updated_at: "2026-04-27T08:00:00Z",
        has_api_key: false,
        secret_ref: { store_id: "sqlcipher_inline", state: "missing" },
        is_default: true,
      },
    ],
    default: "ollama",
    secret_store_policy: {
      platform: "macos",
      availability: {
        state: "available",
        identity_strength: "unknown_or_unsigned",
      },
      default: {
        store_id: "sqlcipher_inline",
        native_store_id: "macos_keychain",
        native_available: true,
        warning:
          "Unsigned or ad-hoc macOS builds keep AI keys in SQLCipher by default; Keychain is an explicit experimental move because prompts may appear again after rebuilds or identity changes.",
      },
    },
  },
  "ai.list_models": {
    provider: "ollama",
    models: [
      { id: "qwen3.6:35b", owned_by: "library" },
      { id: "llama3.3:70b", owned_by: "library" },
    ],
  },
  "ai.test_connection": {
    base_url: "http://localhost:11434/v1",
    model_count: 2,
    models: [
      { id: "qwen3.6:35b", owned_by: "library" },
      { id: "llama3.3:70b", owned_by: "library" },
    ],
  },
};

/**
 * Pre-canned AI chat stream for mock mode. Mimics what Ollama's
 * OpenAI-compat shim sends for current reasoning builds (Qwen3, Gemma
 * reasoning) and what OpenAI o1/o3 endpoints send: structured
 * `reasoning` deltas first, then visible `content` deltas — never both
 * in one stream. The inline `<think>...</think>` tag style used by
 * DeepSeek-R1 / QwQ is covered by `lib/thinkParser.test.ts` rather than
 * mixed into this fixture, so the mock matches one realistic provider
 * shape instead of conflating two.
 */
export const MOCK_AI_CHAT_STREAM: {
  content?: string;
  reasoning?: string;
  delayMs?: number;
}[] = [
  { reasoning: "Preparing a formatting demo. ", delayMs: 20 },
  { reasoning: "Including headings, table, list, quote, and code.", delayMs: 60 },
  { content: "## Review snapshot\n\n", delayMs: 30 },
  {
    content:
      "This is a formatting demo for the assistant transcript. It should show relaxed paragraphs, headings, a CLI-style table, and command output without squeezing everything into a tiny bubble.\n\n",
    delayMs: 40,
  },
  { content: "### CLI-style table\n\n", delayMs: 30 },
  { content: "| Item | Status | Action |\n", delayMs: 30 },
  { content: "| --- | --- | --- |\n", delayMs: 20 },
  { content: "| Journals | Current | Run report exports |\n", delayMs: 30 },
  { content: "| Quarantine | Clear | Keep watching imports |\n", delayMs: 30 },
  { content: "| Rates | Needs review | Sync BTC-EUR cache |\n\n", delayMs: 30 },
  { content: "### Notes\n\n", delayMs: 30 },
  { content: "- Use program output for calculations.\n", delayMs: 30 },
  { content: "- Keep wallet data local.\n", delayMs: 30 },
  { content: "- Reprocess journals after imports.\n\n", delayMs: 30 },
  {
    content:
      "> Tables should be readable and scroll horizontally when needed.\n\n",
    delayMs: 40,
  },
  {
    content: "```bash\nkassiber reports tax-summary --machine\n```\n",
    delayMs: 50,
  },
];
