services:
  bitcoind:
    image: ${KASSIBER_REGTEST_BITCOIND_IMAGE:-bitcoin/bitcoin:27.1}
    command:
      -printtoconsole
      -regtest=1
      -server=1
      -txindex=1
      -fallbackfee=0.0002
      -rpcbind=0.0.0.0
      -rpcallowip=172.16.0.0/12
      -rpcauth=${KASSIBER_REGTEST_RPC_AUTH}
    ports:
      - "127.0.0.1:${KASSIBER_REGTEST_RPC_PORT:-18443}:18443"
    volumes:
      - bitcoind-regtest:/home/bitcoin/.bitcoin

volumes:
  bitcoind-regtest:
