//! Checks the decimal module against CPython's `decimal` and RP2Decimal.
//!
//! `data/decimal_vectors.txt` is generated by
//! `tax-engine/scripts/gen_decimal_vectors.py`; its header documents the line
//! format. Every line is checked, and every mismatch is reported at once.
//! Setting `KASSIBER_DECIMAL_VECTORS` to another generated file (a stress run)
//! checks that file as well.

use std::collections::BTreeMap;

use kassiber_tax_core::decimal::{Context, Decimal, DecimalError, Rounding};

const VECTORS: &str = include_str!("data/decimal_vectors.txt");

/// Fewest cases each operation must have, so a truncated file cannot pass.
const MIN_CASES_PER_OP: usize = 40;

const OPS: [&str; 14] = [
    "parse", "int", "str", "fmtf", "add", "sub", "mul", "div", "quantize", "neg", "abs", "plus",
    "cmp", "rp2",
];

fn rounding(name: &str) -> Option<Rounding> {
    Some(match name {
        "half_even" => Rounding::HalfEven,
        "half_up" => Rounding::HalfUp,
        "half_down" => Rounding::HalfDown,
        "down" => Rounding::Down,
        "up" => Rounding::Up,
        "ceiling" => Rounding::Ceiling,
        "floor" => Rounding::Floor,
        "05up" => Rounding::ZeroFiveUp,
        _ => return None,
    })
}

fn context(token: &str) -> Result<Context, String> {
    let (prec, mode) = token
        .split_once(':')
        .ok_or_else(|| format!("bad context {token:?}"))?;
    let prec = prec
        .parse::<u32>()
        .map_err(|_| format!("bad precision in {token:?}"))?;
    let mode = rounding(mode).ok_or_else(|| format!("bad rounding in {token:?}"))?;
    Ok(Context::new(prec, mode))
}

/// Reads a canonical operand, and checks that the Python-syntax parser and
/// the canonical writer agree with it.
fn operand(token: &str) -> Result<Decimal, String> {
    let value = Decimal::from_canonical(token)
        .map_err(|e| format!("operand {token:?} rejected by from_canonical: {e}"))?;
    if value.to_canonical() != token {
        return Err(format!(
            "operand {token:?} re-rendered as {:?}",
            value.to_canonical()
        ));
    }
    match token.parse::<Decimal>() {
        Ok(parsed) if parsed.same_representation(&value) => Ok(value),
        Ok(parsed) => Err(format!(
            "operand {token:?} parsed as {:?} by FromStr",
            parsed.to_canonical()
        )),
        Err(e) => Err(format!("operand {token:?} rejected by FromStr: {e}")),
    }
}

fn show(result: Result<Decimal, DecimalError>) -> String {
    match result {
        Ok(v) => v.to_canonical(),
        Err(e) => format!("!{}", e.name()),
    }
}

fn show_text(result: Result<String, DecimalError>) -> String {
    match result {
        Ok(s) => s,
        Err(e) => format!("!{}", e.name()),
    }
}

fn expect(actual: String, expected: &str) -> Result<(), String> {
    if actual == expected {
        return Ok(());
    }
    Err(format!("got {actual}"))
}

/// Expected results that are numbers must themselves round-trip.
fn expect_number(actual: String, expected: &str) -> Result<(), String> {
    if !expected.starts_with('!') {
        match Decimal::from_canonical(expected) {
            Ok(v) if v.to_canonical() == expected => {}
            _ => return Err(format!("expected value {expected:?} does not round-trip")),
        }
    }
    expect(actual, expected)
}

/// Decodes a parse input: `EMPTY` is the empty string, and `\u{<hex>}` is
/// one character (the generator escapes everything outside printable ASCII).
fn parse_input(token: &str) -> Result<String, String> {
    if token == "EMPTY" {
        return Ok(String::new());
    }
    let bad = || format!("bad escape in parse input {token:?}");
    let mut out = String::new();
    let mut rest = token;
    while let Some(start) = rest.find('\\') {
        out.push_str(&rest[..start]);
        let tail = rest[start..].strip_prefix("\\u{").ok_or_else(bad)?;
        let end = tail.find('}').ok_or_else(bad)?;
        let hex = &tail[..end];
        if hex.is_empty() || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(bad());
        }
        let c = u32::from_str_radix(hex, 16)
            .ok()
            .and_then(char::from_u32)
            .ok_or_else(bad)?;
        out.push(c);
        rest = &tail[end + 1..];
    }
    out.push_str(rest);
    Ok(out)
}

fn integer(text: &str) -> Result<Decimal, String> {
    if let Ok(v) = text.parse::<i128>() {
        return Ok(Decimal::from(v));
    }
    text.parse::<u128>()
        .map(Decimal::from)
        .map_err(|_| format!("integer {text:?} is outside i128 and u128"))
}

fn rp2_flags(x: &Decimal, y: &Decimal, ctx: &Context) -> String {
    let results = [
        x.rp2_eq(y, ctx),
        x.rp2_ne(y, ctx),
        x.rp2_gt(y, ctx),
        x.rp2_ge(y, ctx),
        x.rp2_lt(y, ctx),
        x.rp2_le(y, ctx),
    ];
    let mut flags = String::new();
    for r in &results {
        match r {
            Ok(true) => flags.push('1'),
            Ok(false) => flags.push('0'),
            Err(e) => {
                // RP2 raises the same error from every comparison.
                if results.iter().all(|other| other == r) {
                    return format!("!{}", e.name());
                }
                return format!("mixed {results:?}");
            }
        }
    }
    flags
}

fn check(fields: &[&str]) -> Result<(), String> {
    match fields {
        ["parse", input, expected] => {
            let input = parse_input(input)?;
            expect_number(show(input.parse::<Decimal>()), expected)
        }
        ["int", text, expected] => expect_number(integer(text)?.to_canonical(), expected),
        ["str", x, expected] => expect(operand(x)?.to_string(), expected),
        ["fmtf", x, expected] => expect(show_text(operand(x)?.to_fixed_string()), expected),
        [op @ ("add" | "sub" | "mul" | "div"), ctx, x, y, expected] => {
            let (ctx, x, y) = (context(ctx)?, operand(x)?, operand(y)?);
            let result = match *op {
                "add" => x.add(&y, &ctx),
                "sub" => x.sub(&y, &ctx),
                "mul" => x.mul(&y, &ctx),
                _ => x.div(&y, &ctx),
            };
            expect_number(show(result), expected)
        }
        ["quantize", ctx, x, exp, expected] => {
            let (ctx, x) = (context(ctx)?, operand(x)?);
            let exp = exp
                .parse::<i64>()
                .map_err(|_| format!("bad exponent {exp:?}"))?;
            expect_number(show(x.quantize(exp, &ctx)), expected)
        }
        [op @ ("neg" | "abs" | "plus"), ctx, x, expected] => {
            let (ctx, x) = (context(ctx)?, operand(x)?);
            let result = match *op {
                "neg" => x.neg(&ctx),
                "abs" => x.abs(&ctx),
                _ => x.plus(&ctx),
            };
            expect_number(show(result), expected)
        }
        ["cmp", x, y, expected] => {
            let (x, y) = (operand(x)?, operand(y)?);
            let actual = match x.cmp(&y) {
                std::cmp::Ordering::Less => "-1",
                std::cmp::Ordering::Equal => "0",
                std::cmp::Ordering::Greater => "1",
            };
            if (x == y) != (actual == "0") || (x < y) != (actual == "-1") {
                return Err("PartialEq/PartialOrd disagree with Ord".to_string());
            }
            expect(actual.to_string(), expected)
        }
        ["rp2", ctx, x, y, expected] => {
            let (ctx, x, y) = (context(ctx)?, operand(x)?, operand(y)?);
            expect(rp2_flags(&x, &y, &ctx), expected)
        }
        _ => Err("unrecognized line".to_string()),
    }
}

/// Checks every case in `text`, appending failures to `mismatches`. With
/// `require_coverage`, also fails when an operation has too few cases.
fn check_file(
    name: &str,
    text: &str,
    require_coverage: bool,
    mismatches: &mut Vec<String>,
) -> usize {
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for (index, line) in text.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split(' ').collect();
        *counts.entry(fields[0]).or_default() += 1;
        if let Err(problem) = check(&fields) {
            mismatches.push(format!("{name}:{}: {line}\n    {problem}", index + 1));
        }
    }
    for op in OPS {
        let n = counts.get(op).copied().unwrap_or(0);
        if require_coverage && n < MIN_CASES_PER_OP {
            mismatches.push(format!(
                "{name}: only {n} {op} cases; expected at least {MIN_CASES_PER_OP}"
            ));
        }
    }
    counts.values().sum()
}

#[test]
fn decimal_vectors_match_cpython() {
    let mut mismatches = Vec::new();
    let mut total = check_file("decimal_vectors.txt", VECTORS, true, &mut mismatches);
    if let Some(path) = std::env::var_os("KASSIBER_DECIMAL_VECTORS") {
        let extra = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.to_string_lossy()));
        total += check_file(&path.to_string_lossy(), &extra, false, &mut mismatches);
    }
    assert!(
        mismatches.is_empty(),
        "{} of {total} decimal vectors failed:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
