//! Checks the engine against RP2-oracle fixtures.
//!
//! `data/generic_fixtures.json` is generated by
//! `tax-engine/scripts/gen_engine_fixtures.py`: each case is an engine request
//! and the response RP2 gives for the same input. Every case runs, and every
//! differing field is reported by case and path. Setting
//! `KASSIBER_ENGINE_FIXTURES` to another generated file (a stress run) checks
//! that file as well.

use std::collections::BTreeMap;

use kassiber_tax_core::{check_entry, compute};
use serde_json::Value;

const FIXTURES: &str = include_str!("data/generic_fixtures.json");

/// Fewest cases of each kind, so a truncated file cannot pass.
const MIN_CASES: [(&str, usize); 4] = [
    ("compute:ok", 300),
    ("compute:error", 40),
    ("check_entry:ok", 150),
    ("check_entry:error", 60),
];

/// Most mismatches printed; all are counted.
const MAX_REPORTED: usize = 200;

fn diff(path: &str, expected: &Value, actual: &Value, out: &mut Vec<String>) {
    match (expected, actual) {
        (Value::Object(expected), Value::Object(actual)) => {
            for (key, value) in expected {
                let path = format!("{path}.{key}");
                match actual.get(key) {
                    Some(actual) => diff(&path, value, actual, out),
                    None => out.push(format!("{path}: missing")),
                }
            }
            for key in actual.keys().filter(|key| !expected.contains_key(*key)) {
                out.push(format!("{path}.{key}: unexpected field"));
            }
        }
        (Value::Array(expected), Value::Array(actual)) => {
            if expected.len() != actual.len() {
                out.push(format!(
                    "{path}: expected {} items, got {}",
                    expected.len(),
                    actual.len()
                ));
            }
            for (index, (expected, actual)) in expected.iter().zip(actual).enumerate() {
                diff(&format!("{path}[{index}]"), expected, actual, out);
            }
        }
        _ if expected == actual => {}
        _ => out.push(format!("{path}: expected {expected}, got {actual}")),
    }
}

/// The result of running every case of one fixture document.
struct Outcome {
    /// Cases per `operation:ok` or `operation:error`.
    counts: BTreeMap<String, usize>,
    total: usize,
    differing: usize,
    /// Every differing field, as `case: path: difference`.
    mismatches: Vec<String>,
}

impl Outcome {
    fn assert_clean(&self, label: &str) {
        let shown: Vec<&str> = self
            .mismatches
            .iter()
            .take(MAX_REPORTED)
            .map(String::as_str)
            .collect();
        assert!(
            self.mismatches.is_empty(),
            "{label}: {} of {} cases differ from RP2 ({} fields):\n{}",
            self.differing,
            self.total,
            self.mismatches.len(),
            shown.join("\n")
        );
    }
}

fn check_document(text: &str) -> Outcome {
    let document: Value = serde_json::from_str(text).expect("fixture file is JSON");
    let cases = document["cases"]
        .as_array()
        .expect("fixture file has cases");
    let mut outcome = Outcome {
        counts: BTreeMap::new(),
        total: cases.len(),
        differing: 0,
        mismatches: Vec::new(),
    };
    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let operation = case["operation"].as_str().expect("case operation");
        let request = serde_json::to_string(&case["request"]).expect("request serializes");
        let response = match operation {
            "compute" => compute(&request),
            "check_entry" => check_entry(&request),
            other => panic!("{name}: unknown operation {other}"),
        };
        let actual: Value = serde_json::from_str(&response).expect("engine response is JSON");
        let expected = &case["expected"];
        let result = if expected["ok"] == Value::Bool(true) {
            "ok"
        } else {
            "error"
        };
        *outcome
            .counts
            .entry(format!("{operation}:{result}"))
            .or_default() += 1;
        let mut differences = Vec::new();
        diff("", expected, &actual, &mut differences);
        if !differences.is_empty() {
            outcome.differing += 1;
            outcome
                .mismatches
                .extend(differences.into_iter().map(|d| format!("{name}: {d}")));
        }
    }
    outcome
}

#[test]
fn engine_matches_rp2_fixtures() {
    let outcome = check_document(FIXTURES);
    for (kind, minimum) in MIN_CASES {
        let count = outcome.counts.get(kind).copied().unwrap_or(0);
        assert!(
            count >= minimum,
            "only {count} {kind} cases (want {minimum}); counts {:?}",
            outcome.counts
        );
    }
    outcome.assert_clean("generic_fixtures.json");
}

#[test]
fn engine_matches_extra_fixtures() {
    let Some(path) = std::env::var_os("KASSIBER_ENGINE_FIXTURES") else {
        return;
    };
    let text = std::fs::read_to_string(&path).expect("KASSIBER_ENGINE_FIXTURES is readable");
    check_document(&text).assert_clean(&path.to_string_lossy());
}

#[test]
fn differences_are_reported_by_path() {
    let expected: Value = serde_json::json!({"a": [1, {"b": "x"}], "c": true});
    let actual: Value = serde_json::json!({"a": [1, {"b": "y"}, 3], "d": null});
    let mut out = Vec::new();
    diff("", &expected, &actual, &mut out);
    assert_eq!(
        out,
        vec![
            ".a: expected 2 items, got 3",
            ".a[1].b: expected \"x\", got \"y\"",
            ".c: missing",
            ".d: unexpected field",
        ]
    );
}
