//! Checks the engine against RP2-oracle fixtures.
//!
//! Both files are generated by `tax-engine/scripts/gen_engine_fixtures.py`.
//! In `data/generic_fixtures.json` each case is an engine request and the
//! response RP2 gives for the same input. In `data/at_fixtures.json` each
//! scenario is one adapter run over every asset of a book (moving averages
//! and Austria): its `validate`, `compute_multi`, and per-asset `compute`
//! steps, each with RP2's result. Every case runs, and every differing field
//! is reported by case and path. Setting `KASSIBER_ENGINE_FIXTURES` or
//! `KASSIBER_AT_FIXTURES` to another generated file (a stress run) checks
//! that file as well.

use std::collections::BTreeMap;

use kassiber_tax_core::{check_entry, compute};
use serde_json::Value;

const FIXTURES: &str = include_str!("data/generic_fixtures.json");
const AT_FIXTURES: &str = include_str!("data/at_fixtures.json");

/// Fewest cases of each kind, so a truncated file cannot pass.
const MIN_CASES: [(&str, usize); 4] = [
    ("compute:ok", 300),
    ("compute:error", 40),
    ("check_entry:ok", 150),
    ("check_entry:error", 60),
];

/// Fewest Austrian steps and rows of each kind, so a truncated file cannot
/// pass.
const MIN_AT_STEPS: [(&str, usize); 16] = [
    ("scenarios", 470),
    ("validate:ok", 400),
    ("validate:error", 15),
    ("compute_multi:handled", 55),
    ("compute_multi:declined", 300),
    ("compute_multi:error", 20),
    ("compute:ok", 330),
    ("compute:error", 30),
    ("category:alt_spekulation", 400),
    ("category:alt_taxfree", 40),
    ("category:neu_gain", 180),
    ("category:neu_loss", 180),
    ("category:neu_swap", 130),
    ("category:income_general", 70),
    ("category:income_capital_yield", 65),
    ("category:error", 8),
];

/// Most mismatches printed; all are counted.
const MAX_REPORTED: usize = 200;

fn diff(path: &str, expected: &Value, actual: &Value, out: &mut Vec<String>) {
    match (expected, actual) {
        (Value::Object(expected), Value::Object(actual)) => {
            for (key, value) in expected {
                let path = format!("{path}.{key}");
                match actual.get(key) {
                    Some(actual) => diff(&path, value, actual, out),
                    None => out.push(format!("{path}: missing")),
                }
            }
            for key in actual.keys().filter(|key| !expected.contains_key(*key)) {
                out.push(format!("{path}.{key}: unexpected field"));
            }
        }
        (Value::Array(expected), Value::Array(actual)) => {
            if expected.len() != actual.len() {
                out.push(format!(
                    "{path}: expected {} items, got {}",
                    expected.len(),
                    actual.len()
                ));
            }
            for (index, (expected, actual)) in expected.iter().zip(actual).enumerate() {
                diff(&format!("{path}[{index}]"), expected, actual, out);
            }
        }
        _ if expected == actual => {}
        _ => out.push(format!("{path}: expected {expected}, got {actual}")),
    }
}

/// The result of running every case of one fixture document.
struct Outcome {
    /// Cases per `operation:ok` or `operation:error`.
    counts: BTreeMap<String, usize>,
    total: usize,
    differing: usize,
    /// Every differing field, as `case: path: difference`.
    mismatches: Vec<String>,
}

impl Outcome {
    fn assert_clean(&self, label: &str) {
        let shown: Vec<&str> = self
            .mismatches
            .iter()
            .take(MAX_REPORTED)
            .map(String::as_str)
            .collect();
        assert!(
            self.mismatches.is_empty(),
            "{label}: {} of {} cases differ from RP2 ({} fields):\n{}",
            self.differing,
            self.total,
            self.mismatches.len(),
            shown.join("\n")
        );
    }
}

fn check_document(text: &str) -> Outcome {
    let document: Value = serde_json::from_str(text).expect("fixture file is JSON");
    let cases = document["cases"]
        .as_array()
        .expect("fixture file has cases");
    let mut outcome = Outcome {
        counts: BTreeMap::new(),
        total: cases.len(),
        differing: 0,
        mismatches: Vec::new(),
    };
    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let operation = case["operation"].as_str().expect("case operation");
        let request = serde_json::to_string(&case["request"]).expect("request serializes");
        let response = match operation {
            "compute" => compute(&request),
            "check_entry" => check_entry(&request),
            other => panic!("{name}: unknown operation {other}"),
        };
        let actual: Value = serde_json::from_str(&response).expect("engine response is JSON");
        let expected = &case["expected"];
        let result = if expected["ok"] == Value::Bool(true) {
            "ok"
        } else {
            "error"
        };
        *outcome
            .counts
            .entry(format!("{operation}:{result}"))
            .or_default() += 1;
        let mut differences = Vec::new();
        diff("", expected, &actual, &mut differences);
        if !differences.is_empty() {
            outcome.differing += 1;
            outcome
                .mismatches
                .extend(differences.into_iter().map(|d| format!("{name}: {d}")));
        }
    }
    outcome
}

#[test]
fn engine_matches_rp2_fixtures() {
    let outcome = check_document(FIXTURES);
    for (kind, minimum) in MIN_CASES {
        let count = outcome.counts.get(kind).copied().unwrap_or(0);
        assert!(
            count >= minimum,
            "only {count} {kind} cases (want {minimum}); counts {:?}",
            outcome.counts
        );
    }
    outcome.assert_clean("generic_fixtures.json");
}

#[test]
fn engine_matches_extra_fixtures() {
    let Some(path) = std::env::var_os("KASSIBER_ENGINE_FIXTURES") else {
        return;
    };
    let text = std::fs::read_to_string(&path).expect("KASSIBER_ENGINE_FIXTURES is readable");
    check_document(&text).assert_clean(&path.to_string_lossy());
}

/// The request one step of a scenario sends: every asset, or only the
/// step's asset for `compute`.
fn step_request(scenario: &Value, step: &Value) -> String {
    let assets = match step["asset"].as_str() {
        None => scenario["assets"].clone(),
        Some(asset) => Value::Array(
            scenario["assets"]
                .as_array()
                .expect("scenario assets")
                .iter()
                .filter(|entry| entry["asset"] == asset)
                .cloned()
                .collect(),
        ),
    };
    serde_json::json!({
        "schema_version": 1,
        "operation": step["operation"],
        "country": scenario["country"],
        "method": scenario["method"],
        "assets": assets,
    })
    .to_string()
}

/// Counts what an Austrian step's expected response covers.
fn count_at_step(operation: &str, expected: &Value, counts: &mut BTreeMap<String, usize>) {
    let mut bump = |key: String| *counts.entry(key).or_default() += 1;
    if expected["ok"] != Value::Bool(true) {
        bump(format!("{operation}:error"));
        return;
    }
    match (operation, expected["handled"].as_bool()) {
        ("compute_multi", Some(true)) => bump("compute_multi:handled".to_owned()),
        ("compute_multi", _) => bump("compute_multi:declined".to_owned()),
        _ => bump(format!("{operation}:ok")),
    }
    for asset in expected["assets"].as_array().into_iter().flatten() {
        for row in asset["gain_losses"].as_array().into_iter().flatten() {
            if let Some(category) = row["at_category"].as_str() {
                bump(format!("category:{category}"));
            } else if row.get("at_category_error").is_some() {
                bump("category:error".to_owned());
            }
        }
    }
}

fn check_at_document(text: &str) -> Outcome {
    let document: Value = serde_json::from_str(text).expect("fixture file is JSON");
    let scenarios = document["scenarios"]
        .as_array()
        .expect("fixture file has scenarios");
    let mut outcome = Outcome {
        counts: BTreeMap::new(),
        total: 0,
        differing: 0,
        mismatches: Vec::new(),
    };
    outcome
        .counts
        .insert("scenarios".to_owned(), scenarios.len());
    for scenario in scenarios {
        let name = scenario["name"].as_str().expect("scenario name");
        for step in scenario["steps"].as_array().expect("scenario steps") {
            let operation = step["operation"].as_str().expect("step operation");
            let label = match step["asset"].as_str() {
                Some(asset) => format!("{name}/{operation}/{asset}"),
                None => format!("{name}/{operation}"),
            };
            let response = compute(&step_request(scenario, step));
            let actual: Value = serde_json::from_str(&response).expect("engine response is JSON");
            let expected = &step["expected"];
            count_at_step(operation, expected, &mut outcome.counts);
            outcome.total += 1;
            let mut differences = Vec::new();
            diff("", expected, &actual, &mut differences);
            if !differences.is_empty() {
                outcome.differing += 1;
                outcome
                    .mismatches
                    .extend(differences.into_iter().map(|d| format!("{label}: {d}")));
            }
        }
    }
    outcome
}

#[test]
fn engine_matches_rp2_at_fixtures() {
    let outcome = check_at_document(AT_FIXTURES);
    outcome.assert_clean("at_fixtures.json");
    for (kind, minimum) in MIN_AT_STEPS {
        let count = outcome.counts.get(kind).copied().unwrap_or(0);
        assert!(
            count >= minimum,
            "only {count} {kind} (want {minimum}); counts {:?}",
            outcome.counts
        );
    }
}

#[test]
fn engine_matches_extra_at_fixtures() {
    let Some(path) = std::env::var_os("KASSIBER_AT_FIXTURES") else {
        return;
    };
    let text = std::fs::read_to_string(&path).expect("KASSIBER_AT_FIXTURES is readable");
    check_at_document(&text).assert_clean(&path.to_string_lossy());
}

#[test]
fn differences_are_reported_by_path() {
    let expected: Value = serde_json::json!({"a": [1, {"b": "x"}], "c": true});
    let actual: Value = serde_json::json!({"a": [1, {"b": "y"}, 3], "d": null});
    let mut out = Vec::new();
    diff("", &expected, &actual, &mut out);
    assert_eq!(
        out,
        vec![
            ".a: expected 2 items, got 3",
            ".a[1].b: expected \"x\", got \"y\"",
            ".c: missing",
            ".d: unexpected field",
        ]
    );
}
