import { useTranslation } from "react-i18next";
import type { BalanceRow, Reports } from "./model";

const panelClass = "rounded-lg border bg-card p-4";

export function FinancialReports({ reports, money }: { reports: Reports; money: (value: string) => string }) {
  const { t } = useTranslation("accountingReview");
  const table = (rows: BalanceRow[], turnover: boolean) => <div className="overflow-x-auto"><table className="w-full min-w-[400px] text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="pb-2 text-left">{t("account")}</th>{turnover && <><th className="pb-2 text-right">{t("debit")}</th><th className="pb-2 text-right">{t("credit")}</th></>}<th className="pb-2 text-right">{t("balance")}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.account_code} className="border-b last:border-0"><td className="py-2">{row.account_code} · {row.name}</td>{turnover && <><td className="text-right font-mono">{money(row.debit_minor)}</td><td className="text-right font-mono">{money(row.credit_minor)}</td></>}<td className="text-right font-mono">{money(row.balance_minor)}</td></tr>)}</tbody></table>{!rows.length && <p className="mt-3 text-sm text-muted-foreground">{t("empty")}</p>}</div>;
  return <div className="space-y-4"><section className={panelClass}><h2 className="mb-4 font-semibold">{t("trialBalance")}</h2>{table(reports.trial_balance.rows, true)}<div className="mt-3 flex justify-between border-t pt-3 text-sm"><span>{reports.trial_balance.balanced ? t("balanced") : t("unbalanced")}</span><span className="font-mono">{money(reports.trial_balance.debit_minor)} / {money(reports.trial_balance.credit_minor)}</span></div></section><section className={panelClass}><h2 className="mb-4 font-semibold">{t("profitLoss")}</h2>{table(reports.statements.profit_and_loss, false)}<p className="mt-3 flex justify-between border-t pt-3 text-sm font-medium"><span>{t("profit")}</span><span className="font-mono">{money(reports.statements.profit_minor)}</span></p></section><section className={panelClass}><h2 className="mb-4 font-semibold">{t("balanceSheet")}</h2>{table(reports.statements.balance_sheet, false)}<p className="mt-3 flex justify-between gap-3 border-t pt-3 text-sm"><span>{t("unappropriated")}</span><span className="font-mono">{money(reports.statements.unappropriated_result_minor)}</span></p></section></div>;
}
