import Foundation

/// The native equivalent of Tauri's renderer privilege boundary.
///
/// This list is intentionally explicit rather than derived from
/// `DaemonKind.allCases`: Python's `SUPPORTED_KINDS` also contains AI-only and
/// reveal/CLI capabilities that must never become reachable merely because a
/// new enum case was generated.
public enum DesktopDaemonAccessPolicy {
    public static let rendererAllowedKinds: Set<DaemonKind> = [
        .status,
        .uiEgressSnapshot,
        .uiOverviewSnapshot,
        .uiWorkspaceOverviewSnapshot,
        .uiTransactionsList,
        .uiTransactionsMetadataUpdate,
        .uiTransactionsResolve,
        .uiTransactionsGraph,
        .uiTransactionsHistory,
        .uiTransactionsHistoryRevert,
        .uiActivityHistory,
        .uiActivityStale,
        .uiAttachmentsList,
        .uiAttachmentsAdd,
        .uiAttachmentsCopy,
        .uiAttachmentsRename,
        .uiAttachmentsRemove,
        .uiAttachmentsOpen,
        .uiWalletsList,
        .uiBackendsList,
        .uiBackendsOptions,
        .uiBackendsPublicDefaults,
        .uiBackendsSettingsList,
        .uiBackendsCreate,
        .uiBackendsUpdate,
        .uiBackendsDelete,
        .uiBackendsSetDefault,
        .uiBackendsBitcoinrpcTest,
        .uiBackendsDetectCore,
        .uiBackendsElectrumTest,
        .uiBackendsHttpTest,
        .uiBackendsLightningTest,
        .uiProfilesSnapshot,
        .uiOnboardingComplete,
        .uiProfilesCreate,
        .uiProfilesRename,
        .uiProfilesUpdate,
        .uiProfilesSwitch,
        .uiProfilesResetData,
        .uiReportsCapitalGains,
        .uiReportsSummary,
        .uiReportsBalanceSheet,
        .uiReportsPortfolioSummary,
        .uiReportsBalanceHistory,
        .uiReportsTaxSummary,
        .uiReportsPrivacyHygiene,
        .uiReportsPrivacyMirror,
        .uiReportsPsbtPrivacy,
        .uiReportsExitTaxPreview,
        .uiReportsExportExitTaxPdf,
        .uiReportsExportExitTaxXlsx,
        .uiReportsExportPdf,
        .uiReportsExportSummaryPdf,
        .uiReportsExportCsv,
        .uiReportsExportXlsx,
        .uiReportsExportCapitalGainsCsv,
        .uiReportsExportAustrianE1kvPdf,
        .uiReportsExportAustrianE1kvXlsx,
        .uiReportsExportAustrianE1kvCsv,
        .uiReportsExportAuditPackage,
        .uiTransactionsExportCsv,
        .uiTransactionsExportXlsx,
        .uiTransactionsLedgerTemplate,
        .uiJournalsSnapshot,
        .uiJournalsEventsList,
        .uiJournalsQuarantine,
        .uiJournalsTransfersList,
        .uiJournalsProcess,
        .uiTransfersSuggest,
        .uiTransfersList,
        .uiTransfersPayoutsList,
        .uiTransfersPayoutsCreate,
        .uiTransfersPayoutsDelete,
        .uiTransfersPair,
        .uiTransfersUnpair,
        .uiTransfersUpdate,
        .uiTransfersBulkPair,
        .uiTransfersDismiss,
        .uiTransfersRulesList,
        .uiTransfersRulesCreate,
        .uiTransfersRulesDelete,
        .uiTransfersRulesSetEnabled,
        .uiTransfersRulesApply,
        .uiSavedViewsList,
        .uiSavedViewsCreate,
        .uiSavedViewsDelete,
        .uiRatesSummary,
        .uiRatesCoverage,
        .uiRatesKrakenCsvImport,
        .uiRatesLatest,
        .uiRatesRebuild,
        .uiMaintenanceSettings,
        .uiMaintenanceConfigure,
        .uiMaintenanceRun,
        .uiSyncStatus,
        .uiSyncEnable,
        .uiSyncDisable,
        .uiSyncTransportsList,
        .uiSyncTransportsConfigure,
        .uiSyncTransportsDelete,
        .uiSyncPush,
        .uiSyncPull,
        .uiSyncJoinRequest,
        .uiSyncInvite,
        .uiSyncJoin,
        .uiSyncMembersList,
        .uiSyncMembersRevoke,
        .uiSyncDevicesList,
        .uiSyncDevicesRevoke,
        .uiSyncConflictsList,
        .uiSyncConflictsResolve,
        .uiWorkspaceHealth,
        .uiWorkspaceFreshnessRun,
        .uiAuditEvidenceSummary,
        .uiWorkspaceCreate,
        .uiWorkspaceRename,
        .uiWorkspaceDelete,
        .uiProjectsList,
        .uiProjectsCreate,
        .uiProjectsSelect,
        .uiSecretsInit,
        .uiSecretsChangePassphrase,
        .uiNextActions,
        .uiReviewBadges,
        .uiWalletsUtxos,
        .uiPrivacyHygieneSnapshot,
        .uiLoansList,
        .uiLoansLink,
        .uiLoansMark,
        .uiLoansUnmark,
        .uiWalletsCreate,
        .uiWalletsImportFile,
        .uiWalletsImportSamourai,
        .uiWalletsLedgerPreview,
        .uiWalletsPreviewDescriptor,
        .uiWalletsDetectScriptTypes,
        .uiWalletsIdentify,
        .uiWalletsIdentifyOnchain,
        .uiConnectionsSources,
        .uiConnectionsBtcpayCreate,
        .uiConnectionsBullbitcoinWalletCreate,
        .uiConnectionsBtcpayDiscover,
        .uiConnectionsBtcpayTest,
        .uiConnectionsNodeSnapshot,
        .uiReportsLightningProfitability,
        .uiMetadataBip329Preview,
        .uiMetadataBip329Import,
        .uiMetadataBip329Export,
        .uiWalletsUpdate,
        .uiWalletsDelete,
        .uiWalletsSync,
        .uiFreshnessStatus,
        .uiFreshnessConfigure,
        .uiFreshnessRun,
        .uiFreshnessCancel,
        .uiFreshnessPause,
        .uiFreshnessResume,
        .walletsRevealDescriptor,
        .daemonLock,
        .daemonUnlock,
        .aiProvidersList,
        .aiProvidersGet,
        .aiProvidersCreate,
        .aiProvidersUpdate,
        .aiProvidersSetApiKey,
        .aiProvidersMoveApiKey,
        .aiProvidersDelete,
        .aiProvidersSetDefault,
        .aiProvidersClearDefault,
        .aiProvidersAcknowledge,
        .aiListModels,
        .aiTestConnection,
        .aiChat,
        .aiChatCancel,
        .aiToolCallConsent,
        .uiChatSessionsList,
        .uiChatSessionsGet,
        .uiChatSessionsDelete,
        .uiChatSessionsClear,
        .uiChatHistoryConfigure,
        .uiSourceFundsPreview,
        .uiSourceFundsCasesSave,
        .uiSourceFundsCasesList,
        .uiSourceFundsSourcesList,
        .uiSourceFundsSourcesCreate,
        .uiSourceFundsSourcesAttach,
        .uiSourceFundsLinksList,
        .uiSourceFundsLinksCreate,
        .uiSourceFundsLinksReview,
        .uiSourceFundsLinksBulkReview,
        .uiSourceFundsLinksAttach,
        .uiSourceFundsSuggest,
        .uiSourceFundsAssemble,
        .uiSourceFundsEvidenceList,
        .uiSourceFundsExportPdf,
        .uiSourceFundsExportBundle,
        .uiSourceFundsCoverage,
        .uiSourceFundsRecipientsList,
        .uiSourceFundsRecipientsCreate,
        .uiSourceFundsRecipientsUpdate,
        .uiSourceFundsRecipientsDelete,
        .uiBtcpayProvenanceSync,
        .uiBtcpayProvenanceList,
        .uiBtcpayProvenanceSuggest,
        .uiBtcpayProvenanceLinks,
        .uiBtcpayProvenanceReview,
        .uiTransactionsCommercialContext,
        .uiDocumentsList,
        .uiDocumentsCreate,
        .uiDocumentsAttach,
        .uiLogsSnapshot,
    ]

    /// Model calls and live tool-consent controls. Provider CRUD and encrypted
    /// chat-history privacy controls are intentionally not runtime-gated.
    public static let aiRuntimeKinds: Set<DaemonKind> = [
        .aiListModels,
        .aiTestConnection,
        .aiChat,
        .aiChatCancel,
        .aiToolCallConsent,
    ]

    /// Tool envelopes presented by the native assistant's generic tool card.
    /// These are not substitute direct renderer privileges: four are AI-only
    /// daemon kinds and the remaining results are reachable only when
    /// `ai.chat` executes an audited tool (with consent for mutations). Keeping
    /// the list explicit lets the parity checker distinguish real feature call
    /// sites from tool-result display.
    public static let aiToolResultPresentationKinds: Set<DaemonKind> = [
        .uiAuditChangesSinceLastAnswer,
        .uiBackendsList,
        .uiJournalsQuarantine,
        .uiJournalsTransfersList,
        .uiMaintenanceConfigure,
        .uiMaintenanceRun,
        .uiMaintenanceSettings,
        .uiNextActions,
        .uiOverviewSnapshot,
        .uiRatesCoverage,
        .uiRatesSummary,
        .uiReportBlockers,
        .uiReportsBalanceHistory,
        .uiReportsBalanceSheet,
        .uiReportsPortfolioSummary,
        .uiReportsSummary,
        .uiReportsTaxSummary,
        .uiTransactionsExtremes,
        .uiTransactionsList,
        .uiTransactionsSearch,
        .uiWalletsList,
        .uiWorkspaceHealth,
    ]

    /// AI catalog reads intentionally excluded from the renderer invoke
    /// allowlist. They may appear inside `ai.chat.tool_result` only.
    public static let aiOnlyToolResultKinds: Set<DaemonKind> = [
        .uiAuditChangesSinceLastAnswer,
        .uiReportBlockers,
        .uiTransactionsExtremes,
        .uiTransactionsSearch,
    ]

    public static func denial(
        for kind: DaemonKind,
        aiFeaturesEnabled: Bool
    ) -> DaemonRecord? {
        guard rendererAllowedKinds.contains(kind) else {
            return error(
                code: "kind_not_allowed",
                message: "Daemon kind \(kind.rawValue) is not allowed by the native desktop shell.",
                hint: "Add the kind to the audited desktop allowlist before exposing it to the app UI.",
                kind: kind
            )
        }
        guard !aiRuntimeKinds.contains(kind) || aiFeaturesEnabled else {
            return error(
                code: "ai_features_disabled",
                message: "AI features are disabled in Settings.",
                hint: "Enable AI features in Settings before invoking AI runtime kinds.",
                kind: kind
            )
        }
        return nil
    }

    private static func error(
        code: String,
        message: String,
        hint: String,
        kind: DaemonKind
    ) -> DaemonRecord {
        DaemonRecord(
            kind: "error",
            data: ["kind": .string(kind.rawValue)],
            error: DaemonErrorPayload(
                code: code,
                message: message,
                hint: hint,
                details: ["kind": .string(kind.rawValue)],
                retryable: false
            )
        )
    }
}
