#!/usr/bin/env python3
"""Generate the Swift daemon-kind contract from Python source.

This deliberately parses source with ``ast`` instead of importing Kassiber.
Code generation therefore works in Xcode and on Linux without loading the
application, opening its database, or requiring optional runtime packages.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ImportedName:
    module: str
    name: str


def module_path(package_root: Path, module: str) -> Path:
    return package_root.joinpath(*module.split(".")).with_suffix(".py")


def assignments_and_imports(path: Path) -> tuple[dict[str, ast.AST], dict[str, ImportedName]]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    assignments: dict[str, ast.AST] = {}
    imports: dict[str, ImportedName] = {}
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            value = node.value
            if value is None:
                continue
            for target in targets:
                if isinstance(target, ast.Name):
                    assignments[target.id] = value
        elif isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                imports[alias.asname or alias.name] = ImportedName(node.module, alias.name)
    return assignments, imports


def string_sequence(
    expression: ast.AST,
    *,
    source_path: Path,
    package_root: Path,
    assignments: dict[str, ast.AST],
    imports: dict[str, ImportedName],
) -> list[str]:
    if isinstance(expression, (ast.Tuple, ast.List, ast.Set)):
        result: list[str] = []
        for item in expression.elts:
            if isinstance(item, ast.Starred):
                result.extend(
                    string_sequence(
                        item.value,
                        source_path=source_path,
                        package_root=package_root,
                        assignments=assignments,
                        imports=imports,
                    )
                )
            elif isinstance(item, ast.Constant) and isinstance(item.value, str):
                result.append(item.value)
            else:
                raise ValueError(f"unsupported value in {source_path}: {ast.dump(item)}")
        return result
    if isinstance(expression, ast.Name):
        if expression.id in assignments:
            return string_sequence(
                assignments[expression.id],
                source_path=source_path,
                package_root=package_root,
                assignments=assignments,
                imports=imports,
            )
        imported = imports.get(expression.id)
        if imported is not None:
            imported_path = module_path(package_root, imported.module.lstrip("."))
            imported_assignments, imported_imports = assignments_and_imports(imported_path)
            imported_expression = imported_assignments.get(imported.name)
            if imported_expression is None:
                raise ValueError(f"{imported.name} is not assigned in {imported_path}")
            return string_sequence(
                imported_expression,
                source_path=imported_path,
                package_root=package_root,
                assignments=imported_assignments,
                imports=imported_imports,
            )
    raise ValueError(f"unsupported sequence expression in {source_path}: {ast.dump(expression)}")


def swift_case(raw: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", raw) if word]
    if not words:
        raise ValueError(f"cannot form a Swift case for {raw!r}")
    name = words[0].lower() + "".join(word[:1].upper() + word[1:] for word in words[1:])
    if name[0].isdigit():
        name = "kind" + name[:1].upper() + name[1:]
    return name


def render(kinds: list[str], source_label: str) -> str:
    cases: list[str] = []
    seen: dict[str, str] = {}
    for raw in kinds:
        name = swift_case(raw)
        previous = seen.get(name)
        if previous is not None and previous != raw:
            raise ValueError(f"Swift case collision: {previous!r} and {raw!r} -> {name}")
        seen[name] = raw
        cases.append(f'    case {name} = "{raw}"')
    body = "\n".join(cases)
    return f'''// Generated by Scripts/generate_daemon_kinds.py from {source_label}.
// Do not edit. Run `python3 Scripts/generate_daemon_kinds.py`.

import Foundation

public enum DaemonKind: String, CaseIterable, Codable, Sendable {{
{body}
}}
'''


def find_repo_root(script: Path) -> Path:
    candidate = script.resolve().parents[2]
    if (candidate / "kassiber" / "daemon.py").is_file():
        return candidate
    raise FileNotFoundError("could not locate repository root from generator path")


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return True
    if check:
        print(f"generated file is stale: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo-root", type=Path)
    args = parser.parse_args()

    script = Path(__file__)
    repo_root = args.repo_root.resolve() if args.repo_root else find_repo_root(script)
    daemon_path = repo_root / "kassiber" / "daemon.py"
    assignments, imports = assignments_and_imports(daemon_path)
    expression = assignments.get("SUPPORTED_KINDS")
    if expression is None:
        raise ValueError(f"SUPPORTED_KINDS not found in {daemon_path}")
    kinds = string_sequence(
        expression,
        source_path=daemon_path,
        package_root=repo_root / "kassiber",
        assignments=assignments,
        imports=imports,
    )
    if len(kinds) != len(set(kinds)):
        raise ValueError("SUPPORTED_KINDS contains duplicate values")

    generated = repo_root / "ui-macos" / "Sources" / "KassiberDaemonKit" / "Generated" / "DaemonKind.generated.swift"
    manifest = repo_root / "ui-macos" / "Generated" / "DaemonKinds.generated.json"
    swift_ok = write_or_check(generated, render(kinds, "kassiber/daemon.py::SUPPORTED_KINDS"), args.check)
    json_ok = write_or_check(manifest, json.dumps(kinds, indent=2) + "\n", args.check)
    if not args.check:
        print(f"generated {len(kinds)} daemon kinds")
    return 0 if swift_ok and json_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
