#!/usr/bin/env python3
"""Generate CPython decimal test vectors for kassiber-tax-core's decimal module.

The Rust decimal type must match CPython's ``decimal`` module (libmpdec) bit
for bit, and RP2Decimal's fuzzy comparisons exactly. This script computes the
expected results with the real CPython module and the real RP2Decimal class.

Run it with the repository virtualenv, which provides RP2:

    .venv/bin/python tax-engine/scripts/gen_decimal_vectors.py

It writes tax-engine/core/tests/data/decimal_vectors.txt. The output depends
only on the fixed seed and the CPython/libmpdec version recorded in its header.
The line format is documented in that header (see HEADER below).

For a stress run, write a larger set elsewhere and point the Rust test at it:

    .venv/bin/python tax-engine/scripts/gen_decimal_vectors.py \
        --seed 7 --scale 20 --output /tmp/decimal_stress.txt
    KASSIBER_DECIMAL_VECTORS=/tmp/decimal_stress.txt \
        cargo test -p kassiber-tax-core --test decimal_vectors
"""

from __future__ import annotations

import argparse
import decimal
import operator
import random
import sys
import unicodedata
from decimal import Context, Decimal, DecimalException, localcontext
from pathlib import Path

from rp2.rp2_decimal import RP2Decimal

SEED = 20261001
OUTPUT = Path(__file__).resolve().parent.parent / "core" / "tests" / "data" / "decimal_vectors.txt"
MAX_BYTES = 1_000_000
SCALE = 1.0  # set by --scale

ROUNDINGS = {
    "half_even": decimal.ROUND_HALF_EVEN,
    "half_up": decimal.ROUND_HALF_UP,
    "half_down": decimal.ROUND_HALF_DOWN,
    "down": decimal.ROUND_DOWN,
    "up": decimal.ROUND_UP,
    "ceiling": decimal.ROUND_CEILING,
    "floor": decimal.ROUND_FLOOR,
    "05up": decimal.ROUND_05UP,
}
RP2_CTX = (32, "half_even")
OTHER_PRECS = [1, 2, 3, 5, 9, 16, 28, 32, 34, 50]
ETINY_32 = -999999 - 32 + 1
MIN_ETINY = decimal.MIN_ETINY
MAX_EMAX = decimal.MAX_EMAX

HEADER = f"""\
# CPython decimal vectors for kassiber-tax-core's decimal module.
# Generated by tax-engine/scripts/gen_decimal_vectors.py (seed {{seed}}); do not edit.
# Python {sys.version.split()[0]}, decimal {decimal.__version__}, libmpdec {decimal.__libmpdec_version__},
# Unicode {unicodedata.unidata_version}.
#
# One case per line, fields separated by single spaces; '#' starts a comment.
# Numbers use the lossless canonical form [-]<digits>E<exp> (e.g. -12345E-3).
# <ctx> is <prec>:<rounding>; rounding is one of
#   half_even half_up half_down down up ceiling floor 05up
# with CPython's default Emin/Emax, clamp 0, and traps
# InvalidOperation, DivisionByZero, Overflow.
# A result starting with '!' is the expected error, e.g. !DivisionByZero.
# NonFinite means CPython parsed an infinity or NaN.
#
#   parse <input> <result>          Decimal(input); EMPTY stands for '', and
#                                   \\u{{<hex>}} for one character: every
#                                   character outside printable ASCII, and
#                                   the backslash, is escaped. No input has
#                                   surrounding whitespace, which CPython
#                                   strips and the Rust parser rejects.
#   int <integer> <result>          Decimal(int)
#   str <x> <text>                  str(x)
#   fmtf <x> <text>                 format(x, 'f')
#   add|sub|mul|div <ctx> <x> <y> <result>
#                                   x + y, x - y, x * y, x / y under ctx
#   quantize <ctx> <x> <exp> <result>
#                                   x.quantize(Decimal('1E<exp>')) under ctx
#   neg|abs|plus <ctx> <x> <result> -x, abs(x), +x under ctx
#   cmp <x> <y> <-1|0|1>            exact comparison
#   rp2 <ctx> <x> <y> <flags>       RP2Decimal ==, !=, >, >=, <, <= under
#                                   ctx as six 0/1 digits, or one !error
"""


def scaled(count: int) -> range:
    """Repetitions of a generated case; --scale multiplies them for stress runs."""
    return range(max(1, round(count * SCALE)))


def make_context(ctx: tuple[int, str]) -> Context:
    prec, rounding = ctx
    return Context(
        prec=prec,
        rounding=ROUNDINGS[rounding],
        traps=[decimal.InvalidOperation, decimal.DivisionByZero, decimal.Overflow],
    )


def ctx_token(ctx: tuple[int, str]) -> str:
    return f"{ctx[0]}:{ctx[1]}"


def canon(x: Decimal) -> str:
    sign, digits, exp = x.as_tuple()
    return ("-" if sign else "") + "".join(map(str, digits)) + "E" + str(exp)


def mk(sign: int, coeff: int, exp: int) -> Decimal:
    return Decimal((sign, tuple(int(c) for c in str(coeff)), exp))


SIGNAL_ORDER = [
    decimal.ConversionSyntax,
    decimal.DivisionUndefined,
    decimal.DivisionByZero,
    decimal.Overflow,
    decimal.InvalidOperation,
]


def err_name(exc: DecimalException) -> str:
    signals = exc.args[0] if exc.args and isinstance(exc.args[0], list) else [type(exc)]
    if len(signals) != 1:
        raise RuntimeError(f"unexpected signal list {signals!r}")
    for cls in SIGNAL_ORDER:
        if signals[0] is cls:
            return cls.__name__
    raise RuntimeError(f"unexpected signal {signals!r}")


def outcome(fn) -> str:
    try:
        result = fn()
    except DecimalException as exc:
        return "!" + err_name(exc)
    return canon(result)


def escape(s: str) -> str:
    """Spells every character outside printable ASCII, and the backslash, as \\u{<hex>}."""
    return "".join(ch if "!" <= ch <= "~" and ch != "\\" else f"\\u{{{ord(ch):X}}}" for ch in s)


class Writer:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.seen: set[str] = set()

    def emit(self, *fields: str) -> None:
        for field in fields:
            if not field or any(ch.isspace() for ch in field):
                raise ValueError(f"bad field {field!r}")
        line = " ".join(fields)
        if line not in self.seen:
            self.seen.add(line)
            self.lines.append(line)

    def section(self, title: str) -> None:
        self.lines.append(f"# {title}")

    # Operations, computed exactly as RP2 does: operators under a local context.
    def binary(self, op: str, ctx: tuple[int, str], x: Decimal, y: Decimal) -> None:
        fn = {"add": operator.add, "sub": operator.sub, "mul": operator.mul, "div": operator.truediv}[op]

        def run() -> Decimal:
            with localcontext(make_context(ctx)):
                return fn(x, y)

        self.emit(op, ctx_token(ctx), canon(x), canon(y), outcome(run))

    def quantize(self, ctx: tuple[int, str], x: Decimal, exp: int) -> None:
        def run() -> Decimal:
            with localcontext(make_context(ctx)):
                return x.quantize(Decimal((0, (1,), exp)))

        self.emit("quantize", ctx_token(ctx), canon(x), str(exp), outcome(run))

    def unary(self, op: str, ctx: tuple[int, str], x: Decimal) -> None:
        fn = {"neg": operator.neg, "abs": operator.abs, "plus": operator.pos}[op]

        def run() -> Decimal:
            with localcontext(make_context(ctx)):
                return fn(x)

        self.emit(op, ctx_token(ctx), canon(x), outcome(run))

    def cmp(self, x: Decimal, y: Decimal) -> None:
        self.emit("cmp", canon(x), canon(y), str((x > y) - (x < y)))

    def rp2(self, ctx: tuple[int, str], x: Decimal, y: Decimal) -> None:
        results = []
        with localcontext(make_context(ctx)):
            a, b = RP2Decimal(x), RP2Decimal(y)
            for op in (operator.eq, operator.ne, operator.gt, operator.ge, operator.lt, operator.le):
                try:
                    results.append("1" if op(a, b) else "0")
                except DecimalException as exc:
                    results.append("!" + err_name(exc))
        errors = {r for r in results if r.startswith("!")}
        if errors:
            if len(errors) != 1 or len(results) != 6 or not all(r.startswith("!") for r in results):
                raise RuntimeError(f"mixed RP2 outcome {results!r}")
            flags = errors.pop()
        else:
            flags = "".join(results)
        self.emit("rp2", ctx_token(ctx), canon(x), canon(y), flags)

    def text(self, x: Decimal) -> None:
        self.emit("str", canon(x), str(x))
        # Fixed-point text grows with the exponent; keep lines short.
        if -400 <= x.as_tuple().exponent <= 400:
            self.emit("fmtf", canon(x), format(x, "f"))

    def parse(self, s: str) -> None:
        if s != s.strip():
            raise ValueError(f"parse input {s!r} has surrounding whitespace")
        try:
            value = Decimal(s)
        except DecimalException as exc:
            result = "!" + err_name(exc)
        else:
            result = canon(value) if value.is_finite() else "!NonFinite"
        self.emit("parse", escape(s) if s else "EMPTY", result)


class Values:
    """Operand generators for the quantities Kassiber handles."""

    def __init__(self, r: random.Random) -> None:
        self.r = r

    def sign(self, negative_share: int = 3) -> int:
        return 1 if self.r.randrange(10) < negative_share else 0

    def digits(self, n: int) -> int:
        if n <= 0:
            return 0
        return self.r.randrange(10 ** (n - 1), 10**n)

    def crypto(self) -> Decimal:
        places = self.r.randint(8, 13)
        kind = self.r.randrange(4)
        if kind == 0:
            coeff = self.r.randrange(0, 21_000_000 * 10**places + 1)
        elif kind == 1:
            coeff = self.r.randrange(1, 10**places)
        elif kind == 2:
            coeff = self.r.randrange(1, 10**6) * 10 ** self.r.randint(0, places)
        else:
            coeff = self.r.randrange(1, 10 ** self.r.randint(1, 6))
        return mk(self.sign(), coeff, -places)

    def fiat(self) -> Decimal:
        places = self.r.randint(2, 20)
        if self.r.randrange(3) == 0:
            coeff = self.r.randrange(0, 10**12 * 10**places + 1)
        else:
            coeff = self.r.randrange(0, 10 ** self.r.randint(1, 8 + places))
        return mk(self.sign(), coeff, -places)

    def price(self) -> Decimal:
        sig = self.r.randint(1, 10)
        adjusted = self.r.randint(-8, 7)
        return mk(self.sign(1), self.digits(sig), adjusted - sig + 1)

    def rate(self) -> Decimal:
        sig = self.r.randint(20, 40)
        adjusted = self.r.randint(-12, 8)
        return mk(self.sign(2), self.digits(sig), adjusted - sig + 1)

    def long(self) -> Decimal:
        sig = self.r.randint(33, 60)
        return mk(self.sign(), self.digits(sig), self.r.randint(-45, 10))

    def tiny(self) -> Decimal:
        if self.r.randrange(12) == 0:
            return mk(self.sign(), self.digits(self.r.randint(1, 3)), MIN_ETINY)
        sig = self.r.randint(1, 40)
        return mk(self.sign(), self.digits(sig), self.r.randint(-1000062, -999950) - sig + 1)

    def huge(self) -> Decimal:
        if self.r.randrange(12) == 0:
            return mk(self.sign(), 1, MAX_EMAX)
        sig = self.r.randint(1, 34)
        adjusted = self.r.randint(999960, 1000002)
        return mk(self.sign(), self.digits(sig), adjusted - sig + 1)

    def zero(self) -> Decimal:
        exp = self.r.choice(
            list(range(-20, 21)) + [-1000040, ETINY_32, -999999, 999999, 1000005, MIN_ETINY, MAX_EMAX]
        )
        return mk(self.sign(5), 0, exp)

    def special(self) -> Decimal:
        n = self.r.randint(1, 40)
        kind = self.r.randrange(6)
        if kind == 0:
            coeff = 10**n - 1
        elif kind == 1:
            coeff = 10 ** (n - 1)
        elif kind == 2:
            coeff = 5 * 10 ** (n - 1)
        elif kind == 3:
            coeff = 10**n + 1
        elif kind == 4:
            coeff = 10 ** (n - 1) * 10 + 5
        else:
            coeff = self.r.choice([1, 2, 3, 7, 9, 11, 25, 125, 333, 999])
        return mk(self.sign(), coeff, self.r.randint(-40, 8) if n < 36 else self.r.randint(-60, 0))

    def any(self) -> Decimal:
        pick = self.r.randrange(100)
        if pick < 22:
            return self.crypto()
        if pick < 42:
            return self.fiat()
        if pick < 54:
            return self.price()
        if pick < 66:
            return self.rate()
        if pick < 76:
            return self.long()
        if pick < 81:
            return self.tiny()
        if pick < 86:
            return self.huge()
        if pick < 92:
            return self.zero()
        return self.special()


def pick_ctx(r: random.Random) -> tuple[int, str]:
    if r.randrange(10) < 6:
        return RP2_CTX
    return (r.choice(OTHER_PRECS), r.choice(list(ROUNDINGS)))


def all_contexts(precs: list[int]) -> list[tuple[int, str]]:
    return [(p, name) for p in precs for name in ROUNDINGS]


def gen_parse(w: Writer, r: random.Random) -> None:
    w.section("parse: hand-picked forms")
    literal = [
        "", "0", "-0", "+0", "00", "-00.000", ".5", "5.", "-.5", "+5.", "-0.00", "0.", ".0",
        "1E+5", "1e+5", "1E5", "1e-5", "1E-0", "1E+0", "-1E-00", "00012E1", "0.e1", ".0e1",
        "-.0", "+.0E-0", "12.3400", "0.000000000000000000000000000000000000001",
        "123456789012345678901234567890123456789012345678901234567890",
        "21000000.0000000000000", "-0.00000001", "1_000", "1__000", "_1000", "1000_",
        "1_0.0_1", "1.0_1", "1e1_0", "1_e10", "1._1", "1_.1", "+_1", "-_0", "1e_5", "1e5_",
        "1e-_5", "_", "__", "_._", "1E00000000000000000000000000005", "1E999999999999999999",
        "1E9999999999999999999", "1E-999999999999999999", "1E-9999999999999999999",
        "1E-1000000000000000000", "1E1000000000000000000", "0E-9999999999999999999999",
        "0E99999999999999999999999", "1.5E999999999999999999", "12E-999999999999999999",
        "0E-1999999999999999997", "0E-1999999999999999998", "-0E-1999999999999999997",
        "1E-1999999999999999997", "1E-1999999999999999998", "12E-1999999999999999998",
        "0E+999999999999999999", "0E+1000000000000000000", "0.001E+1000000000000000002",
        "0.00E-1999999999999999995", "0.00E-1999999999999999996", "1E9223372036854775807",
        "0E9223372036854775807", "0E9223372036854775808", "1E-9223372036854775808",
        "0E-9223372036854775809", "0.1E-1999999999999999996", "99E999999999999999998",
        "1E+999999", "1E+1000000", "1E-1000030", "1E-1000031", ".", "e5", "E5", "1e", "1E",
        "1e+", "1e-", "+", "-", "++1", "--1", "+-1", "1.2.3", "1..2", "..1", "1E+-5",
        "1E5.0", "1E5E5", "0x10", "1,5", "1/2", "1e1e", "e", "-e1", "Inf", "inf", "-Inf",
        "+inf", "Infinity", "-INFINITY", "infinit", "infinityy", "iNF", "In_f", "NaN", "nan",
        "-nan", "+NaN", "nan123", "NaN-1", "nan1.5", "sNaN", "-snan", "sNaN12", "snan_1",
        "nan_1", "-_nan", "nana", "N", "1nan", "1inf", "Inf1", "0e0", "-0e-0", "0e+0", "1_",
    ]
    for s in literal:
        w.parse(s)
    w.section("parse: generated forms")
    for _ in scaled(260):
        sign = r.choice(["", "", "+", "-"])
        lead = "0" * r.choice([0, 0, 0, 1, 3])
        int_part = lead + (str(r.randrange(10 ** r.randint(1, 25))) if r.randrange(4) else "")
        frac_part = ""
        point = ""
        if r.randrange(3):
            point = "."
            frac_part = "".join(str(r.randrange(10)) for _ in range(r.randint(0, 25)))
            frac_part += "0" * r.choice([0, 0, 2])
        exp_part = ""
        if r.randrange(2):
            marker = r.choice("eE")
            exp_sign = r.choice(["", "+", "-"])
            exp_digits = "0" * r.choice([0, 0, 2]) + str(r.randrange(10 ** r.randint(1, 7)))
            if r.randrange(25) == 0:
                exp_digits = str(r.randrange(10**17, 10**20))
            exp_part = marker + exp_sign + exp_digits
        s = sign + int_part + point + frac_part + exp_part
        if r.randrange(6) == 0:
            pos = r.randint(0, len(s))
            s = s[:pos] + "_" + s[pos:]
        if r.randrange(8) == 0 and s:
            pos = r.randrange(len(s))
            s = s[:pos] + r.choice(["+", "-", ".", "e", "x", "E", "1"]) + s[pos:]
        w.parse(s)


def gen_parse_unicode(w: Writer) -> None:
    """Unicode decimal digits, which CPython reads as ASCII digits, and their look-alikes.

    Every run of ten digits in the Unicode database appears, so the vectors
    check the Rust digit table entry by entry, along with the code points just
    outside each run. This section uses no randomness, so it leaves the
    generated values of every other section unchanged.
    """
    zeros = [cp for cp in range(0x80, sys.maxunicode + 1) if unicodedata.decimal(chr(cp), -1) == 0]

    def in_script(s: str, zero: int) -> str:
        return "".join(chr(zero + int(ch)) if "0" <= ch <= "9" else ch for ch in s)

    def parse_unless_stripped(s: str) -> None:
        # CPython strips surrounding whitespace; the Rust parser rejects it.
        if s == s.strip():
            w.parse(s)

    w.section(f"parse: every run of Unicode decimal digits (Unicode {unicodedata.unidata_version})")
    for i, zero in enumerate(zeros):
        d = [chr(zero + k) for k in range(10)]
        w.parse("".join(d))
        w.parse("-" + "".join(reversed(d)) + "." + d[5] + "E+" + d[1] + d[2])
        w.parse("1" + d[2] + "3." + d[0] + "e-" + d[4])
        w.parse(d[0] * 3 + "." + d[0] * 2)
        w.parse("-" + d[0])
        w.parse(d[1] + "_" + d[0] + "_" + d[0])
        w.parse(["nan", "sNaN", "-NaN"][i % 3] + d[i % 10] + d[(i + 3) % 10])
        w.parse("inf" + d[1])
        for cp in (zero - 1, zero + 10):
            ch = chr(cp)
            for s in (ch, "1" + ch, ch + "1", "1" + ch + "2", "1e" + ch, "nan" + ch):
                parse_unless_stripped(s)

    w.section("parse: Unicode digits in long, exponent-limit, and mixed-script forms")
    forms = [
        "123456789012345678901234567890123456789012345678901234567890", "21000000.0000000000000",
        "-0.00000001", "0.000000000000000000000000000000000000001", "1E999999999999999999",
        "1E1000000000000000000", "1E-1999999999999999997", "1E-1999999999999999998",
        "0E-1999999999999999998", "1E9223372036854775808", "99E999999999999999998", "1E+999999",
        "1E-1000031", "00012E1", "12.3400", "-.5", "5.", "+0E-0", "nan12", "sNaN00",
    ]
    for zero in (0x660, 0x6F0, 0x966, 0xFF10, 0x1D7F6, 0x1E950):
        for s in forms:
            w.parse(in_script(s, zero))
    for s in ("1٢３.०\U0001d7d75", "١E۲२", "-０.\U0001e950٠"):
        w.parse(s)

    w.section("parse: look-alikes that CPython rejects or ignores")
    lookalikes = [
        # Digits and numbers without a decimal value.
        "²", "1³", "¹", "⁰", "₁", "①", "ⅰ", "Ⅻ", "〇",
        "一", "零", "༪", "፩", "᧚", "\U00010107", "\U0001f100", "1½",
        # Signs, separators, and letters from other blocks.
        "1٫5", "1٬000", "1．5", "＋1", "－1", "−1", "–1",
        "﹣1", "1ｅ5", "1Ｅ5", "ｎａｎ", "Ｉｎｆ",
        "İnf", "ınf", "naɴ", "١٫٥", "١٪",
        # Combining marks, format characters, controls, and inner whitespace.
        "1́", "١ٰ", "1​2", "​1", "1​", "﻿1", "1﻿",
        "1 2", "1 2", "1　2", "- 1", "1e 5", "1 2", "1\x852",
        "1\x1c2", "1 2", "1\t2", "\x00", "1\x00", "\x001", "nan\x00", "1\x7f", "1\x80",
        "\U0010ffff", "1\U0010ffff", "�", "1\\2", "\\u{31}",
    ]
    for s in lookalikes:
        w.parse(s)


def gen_int(w: Writer, r: random.Random) -> None:
    w.section("int")
    values = [0, 1, -1, 9, 10, -10, 2**31 - 1, -(2**31), 2**32 - 1, 2**63 - 1, -(2**63), 2**64 - 1,
              10**18, 10**19, -(10**30), 2**127 - 1, -(2**127), 2**128 - 1, 21_000_000 * 10**8]
    for _ in scaled(24):
        values.append((-1) ** r.randrange(2) * r.randrange(10 ** r.randint(1, 38)))
    for v in values:
        w.emit("int", str(v), canon(Decimal(v)))


def gen_text(w: Writer, v: Values, r: random.Random) -> None:
    w.section("str and format 'f': notation boundaries")
    for ndig in range(1, 5):
        for exp in range(-12, 4):
            w.text(mk(0, v.digits(ndig), exp))
            if ndig == 1:
                w.text(mk(1, 0, exp))
    w.section("str and format 'f': generated values")
    for _ in scaled(420):
        w.text(v.any())


def gen_add_sub(w: Writer, v: Values, r: random.Random) -> None:
    w.section("add/sub: random operands")
    for _ in scaled(520):
        w.binary(r.choice(["add", "sub"]), pick_ctx(r), v.any(), v.any())
    w.section("add/sub: same-kind operands")
    for gen in (v.crypto, v.fiat, v.rate, v.long, v.tiny, v.huge, v.zero):
        for _ in scaled(26):
            w.binary(r.choice(["add", "sub"]), pick_ctx(r), gen(), gen())
    w.section("add/sub: rounding ties, near ties, and sticky tails at every rounding")
    for ctx in all_contexts([32, 9, 1]):
        prec = ctx[0]
        for _ in scaled(3):
            exp = r.randint(-20, 5)
            x = mk(v.sign(5), v.digits(prec), exp)
            tie = mk(v.sign(5), 5, exp - 1)
            w.binary("add", ctx, x, tie)
            w.binary("sub", ctx, x, tie)
            # Just below and just above half.
            w.binary("add", ctx, x, mk(tie.as_tuple().sign, 49999, exp - 5))
            w.binary("add", ctx, x, mk(tie.as_tuple().sign, 50001, exp - 5))
            # A far smaller operand only contributes a sticky tail.
            w.binary("add", ctx, x, mk(v.sign(5), 1, exp - r.randint(3, 80)))
            w.binary("sub", ctx, x, mk(v.sign(5), 7, exp - 1000))
            # A tie in the larger operand itself, nudged by a far smaller one.
            t = mk(v.sign(5), v.digits(prec) * 10 + 5, exp - 1)
            w.binary("add", ctx, t, mk(0, 1, exp - r.randint(40, 120)))
            w.binary("sub", ctx, t, mk(0, 1, exp - r.randint(40, 120)))
            w.binary("add", ctx, t, mk(v.sign(5), 0, exp - r.randint(1, 60)))
    w.section("add/sub: carries that lengthen the coefficient")
    for prec in (32, 28, 5):
        nines = 10**prec - 1
        for exp in (-31, -13, -8, 0, 3):
            for ctx in ((prec, "half_even"), (prec, "down"), (prec, "up"), (prec, "floor")):
                w.binary("add", ctx, mk(0, nines, exp), mk(0, 5, exp - 1))
                w.binary("add", ctx, mk(0, nines, exp), mk(0, 1, exp))
                w.binary("sub", ctx, mk(1, nines, exp), mk(0, 1, exp - 2))
                w.binary("add", ctx, mk(0, nines, exp), mk(0, 1, exp - 50))
            w.binary("sub", (prec, "half_even"), mk(0, 10**prec, exp), mk(0, 1, exp - 1))
            w.binary("sub", (prec, "half_even"), mk(0, 1, exp), mk(0, 1, exp - prec - 1))
    w.section("add/sub: zeros, exponent extremes, and subnormals")
    zeros = [mk(s, 0, e) for s in (0, 1) for e in (-13, 0, 5, ETINY_32 - 10, MAX_EMAX, 1000005)]
    for ctx in (RP2_CTX, (32, "floor"), (32, "ceiling"), (9, "down")):
        for a in zeros:
            for b in zeros[::2]:
                w.binary("add", ctx, a, b)
                w.binary("sub", ctx, a, b)
        for x in (mk(0, 1, 0), mk(1, 12345, -2), mk(0, 1, -1000000)):
            w.binary("add", ctx, x, mk(1, 0, -999999999))
            w.binary("sub", ctx, mk(0, 0, 999999), x)
        w.binary("sub", ctx, mk(0, 12345, -2), mk(0, 12345, -2))
        w.binary("add", ctx, mk(1, 12345, -2), mk(0, 1234500, -4))
    for _ in scaled(30):
        w.binary(r.choice(["add", "sub"]), pick_ctx(r), v.tiny(), v.tiny())
        w.binary(r.choice(["add", "sub"]), pick_ctx(r), v.huge(), v.any())
    for exp in (MAX_EMAX, 999999, 1000000):
        w.binary("add", RP2_CTX, mk(0, 1, exp), mk(0, 1, MIN_ETINY))
        w.binary("sub", RP2_CTX, mk(0, 1, exp), mk(0, 1, MIN_ETINY))
    w.binary("sub", RP2_CTX, mk(0, 1, 999999), mk(0, 1, -999999))
    w.binary("add", RP2_CTX, mk(0, 9, 999999), mk(0, 9, 999999))
    w.binary("add", RP2_CTX, mk(0, 1, 0), mk(0, 1, MIN_ETINY))
    w.binary("add", (32, "up"), mk(0, 1, 0), mk(0, 1, MIN_ETINY))
    w.binary("sub", (32, "down"), mk(0, 1, 0), mk(0, 1, MIN_ETINY))


def gen_mul(w: Writer, v: Values, r: random.Random) -> None:
    w.section("mul: random operands")
    for _ in scaled(560):
        w.binary("mul", pick_ctx(r), v.any(), v.any())
    w.section("mul: crypto amounts times prices and rates")
    for _ in scaled(120):
        w.binary("mul", pick_ctx(r), v.crypto(), r.choice([v.price, v.rate, v.fiat])())
    w.section("mul: exact rounding ties at every rounding")
    for ctx in all_contexts([32, 9, 2]):
        prec = ctx[0]
        found = 0
        attempts = 0
        while found < 4 and attempts < 200000:
            attempts += 1
            a = r.randint(1, prec + 1)
            b = max(1, prec + r.randint(1, 2) - a)
            x, y = v.digits(a), v.digits(b)
            product = x * y
            j = len(str(product)) - prec
            if j >= 1 and product % 10**j == 5 * 10 ** (j - 1):
                found += 1
                w.binary("mul", ctx, mk(v.sign(5), x, r.randint(-20, 5)), mk(v.sign(5), y, r.randint(-20, 5)))
    w.section("mul: carries and long products")
    for prec in (32, 9):
        nines = 10**prec - 1
        for ctx in ((prec, "half_even"), (prec, "down"), (prec, "ceiling")):
            w.binary("mul", ctx, mk(0, nines, -5), mk(0, nines, -5))
            w.binary("mul", ctx, mk(0, int("3" * prec + "4"), -prec), mk(0, 3, 0))
            w.binary("mul", ctx, mk(1, 10 ** (prec + 1) - 1, 0), mk(0, 1, 0))
            w.binary("mul", ctx, mk(0, 10 ** (prec + 1) - 5, -3), mk(1, 1, 0))
    w.section("mul: zeros, overflow, and underflow")
    for ctx in (RP2_CTX, (32, "floor"), (16, "up")):
        for x in (mk(0, 0, 0), mk(1, 0, -3), mk(0, 0, 999999), mk(1, 0, ETINY_32)):
            w.binary("mul", ctx, x, mk(1, 5, 3))
            w.binary("mul", ctx, x, x)
        w.binary("mul", ctx, mk(0, 1, 999999), mk(0, 10, 0))
        w.binary("mul", ctx, mk(0, 1, 500000), mk(1, 1, 499999))
        w.binary("mul", ctx, mk(0, 1, -999999), mk(0, 1, -999999))
        w.binary("mul", ctx, mk(0, 1, -999999), mk(0, 1, -20))
        w.binary("mul", ctx, mk(0, 123456789, -999999), mk(0, 1, -25))
        w.binary("mul", ctx, mk(1, 5, -1000030), mk(0, 1, -1))
        w.binary("mul", ctx, mk(0, 15, -1000031), mk(0, 1, 0))
        w.binary("mul", ctx, mk(0, 1, MIN_ETINY), mk(0, 1, MIN_ETINY))
        w.binary("mul", ctx, mk(0, 1, MAX_EMAX), mk(0, 1, MIN_ETINY))
    for _ in scaled(40):
        w.binary("mul", pick_ctx(r), v.tiny(), v.price())
        w.binary("mul", pick_ctx(r), v.huge(), v.price())


def gen_div(w: Writer, v: Values, r: random.Random) -> None:
    w.section("div: random operands")
    for _ in scaled(560):
        w.binary("div", pick_ctx(r), v.any(), v.any())
    w.section("div: fiat over crypto (prices) and fiat over fiat (rates)")
    for _ in scaled(120):
        w.binary("div", pick_ctx(r), v.fiat(), r.choice([v.crypto, v.fiat, v.price])())
    w.section("div: small exact and inexact quotients")
    for num in (1, 2, 3, 10, 22, 100, 1000, 12345):
        for den in (1, 2, 3, 4, 5, 7, 8, 16, 25, 81, 125, 1024):
            for ctx in (RP2_CTX, (3, "half_even"), (28, "down")):
                w.binary("div", ctx, mk(0, num, r.randint(-4, 2)), mk(r.randrange(2), den, r.randint(-4, 2)))
    w.section("div: exact quotients and the ideal exponent")
    for _ in scaled(160):
        y = v.digits(r.randint(1, 20))
        q = v.digits(r.randint(1, 36))
        x = q * y * 10 ** r.choice([0, 0, 1, 5])
        w.binary("div", pick_ctx(r), mk(v.sign(), x, r.randint(-30, 10)), mk(v.sign(), y, r.randint(-30, 10)))
    w.section("div: exact rounding ties, near ties, and carries at every rounding")
    for ctx in all_contexts([32, 9, 1]):
        prec = ctx[0]
        for _ in scaled(3):
            j = r.randint(1, 3)
            tie = v.digits(prec) * 10**j + 5 * 10 ** (j - 1)
            y = v.digits(r.randint(1, 25))
            ex, ey = r.randint(-20, 10), r.randint(-20, 10)
            sx, sy = v.sign(5), v.sign(5)
            w.binary("div", ctx, mk(sx, tie * y, ex), mk(sy, y, ey))
            w.binary("div", ctx, mk(sx, tie * y + 1, ex), mk(sy, y, ey))
            w.binary("div", ctx, mk(sx, tie * y - 1, ex), mk(sy, y, ey))
        for top in (10 ** (prec + 1) - 5, 10 ** (prec + 1) - 1, 10 ** (prec + 1) - 6):
            y = v.digits(r.randint(1, 10))
            w.binary("div", ctx, mk(0, top * y, -prec), mk(v.sign(5), y, 0))
    w.section("div: zeros, errors, overflow, and underflow")
    for ctx in (RP2_CTX, (32, "floor"), (5, "up")):
        for x in (mk(0, 0, 0), mk(1, 0, -3), mk(0, 0, 999999), mk(1, 1, 0), mk(0, 12345, -2)):
            for y in (mk(0, 0, 0), mk(1, 0, 5), mk(0, 3, 0), mk(1, 7, -2), mk(0, 1, -999999), mk(0, 1, 999999)):
                w.binary("div", ctx, x, y)
        w.binary("div", ctx, mk(0, 10, 0), mk(0, 1, -999999))
        w.binary("div", ctx, mk(0, 1, -999999), mk(0, 3, 0))
        w.binary("div", ctx, mk(0, 1, -999999), mk(0, 7, 25))
        w.binary("div", ctx, mk(0, 1, MIN_ETINY), mk(0, 1, MIN_ETINY))
        w.binary("div", ctx, mk(0, 1, MAX_EMAX), mk(0, 1, MAX_EMAX))
        w.binary("div", ctx, mk(0, 0, MAX_EMAX), mk(0, 1, MIN_ETINY))
    for _ in scaled(40):
        w.binary("div", pick_ctx(r), v.tiny(), v.price())
        w.binary("div", pick_ctx(r), v.price(), v.huge())
        w.binary("div", pick_ctx(r), v.long(), v.long())


def gen_quantize(w: Writer, v: Values, r: random.Random) -> None:
    w.section("quantize: 13 places (RP2's mask) on every kind of value")
    for _ in scaled(420):
        w.quantize(pick_ctx(r), v.any(), -13)
    w.section("quantize: fiat and crypto places")
    for _ in scaled(200):
        w.quantize(pick_ctx(r), v.any(), r.choice([-2, -8, -12, -14, -20, 0, 2, 5]))
    w.section("quantize: 13-place ties, near ties, and carries at every rounding")
    for ctx in all_contexts([32, 28]):
        for _ in scaled(2):
            c = v.digits(r.randint(1, 17))
            w.quantize(ctx, mk(v.sign(5), c * 10 + 5, -14), -13)
            w.quantize(ctx, mk(v.sign(5), c * 100 + 49, -15), -13)
            w.quantize(ctx, mk(v.sign(5), c * 100 + 51, -15), -13)
            w.quantize(ctx, mk(v.sign(5), (c * 10 + 5) * 10**20 + 1, -34), -13)
        w.quantize(ctx, mk(0, 5, -14), -13)
        w.quantize(ctx, mk(1, 15, -14), -13)
        w.quantize(ctx, mk(0, 1, -14), -13)
        w.quantize(ctx, mk(1, 1, MIN_ETINY), -13)
        w.quantize(ctx, mk(0, 10**14 - 5, -14), -13)
        w.quantize(ctx, mk(1, 10**14 - 1, -14), -13)
    w.section("quantize: results at and beyond 32 digits")
    boundary = [
        "9999999999999999999.9999999999999", "9999999999999999999.99999999999995",
        "9999999999999999999.99999999999994", "-9999999999999999999.99999999999996",
        "999999999999999999.99999999999995", "1E19", "-1E19", "1E18", "12345678901234567890",
        "1234567890123456789.0123456789012", "1234567890123456789.01234567890125",
        "21000000.00000000000005", "21000000.000000000000049999", "999999999999999.99999999999995",
        "1E15", "99999999999999999999999999999999", "0.99999999999995", "-0.00000000000005",
    ]
    for s in boundary:
        for ctx in (RP2_CTX, (32, "down"), (32, "up"), (28, "half_even"), (34, "half_even")):
            w.quantize(ctx, Decimal(s), -13)
    w.section("quantize: exponent limits and zeros")
    for ctx in (RP2_CTX, (5, "half_even"), (32, "ceiling")):
        etiny = -999999 - ctx[0] + 1
        for exp in (999999, 1000000, etiny, etiny - 1, 0, -13):
            for x in (mk(0, 0, 0), mk(1, 0, -20), mk(0, 1, 0), mk(1, 5, -1), mk(0, 123, 999990), mk(0, 1, -999999)):
                w.quantize(ctx, x, exp)
        w.quantize(ctx, mk(0, 1, MAX_EMAX), 999999)
        w.quantize(ctx, mk(0, 1, MIN_ETINY), etiny)
        w.quantize(ctx, mk(0, 0, MIN_ETINY), -13)
        w.quantize(ctx, mk(1, 0, MAX_EMAX), -13)


def gen_unary(w: Writer, v: Values, r: random.Random) -> None:
    w.section("neg/abs/plus")
    for _ in scaled(170):
        w.unary(r.choice(["neg", "abs", "plus"]), pick_ctx(r), v.any())
    for ctx in all_contexts([32, 3]):
        for x in (mk(0, 0, 0), mk(1, 0, 0), mk(1, 0, -2), mk(0, 0, MIN_ETINY), mk(1, 0, MAX_EMAX)):
            for op in ("neg", "abs", "plus"):
                w.unary(op, ctx, x)
        for x in (mk(1, 10 ** (ctx[0] + 1) - 5, -4), mk(0, 10 ** ctx[0] * 10 + 5, -7), mk(1, 1, 1000000), mk(0, 25, -1000031)):
            for op in ("neg", "abs", "plus"):
                w.unary(op, ctx, x)


def gen_cmp(w: Writer, v: Values, r: random.Random) -> None:
    w.section("cmp: random pairs")
    for _ in scaled(260):
        w.cmp(v.any(), v.any())
    w.section("cmp: equal values in different representations, zeros, and neighbours")
    for _ in scaled(60):
        x = v.any()
        sign, digits, exp = x.as_tuple()
        coeff = int("".join(map(str, digits)))
        k = min(r.randint(1, 30), exp - MIN_ETINY)
        if k <= 0:
            continue
        w.cmp(x, mk(sign, coeff * 10**k, exp - k))
        w.cmp(x, mk(sign, coeff * 10**k + 1, exp - k))
        w.cmp(mk(sign, coeff * 10**k - 1 if coeff else 0, exp - k), x)
    for a in (mk(0, 0, 0), mk(1, 0, 0), mk(0, 0, 999999), mk(1, 0, MIN_ETINY), mk(0, 1, MIN_ETINY), mk(1, 1, MIN_ETINY)):
        for b in (mk(0, 0, -5), mk(1, 0, 3), mk(0, 1, MAX_EMAX), mk(1, 1, MAX_EMAX), mk(0, 1, 0)):
            w.cmp(a, b)
            w.cmp(b, a)


def gen_rp2(w: Writer, v: Values, r: random.Random) -> None:
    exact = Context(prec=400, traps=[decimal.Inexact, decimal.InvalidOperation, decimal.Overflow])
    deltas = [
        "0", "1E-14", "4E-14", "4.9999999E-14", "4.99999999999999999999E-14", "5E-14",
        "5.0000001E-14", "5.00000000000000000001E-14", "6E-14", "9.9999999E-14", "1E-13",
        "1.4999E-13", "1.5E-13", "2.5E-13", "3.5E-13", "1E-12", "1E-30", "1E-8", "0.01",
    ]
    w.section("rp2: differences around the 13-place boundary")
    for ctx in [RP2_CTX] * 3 + [(32, "half_up"), (32, "down"), (32, "floor"), (32, "ceiling"), (28, "half_even")]:
        for delta in deltas:
            base = r.choice([v.crypto, v.fiat, v.price, v.rate, v.long])()
            d = Decimal(delta) if r.randrange(2) else -Decimal(delta)
            other = exact.add(base, d)
            w.rp2(ctx, other, base)
            w.rp2(ctx, base, other)
    w.section("rp2: random pairs")
    for _ in scaled(160):
        w.rp2(pick_ctx(r), v.any(), v.any())
    w.section("rp2: same values in different representations")
    for _ in scaled(30):
        x = r.choice([v.crypto, v.fiat])()
        sign, digits, exp = x.as_tuple()
        coeff = int("".join(map(str, digits)))
        w.rp2(RP2_CTX, x, mk(sign, coeff * 1000, exp - 3))
        w.rp2(RP2_CTX, mk(1 - sign, coeff, exp), x)
    w.section("rp2: differences whose 13-place form needs more than prec digits")
    for s, t in (("9999999999999999999.9999999999999", "0"), ("1E19", "0"), ("0", "1E19"),
                 ("9999999999999999999.99999999999995", "0"), ("21000000", "-9999999999999999999"),
                 ("12345678901234567890", "12345678901234567890"), ("1E+999999", "1E+999999"),
                 ("9E+999999", "-9E+999999"), ("1E+1000000", "0"), ("1E15", "0"), ("-1E15", "0")):
        for ctx in (RP2_CTX, (28, "half_even"), (34, "half_even")):
            w.rp2(ctx, Decimal(s), Decimal(t))


def main() -> int:
    global SCALE
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--seed", type=int, default=SEED, help="random seed (stress runs only)")
    parser.add_argument("--scale", type=float, default=1.0, help="multiply generated case counts")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="where to write the vectors")
    args = parser.parse_args()
    SCALE = args.scale
    r = random.Random(args.seed)
    v = Values(r)
    w = Writer()
    gen_parse(w, r)
    gen_parse_unicode(w)
    gen_int(w, r)
    gen_text(w, v, r)
    gen_add_sub(w, v, r)
    gen_mul(w, v, r)
    gen_div(w, v, r)
    gen_quantize(w, v, r)
    gen_unary(w, v, r)
    gen_cmp(w, v, r)
    gen_rp2(w, v, r)
    body = HEADER.replace("{seed}", str(args.seed)) + "\n".join(w.lines) + "\n"
    size = len(body.encode("ascii"))
    if args.output == OUTPUT and size >= MAX_BYTES:
        print(f"vector file would be {size} bytes, over the {MAX_BYTES} limit", file=sys.stderr)
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="ascii")
    cases = sum(1 for line in w.lines if not line.startswith("#"))
    print(f"wrote {cases} cases, {size} bytes to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
